### ISSUE TITLE
Already present MQTT Broker not usable

### ISSUE THREAD

**Issue by Tan-DE** [ioBroker/ioBroker.sonoff#1]
Is it possible to use an already installed and running mqtt broker or mqtt adapter (with authentication)? Regards Tan

**Comment by GermanBluefox** [comment]
You can use Sonoff adapter on other port.
This adapter is just for simplifying of the objects, so you can directly control the devices with Alexa and vis.

**Comment by Tan-DE** [comment]
Yes, I know, but I already have  a central Broker and really like your idea, to move the sonoff mqtt logic into a seperate adapter instead of scripts and helper objects. Maybe as a feature request for the future: Configurable internal or external mqtt server. Btw: Thanks for your amazing work!!

**Comment by GermanBluefox** [comment]
>Maybe as a feature request for the future: 

No. It is really hard job to configure it all...
