### ISSUE TITLE
[Feature Request] Standart MQTT issues

### ISSUE THREAD

**Issue by ManuelJimenezBuendia** [ioBroker/ioBroker.sonoff#10]
Thank you for your great work with the adapter!!! It's much easier to use than the regular MQTT adapter when you are interfacing sonoff devices with iobroker.
However, I have found an issue trying to use MQTT commands which are not implemented in your code. For example, I have a TH10 module with a WS2812 RGB LED strip and I would like to send WS2812 related MQTT commands (i.e. "cmnd/TH10/scheme 5"). I'm currently using Node-RED with MQTT output node for this purpose. When I try to do this, it seems the adapter doesn't send the command to the TH10 module. The same would apply if I wanted to issue a "cmnd/TH10/POWER1" command to the module using the MQTT output node. Would there be a way that you adapter behaved just like an MQTT broker for the commands that are not implemented?
Thanks in advance.

**Comment by Alveran81** [comment]
Same Problem here.

**Comment by svenp** [comment]
Same Problem here.
I use 
mosquitto_pub -h 192.168.0.100 -p 1884 -i Henschke_3D_Drucker -u user -P pass -t Henschke_3D_Drucker/POWER -m 'true' 
or
mosquitto_pub -h 192.168.0.100 -p 1884 -i cmnd/Henschke_3D_Drucker -u user -P pass -t Henschke_3D_Drucker/POWER -m 'true' 

on Raspberry Pi to switch the sonoff Pow.

The var in IOBroker switch to state true, for a short time before the next mqqt Message is comming from tasmota, but tasmota does not switch the Relais on . 
When i set the var in IOBroker with mouseklick to state true, the tasmota switch the Relais on.

Tasmota Log when send mosquitto_pub:

- `20:03:29 MQT: Verbindungsversuch...
- 20:03:29 MQT: verbunden
- 20:03:29 MQT: tele/%topic%/LWT = online (beibehalten)
- 20:03:29 MQT: cmnd/%topic%/POWER = 
- 20:03:30 MQT: Verbindungsversuch...
- 20:03:30 MQT: verbunden
- 20:03:30 MQT: tele/%topic%/LWT = online (beibehalten)
- 20:03:30 MQT: cmnd/%topic%/POWER = 
- 20:03:31 MQT: Verbindungsversuch...
- 20:03:31 MQT: verbunden
- 20:03:31 MQT: tele/%topic%/LWT = online (beibehalten)
- 20:03:31 MQT: cmnd/%topic%/POWER =`

**Comment by l3d00m** [comment]
If i understood this adapter correctly, it does not allow external incoming commands to other devices. It works only as an MQTT broker for sonoff devices that just publish their own state to the adapter. 

This is the thing I dislike most about this adapter, I would much prefer to be able to use an external MQTT broker/server (like the plugin in ioBroker).

As I've got a bit spare time, I'm thinking about rewriting this plugin so it works as described above. Because it is a major feature break I will probably make a fork and a new plugin. Any thoughts what would be best here, @GermanBluefox?

**Comment by GermanBluefox** [comment]
I think, that "new option in this adapter" is better, so we not must to maintain 2 adapters.

**Comment by l3d00m** [comment]
I would say this is still relevant (although I was quite optimistic when I said I had time to rewrite, I definitely don't have that currently)

**Comment by l3d00m** [comment]
I would say this is still relevant
