### ISSUE TITLE
error illuminance  BH1750 v.2.3.1

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.sonoff#101]
after the update to 2.3.1 I get the following errrors

sonnoff basic with BH1750

`

sonoff.0 | 2019-10-23 15:42:10.319 | error | (27232) After: {"Time":"2019-10-23T15:42:09","BH1750":{"Illuminance":232}}
-- | -- | -- | --
sonoff.0 | 2019-10-23 15:42:10.319 | error | (27232) Before: {"Time":"2019-10-23T15:42:09","BH1750":{"Illuminance":232}}

`

do you need additional info ?

**Comment by GermanBluefox** [comment]
please use 2.3.2

**Comment by liv-in-sky** [comment]
thank you  - I have installed the adapter again - now it seem to be ok - no error at the moment - the adapter still shows version 2.3.1 ? at he admin
