### ISSUE TITLE
datapoints confusion

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.sonoff#102]
I habe made a script which check datapoint

I always get these warnings - is this an issue or is my script wrong - it checks the type of the datapoint value and compares with the common.type of the dp

![Image 3](https://user-images.githubusercontent.com/18462890/67400134-802b9d00-f5ad-11e9-9464-5a25a1933980.png)

**Comment by GermanBluefox** [comment]
Let's take first DP WemosTasmotaMov1.Wifi_channel.
Who selected the type of DP in the object? You or adapter?

**Comment by modmax** [comment]
Is this an error or can the isse be closed?
Note that datapoints will be created just once. If later on the datatpoint definition is changed, then the type will not be updated cause the state is already present.

**Comment by liv-in-sky** [comment]
is closed
