### ISSUE TITLE
Warum wurde Issues  #95 nicht übernommen?

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.sonoff#103]
Der Ersteller hatte es selbst geschlossen. Leider wurde diese geniale Änderung nicht mit in die neue Version übernommen.
Durch die Änderung wird sofort nach erreichen der gewünschten Position diese auch angezeigt und nicht erst nach der eingestellten Telemetrieperiode.

Hier noch mal die Änderung:
/opt/iobroker/node_modules/iobroker.sonoff/lib/datapoints.js

**SHUTTER1:      {type: 'number',  role: 'state',                    read: true, write: false, unit: '%'},**
![grafik](https://user-images.githubusercontent.com/36501310/67463894-920b4f80-f642-11e9-80d7-bc62b1146bb9.png)

**Comment by GermanBluefox** [comment]
I do not monitor the closed issues and PRs.
The solution will appear in the next version. Thank you.

**Comment by ihavenonick** [comment]
Ok, kann passieren :-)
Ich meine das hatte auch im Forum gestanden und deshalb auch auf Deiner todo Liste.

**Comment by Apollon77** [comment]
Forum können wir teilweise noch weniger monitoren

**Comment by ihavenonick** [comment]
Ist nun mit drin

**Comment by he-so** [comment]
I would appreciate this change being included!
https://github.com/ioBroker/ioBroker.sonoff/issues/95

**Comment by modmax** [comment]
Ticket kann geschlossen werden.
Aktuell in der 2.3.3 vorhanden.

**Comment by Apollon77** [comment]
Danke!
