### ISSUE TITLE
Fehlender Datenpunkt nach MQTT veröffentlichung

### ISSUE THREAD

**Issue by mczeus** [ioBroker/ioBroker.sonoff#105]
wenn ich in Tasmota eine Rule anlege
"on analog#a0div10 do publish Feuchtigkeit/ %value% endon"
wird diese auch gesendet aber im Sonoff Adapter bekomme ich keinen Datenpunkt.

Kann ich den auch manuell einfügen?

**Comment by mczeus** [comment]
So auch bei dem fork
https://github.com/umar14/Sonoff-Tasmota
Wäre schön wenn man die auch mit dem Sonoff adapter verwenden könnte!

**Comment by DerT94** [comment]
gibt es dazu schon etwas neues?
Habe das selbe Problem.

**Comment by mczeus** [comment]
kann in "datapoints.js" manuell hinzugefügt werden.
Werden aber überschrieben im falle eines Updates des Adapters.
