### ISSUE TITLE
MQTT Server - Read Values with Client

### ISSUE THREAD

**Issue by merlin2533** [ioBroker/ioBroker.sonoff#107]
When we push data to the mqtt server of the adapter, we can't read the values with a other mqtt client. Is there an a other option to use a external mqtt server?

Thanks

**Comment by Apollon77** [comment]
Can you please describe your topic in more detail ... ideally with an example?

**Comment by merlin2533** [comment]
In the adapter, there is a MQTT included, we have a lot of other mqtt clients where we want to push data also to io broker. there a other adapter can be use. 

The request is, the included mqtt server can be open for other mqtt sensors or a external mqtt server can be configure, that we have all mqtt information in one mqtt server

**Comment by LaLinea** [comment]
This one could also be integrated in this one: https://github.com/ioBroker/ioBroker.sonoff/issues/69
