### ISSUE TITLE
Support Sensor BMp680

### ISSUE THREAD

**Issue by merlin2533** [ioBroker/ioBroker.sonoff#108]
Hello,

we have implement a lot of different sensors, is there an option e.g. BMP680 to get the information as the implemented sensors yet?

A other Sensor we use a sk04t.

**Comment by Apollon77** [comment]
Please provide the debug log for this sensor. put adapter into debug log mode and check the logfile

**Comment by merlin2533** [comment]
The Sensor have in the lof of tasmota, following JSON:

09:53:01 MQT: SonnOff-BME680/gas/SENSOR = {"Time":"2019-12-11T09:53:01","BME680":{"Temperature":20.0,"Humidity":36.7,"Pressure":963.4,"Gas":1680.35},"PressureUnit":"hPa","TempUnit":"C"}
