### ISSUE TITLE
DHT 22 es wird nur die Temparatur ausgelesen

### ISSUE THREAD

**Issue by oOPsychokillerOo** [ioBroker/ioBroker.sonoff#11]
Hallo bei meinem Sonoff mit dem DHT 22 Sensor wird nur die Temperatur ausgelesen nicht jedoch die Luftfeuchtigkeit.

"DHT22":{"Temperatur":19.5,"Feuchtigkeit":46.1},"TempUnit":"C"}

Die Adapter Version ist 1.0.0

Fehler ist in der /lib/server.js
Falsch:
 Luftfeutigkeit: {type: 'number', role: 'value.humidity', read: true, write: false, unit: '%'},
Richtig:
 Feuchtigkeit: {type: 'number', role: 'value.humidity', read: true, write: false, unit: '%'},

**Comment by GermanBluefox** [comment]
Wieso heißt es Feuchtigkeit und nicht Luftfeutigkeit?

**Comment by oOPsychokillerOo** [comment]
Das müssen Sie die Entwickler von Tasmota fragen.
Abgesehen davon das Luftfeutigkeit echt komisches deutsch ist. XD

**Comment by GermanBluefox** [comment]
Please test with 1.0.1
