### ISSUE TITLE
Wrong unit on humidity

### ISSUE THREAD

**Issue by anwa** [ioBroker/ioBroker.sonoff#111]
Hi,
i have on all humidity sensors in objects, degree celsius and not %

![grafik](https://user-images.githubusercontent.com/1856906/71306689-fbf66a00-23e3-11ea-983c-512e4205e6a0.png)

**Comment by vr6syncro** [comment]
up! still wrong.

**Comment by gerold-penz** [comment]
Unfortunately I have the same problem with these devices:
- "Sonoff TH16" with SI7021 sensor
- "D1 Mini" with BME280 sensor

**Comment by gerold-penz** [comment]
> Unfortunately I have the same problem with these devices:
> 
> * "Sonoff TH16" with SI7021 sensor
> * "D1 Mini" with BME280 sensor

These are messages from my devices:
```
tele/bad/thermometer/SENSOR = {
    "Time":"2021-01-17T10:58:28",
    "SI7021":{
        "Temperature":18.4,
        "Humidity":57.1,
        "DewPoint":9.7
    },
    "TempUnit":"C"
}


stat/keller/thermometer/STATUS10 = {
    "StatusSNS":{
        "Time":"2021-01-17T11:11:39",
        "BME280":{
            "Temperature":21.2,
            "Humidity":80.4,
            "DewPoint":17.7,
            "Pressure":755.7
        },
        "PressureUnit":"hPa",
        "TempUnit":"C"
    }
}
```

**Comment by gerold-penz** [comment]
> Unfortunately I have the same problem with these devices:
> 
> * "Sonoff TH16" with SI7021 sensor
> * "D1 Mini" with BME280 sensor

I am using ioBroker.sonoff version "2.3.3".

**Comment by anwa** [comment]
Ok, ich glaube ich habe das Problem gefunden:
![Screenshot_20210123_095821](https://user-images.githubusercontent.com/1856906/105573991-bf710c80-5d61-11eb-9fa4-462f84460290.png)
Sieht nach ersten Tests gut aus.
Das Problem ist das die Variable unit '°C' enthält und dadurch der bereits korrekte '%' Wert in obj.data.common.unit überschrieben wird. obj.data.common.unit wird durch die Datei /lib/datapoints.js befüllt und sollte eigentlich stimmen.
Ich verstehe den Sinn hinter diesen Code-Zeilen eh nicht ganz! Eigentlich sollte doch alles schon richtig gesetzt sein, warum dann hier nochmal die Sonderbehandlung für Temperature und Humidity?
Wer meine Änderungen Testen will: In #141 gibt es ein paar Infos dazu.
