### ISSUE TITLE
PIR

### ISSUE THREAD

**Issue by merlin2533** [ioBroker/ioBroker.sonoff#113]
Good Evening,
today we have try to implement a PIR Sensor with sonoff/tasmota. It Works on the tasmota side very easy and finde but when we want to integrate it on the iobroker with the adapter, the datafield will not generated

Howto
https://github.com/arendst/Tasmota/wiki/PIR-Motion-Sensors

MQTT sends:
21:06:25 RUL: SWITCH1#STATE=0 performs "publish stat/nodemcu-pir1/PIR1 OFF"
21:06:25 MQT: stat/nodemcu-pir1/PIR1 = OFF
21:06:28 RUL: SWITCH1#STATE=1 performs "publish stat/nodemcu-pir1/PIR1 ON"
21:06:28 MQT: stat/nodemcu-pir1/PIR1 = ON
21:08:10 RUL: SWITCH1#STATE=0 performs "publish stat/nodemcu-pir1/PIR1 OFF"
21:08:10 MQT: stat/nodemcu-pir1/PIR1 = OFF
21:08:12 RUL: SWITCH1#STATE=1 performs "publish stat/nodemcu-pir1/PIR1 ON"
21:08:12 MQT: stat/nodemcu-pir1/PIR1 = ON

Config of rules:
SwitchMode1 1
SwitchTopic 0
Rule1 on switch1#state=1 do publish stat/%topic%/PIR1 ON endon on switch1#state=0 do publish stat/%topic%/PIR1 OFF endon
Rule1 1

Is there any option to get the data inside, with a other topic?

**Comment by Seqway** [comment]
I have exactly the same problem !
Do you have already a solution that is working that the values inside iobroker sonoff are updating ?
