### ISSUE TITLE
Keine Rückmeldung über Power_State beim Sonoff TH16

### ISSUE THREAD

**Issue by RalfEngelberth** [ioBroker/ioBroker.sonoff#114]
Ich habe mir einen Sonoff TH16 über den Sonoff-Adapter in IoBroker eingebunden.
In IoBroker wird mir auch alles in den Objekten angezeigt.
Leider ändert sich aber die Rückmeldung Power_State nicht immer wenn ich schalte.
Ob ich über IObroker oder direkt über Web schalte macht keinen Unterschied bei dem Power_State.
Mit dem mqtt-Adapter geht es.

Warum?

**Comment by Basti149** [comment]
> 
> 
> Ich habe mir einen Sonoff TH16 über den Sonoff-Adapter in IoBroker eingebunden.
> In IoBroker wird mir auch alles in den Objekten angezeigt.
> Leider ändert sich aber die Rückmeldung Power_State nicht immer wenn ich schalte.
> Ob ich über IObroker oder direkt über Web schalte macht keinen Unterschied bei dem Power_State.
> Mit dem mqtt-Adapter geht es.
> 
> Warum?

Hast du irgendwelche Lerzeichen bzw Sonderzeichen in deinem Namen????
