### ISSUE TITLE
Request: Possibility to use TDM with this Adapter

### ISSUE THREAD

**Issue by kugelkopf123** [ioBroker/ioBroker.sonoff#117]
Hey. 
It would be nice if the TDM (https://github.com/jziolkowski/tdm) Tasmota Device Manager would work with this Adapter.
I have no Idea what the problem is. But as far as i know, with a normal MQTT Broker, TDM works fine.

Greetings

**Comment by itProfi** [comment]
It would be nice if the TDM (https://github.com/jziolkowski/tdm)!
