### ISSUE TITLE
data is not displayed or updated 

### ISSUE THREAD

**Issue by ImhotepDE** [ioBroker/ioBroker.sonoff#118]
Hello,

I have integrated a Gosund SP1 v23 module via IOB. Unfortunately the data is not displayed or updated 

sonoff.0.Plug_01.ENERGY_Power
sonoff.0.Plug_01.ENERGY_Current
etc.

The only thing that works is sonoff.0.Plug_01.POWER

Is this a mistake or am I doing something wrong?

Thanks

**Comment by Maddin44** [comment]
I had a similar Problem with Gosund SP 111 V 1.1. It took always 5 Minutes till they were updated. Now i have set in the tasmota console TelePeriod 30 and now all 30s the values are updated.

**Comment by anwa** [comment]
The default Telemetrieperiode is 300s so tasmota send all 5 Minutes new STATE/SENSOR values.
I think its a bug in tasmota, to dont send changes direktly to MQTT
