### ISSUE TITLE
Deutsche übersetzung

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.sonoff#12]
Da hier viele probleme mit der Deutschen übersetzung haben und der adapter dann nicht geht. Hier die Logs für die neuen json werte:

`

sonoff.0 | 2017-12-17 12:11:46.453 | debug | Client [Sonoff4ch] pingreq
-- | -- | -- | --
sonoff.0 | 2017-12-17 12:11:45.940 | debug | Client [SonoffPOW] pingreq
sonoff.0 | 2017-12-17 12:11:41.235 | debug | [SonoffPOW] Received: tele/SonoffPOW/ENERGIE = {"Zeit":"2017.12.17 12:11:40","Total":20.611,"gestern":0.257,"heute":0.111,"Punkt":0,"Leistung":3,"Faktor":0.18,"Spannung":216,"Strom":0.083}
sonoff.0 | 2017-12-17 12:11:41.188 | debug | [SonoffPOW] Received: tele/SonoffPOW/STATUS = {"Zeit":"2017.12.17 12:11:40","Laufzeit":136,"VCC":3.240,"POWER":"ON","WLAN":{"AP":1,"SSID":"IOT","RSSI":76,"APMac":"CC:CE:1E:AE:7B:F9"}}
sonoff.0 | 2017-12-17 12:11:36.846 | debug | Client [ESPClient5] pingreq
sonoff.0 | 2017-12-17 12:11:31.451 | debug | Client [Sonoff4ch] pingreq
sonoff.0 | 2017-12-17 12:11:30.936 | debug | Client [SonoffPOW] pingreq
sonoff.0 | 2017-12-17 12:11:26.193 | debug | [SonoffPOW] Received: tele/SonoffPOW/ENERGIE = {"Zeit":"2017.12.17 12:11:25","Total":20.611,"gestern":0.257,"heute":0.111,"Punkt":0,"Leistung":5,"Faktor":0.26,"Spannung":218,"Strom":0.083}
sonoff.0 | 2017-12-17 12:11:26.189 | debug | [SonoffPOW] Received: tele/SonoffPOW/STATUS = {"Zeit":"2017.12.17 12:11:25","Laufzeit":136,"VCC":3.240,"POWER":"ON","WLAN":{"AP":1,"SSID":"IOT","RSSI":82,"APMac":"CC:CE:1E:AE:7B:F9"}}
sonoff.0 | 2017-12-17 12:11:21.845 | debug | Client [ESPClient5] pingreq
sonoff.0 | 2017-12-17 12:11:18.092 | debug | stateChange sonoff.0.Sonoff4ch.POWER2: {"val":false,"ack":true,"ts":1513509078090,"q":0,"from":"system.adapter.sonoff.0","lc":1513509078090}
sonoff.0 | 2017-12-17 12:11:18.088 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/POWER2 = OFF
sonoff.0 | 2017-12-17 12:11:18.083 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/ERGEBNIS = {"POWER2":"OFF"}
sonoff.0 | 2017-12-17 12:11:17.601 | debug | stateChange sonoff.0.Sonoff4ch.POWER2: {"val":true,"ack":true,"ts":1513509077599,"q":0,"from":"system.adapter.sonoff.0","lc":1513509077599}
sonoff.0 | 2017-12-17 12:11:17.598 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/POWER2 = ON
sonoff.0 | 2017-12-17 12:11:17.596 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/ERGEBNIS = {"POWER2":"ON"}
sonoff.0 | 2017-12-17 12:11:17.117 | debug | stateChange sonoff.0.Sonoff4ch.POWER1: {"val":false,"ack":true,"ts":1513509077116,"q":0,"from":"system.adapter.sonoff.0","lc":1513509077116}
sonoff.0 | 2017-12-17 12:11:17.115 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/POWER1 = OFF
sonoff.0 | 2017-12-17 12:11:17.066 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/ERGEBNIS = {"POWER1":"OFF"}
sonoff.0 | 2017-12-17 12:11:16.444 | debug | Client [Sonoff4ch] pingreq
sonoff.0 | 2017-12-17 12:11:16.376 | debug | stateChange sonoff.0.Sonoff4ch.POWER1: {"val":true,"ack":true,"ts":1513509076375,"q":0,"from":"system.adapter.sonoff.0","lc":1513509076375}
sonoff.0 | 2017-12-17 12:11:16.374 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/POWER1 = ON
sonoff.0 | 2017-12-17 12:11:16.372 | debug | [Sonoff4ch] Received: stat/sonoff_4ch/ERGEBNIS = {"POWER1":"ON"}
sonoff.0 | 2017-12-17 12:11:15.946 | debug | Client [SonoffPOW] pingreq
sonoff.0 | 2017-12-17 12:11:10.974 | debug | [SonoffPOW] Received: tele/SonoffPOW/ENERGIE = {"Zeit":"2017.12.17 12:11:10","Total":20.611,"gestern":0.257,"heute":0.111,"Punkt":0,"Leistung":5,"Faktor":0.24,"Spannung":217,"Strom":0.093}
sonoff.0 | 2017-12-17 12:11:10.925 | debug | [SonoffPOW] Received: tele/SonoffPOW/STATUS = {"Zeit":"2017.12.17 12:11:10","Laufzeit":136,"VCC":3.240,"POWER":"ON","WLAN":{"AP":1,"SSID":"IOT","RSSI":76,"APMac":"CC:CE:1E:AE:7B:F9"}}
sonoff.0 | 2017-12-17 12:11:09.604 | debug | [Sonoff4ch] Received: tele/sonoff_4ch/STATUS = {"Zeit":"2017.12.17 12:11:09","Laufzeit":136,"VCC":3.226,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","WLAN":{"AP":1,"SSID":"IOT","RSSI":7
sonoff.0 | 2017-12-17 12:11:06.857 | debug | Client [ESPClient5] pingreq
sonoff.0 | 2017-12-17 12:11:01.443 | debug | Client [Sonoff4ch] pingreq
sonoff.0 | 2017-12-17 12:11:00.777 | debug | Client [SonoffPOW] pingreq
sonoff.0 | 2017-12-17 12:10:55.970 | debug | [SonoffPOW] Received: tele/SonoffPOW/ENERGIE = {"Zeit":"2017.12.17 12:10:55","Total":20.611,"gestern":0.257,"heute":0.111,"Punkt":0,"Leistung":6,"Faktor":0.28,"Spannung":216,"Strom":0.100}
sonoff.0 | 2017-12-17 12:10:55.923 | debug | [SonoffPOW] Received: tele/SonoffPOW/STATUS = {"Zeit":"2017.12.17 12:10:55","Laufzeit":136,"VCC":3.241,"POWER":"ON","WLAN":{"AP":1,"SSID":"IOT","RSSI":76,"APMac":"CC:CE:1E:AE:7B:F9"}}
sonoff.0 | 2017-12-17 12:10:51.801 | debug | stateChange sonoff.0.ESPClient5.alive: {"val":true,"ack":true,"ts":1513509051800,"q":0,"from":"system.adapter.sonoff.0","lc":1513509051800}

`

**Comment by vr6syncro** [comment]
and some more:

sonoff.0   2017-12-31 14:41:55.139   debug   stateChange sonoff.0.Soff-Test.AM2301_Temperatur: {"val":17.7,"ack":true,"ts":1514727715136,"q":0,"from":"system.adapter.sonoff.0","lc":1514726214408}
sonoff.0   2017-12-31 14:41:55.134   debug   [Soff-Test] Received: tele/sonoff/SENSOR = {"Zeit":"2017.12.31 14:41:54","AM2301":{"Temperatur":17.7,"Feuchtigkeit":63.3},"TempUnit":"C"}
sonoff.0   2017-12-31 14:41:55.046   debug   [Soff-Test] Received: tele/sonoff/STATUS = {"Zeit":"2017.12.31 14:41:54","Laufzeit":1,"VCC":3.148,"POWER":"OFF","WLAN":{"AP":1,"SSID":"Fairpictures","RSSI":100,"APMac":"5C:49:79:4C:1A:6D"}}

**Comment by GermanBluefox** [comment]
Please test with 1.0.1
