### ISSUE TITLE
topics "SerialReceived" and "SerialSend" not available

### ISSUE THREAD

**Issue by Ichda** [ioBroker/ioBroker.sonoff#120]
Hello,
I install a Serial communication with Tasmota 8.1.0.2 to a SINOTIMER WDS688. (Tuya  The with a Serial Command I get data back into the topics "SerialReceived".  I tested the MQTT Broker directly and it works fine.
Unfortunately the data is not displayed.

Thanks for support

**Comment by Ichda** [comment]
Websites:
[https://forum.cpha.pt/t/converter-um-medidor-disjuntor-tuya-de-calha-din-smtonoff-zmai-90-em-tasmota-e-integracao-no-ha/3688](https://forum.cpha.pt/t/converter-um-medidor-disjuntor-tuya-de-calha-din-smtonoff-zmai-90-em-tasmota-e-integracao-no-ha/3688)
or
[https://www.creationfactory.co/2019/12/reverse-engineering-zmai-90-din-rail.html](https://www.creationfactory.co/2019/12/reverse-engineering-zmai-90-din-rail.html)

18:44:07 MQT: stat/SINOTIMER_ENERGIE01/RESULT = {"SerialSend":"Done"}
18:44:07 MQT: stat/SINOTIMER_ENERGIE01/RESULT = {"T1":10,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
18:44:07 MQT: tele/SINOTIMER_ENERGIE01/RESULT = {"SerialReceived":"FE0108000000003823000000000000005000000000000000000000000000000010000070"}

Thanks

**Comment by Bettman66** [comment]
You can add the SerialSend5 object yourself as a string and send data. SerialReceived can also be sent to the adapter with a rule or script in Tasmota.
