### ISSUE TITLE
Data received from Gosund SP112 and SP1 is incorrect / out of sync

### ISSUE THREAD

**Issue by jensb** [ioBroker/ioBroker.sonoff#122]
I have several Gosund SP1 and SP112 (those with 2 USB ports) in my house running Tasmota 8.1 and 8.2.
I also run ioBroker with all updates applied on a Raspberry Pi 4B.
Data is received by ioBroker and saved in an Influx database.

My issue is that the data which is received from the Gosund devices is correct, but for some reason the data displayed by ioBroker is incorrect - UNLESS I enable debug logging, in which case suddenly all data becomes correct.

Example: Right now at 11:53 one of my Gosund devices is recording a current of  86W, displays this correctly in the Web UI and sending a MQTT message to ioBroker:

```
May 13 11:53:14 tasmota-4121 ESP-MQT: tele/tasmota/SENSOR = {"Time":"2020-05-13T10:53:14","ENERGY":{"TotalStartTime":"2020-03-19T21:45:24","Total":56.223,"Yesterday":0.936,"Today":0.289,"Period":0,"Power":86,"ApparentPower":130,"ReactivePower":98,"Factor":0.66,"Voltage":236,"Current":0.552}}
```
This data is correct and is sent every 10 seconds. The data in the Tasmota Web UI is also correct.
But the data displayed by ioBroker, and sent to Influx, is not. And it's not even a few seconds off, or missing a brief change in load, it displays completely different values, which are several *minutes* late. Sometimes I switch a device on or off and ioBroker notices the change in current only after 10 minutes, or 30, ... it's not constant, so it's probably not a DST or time zone issue either (and all clocks are NTP synchronized anyway). The Gosund / Tasmota combo notices the change and displays it correctly after only a few seconds, and also sends off a correct MQTT message.

If I switch on debug logging in the ioBroker.sonoff adapter, then - suddenly - all values are up to date. But since this fills up my log quite quickly (I collect >100 values every ten seconds), I can't really do this, and also it's not really a solution.

Is this a known issue? How can I track this down further?

**Comment by steffengr74** [comment]
Das kann ich so bestätigen. Auch der Datenpunkt .power wird nicht aktualisiert bzw. wird wieder zurück gesetzt. Die Version 2.1.1 funktioniert dagegen wie sie soll. Daher nutze ich diese Version erstmal.

**Comment by jensb** [comment]
I watched this issue over winter, and it did not occur outside DST timezone, at all. Right now all my metering is correct and in the right moment. The issue only occurs when daylight savings time is active.

**Comment by homecineplexx** [comment]
i think this is a very similar problem to #126 and i have this problem already.

the reason why it works for x minutes after switching to debug mode is, because the adapter restarts during a loglevel change.
