### ISSUE TITLE
publish cmnd von zB Tasmota über Rule wird nicht akzeptiert ?

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.sonoff#128]
Hallo,
nach langem herumprobieren habe ich festgestellt, dass die PUBLISH Kommandos von zB Tasmota NIHCT von dem sonoff Adapter angenommen werden.

Ich habe einen PIR an einem NodeMcu hängen und wenn ich über Tasmota einen SWITCH1 definiere und keine RULES definiere und somit in Tasmota noch einen RELAY1 dann funkioniert der SONOFF Adapter und der Datenpunkt POWER1 wird beschrieben.
ABER laut Beschreibung von Tasmota braucht man kein Relay sondern kann das auch über eine RULE und einem publish machen. Leider scheint der sonoff Adapter das nicht zu akzeptieren.

Kann das mal jemand verifizieren / prüfen ?

**Comment by modmax** [comment]
Klappt das auch nihct wenn man in der Konfiguration des Sonoff-Adapters das "Automatische Erstellung von Zuständen" testweise für alle 3 Punkte (tele/SENSOR, tele/STATE, stat/RESULT) aktiviert?
Gesendet wird von dem Gerät wahrscheinlich was, aber vom Sonoff-Adapter nicht verarbeitet.
Eine DebugAusgabe des Adapters, wenn das PUBLISH ausgeführt wird, wäre immer hilfreich.

**Comment by Naibaf1** [comment]
Ich habe das gleiche Problem.
Im Debug steht, dass Werte ankommen:
(340715) [DVES_01] Received: stat/tasmota_01/PIR2 = ON
aber obwohl alle 3 Punkte aktiviert sind, wird bei mir kein Datenpunkt angelegt.
Auch gibt es kein updateState oder ähnliches zu dem Received.
Lediglich der Switch ist zu sehen, der wird alle 300 Sekunden aktualisiert.

**Comment by christophsobel** [comment]
Bei mir funktioniert folgendes:

`Rule1 on Switch1#state=1 do Publish tele/%topic%/SENSOR {"PIR2":true} endon`

In den Instanzeinstellungen muss nur "Automatische Erstellung von Zuständen Für tele/SENSOR" aktiv sein.

**Comment by krzysiek841** [comment]
Great :)
for me works with your help with timer :)
Rule1 on Switch1#state=1 do Backlog Publish tele/%topic%/SENSOR {"PIR":true}; RuleTimer1 30 endon on Rules#Timer=1 do Publish tele/%topic%/SENSOR {"PIR":false} endon

**Comment by Apollon77** [comment]
So fixed and can be closed?

**Comment by krzysiek841** [comment]
Yeah :)
