### ISSUE TITLE
Implementation Sonoff Touch "ledstate"

### ISSUE THREAD

**Issue by MrJuless** [ioBroker/ioBroker.sonoff#13]
hi bluefox,
first thank you for this great project.
Could you implement the ledstate in the adapter?
It would be great to controll this option, cause i want to set the wifi led of for the night, cause i am using a sonoff touch in the bedroom.

Best regards,
julian

**Comment by GermanBluefox** [comment]
Done?

**Comment by MrJuless** [comment]
Hi bluefox,
did it via tasmota. works fine for me. can be closed.

thanks,
julian
