### ISSUE TITLE
Unterordner bei Zigbee2Tasmota Devices

### ISSUE THREAD

**Issue by FreunderNacht** [ioBroker/ioBroker.sonoff#130]
Hallo,
wäre es möglich bei einem Zigbee2Tasmota Modul die einzelnen Zigbee-Geräte in Unterordner zu ordnen?

Das sieht im Moment so aus und ist ziemlich unübersichtlich:

![image](https://user-images.githubusercontent.com/69077006/90762707-c349c000-e2e5-11ea-819d-409d595c8971.png)

Vielen Dank
MfG

Freund der Nacht

**Comment by Apollon77** [comment]
Wie soll der Adapter denn sowas spezielles erkennen (und BTW was ist das überhaupt ein Zigbee2Tasmota Device??)

**Comment by FreunderNacht** [comment]
Hallo,
bezüglich der Zigbee2Tasmota hier einpaar links:

[https://zigbee.blakadder.com/zigbee2tasmota.html](url)

[https://tasmota.github.io/docs/Zigbee/](url)

[https://www.cnx-software.com/2019/12/23/tasmota-open-source-firmware-now-supports-zigbee-connectivity/](url)

[https://blog.moneybag.de/angetestet-zigbee2tasmota-gateway-mit-zigbee-cc2530-und-esp8266/](url)

So sehen die RAW-Daten eines Datenpunktes aus:
`{
  "_id": "sonoff.0.Zigbee2Tasmota_Flur_oben.ZbReceived_Bewegungsmelder_Balkon_Battery",
  "common": {
    "type": "number",
    "role": "value",
    "read": true,
    "write": false,
    "name": "Zigbee2Tasmota_Flur_oben ZbReceived Bewegungsmelder_Balkon  Battery"
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.sonoff.0",
  "user": "system.user.admin",
  "ts": 1596568803039,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`
Alle Daten die über Zigbee empfangen wurden werden anscheinend mit "ZbReceived"am Anfang gekennzeichnet.
In Tasmota bekommen die einzelnen Zigbee-Geräte eine eindeutige ID, die dann manuell durch einen individuellen Namen ergänzt werden kann, der dann auch übertragen wird.

Vielleicht lässt sich mit diesen Informationen die Sortierung in Unterordner realisieren.


MfG

Freund der Nacht

**Comment by madc882** [comment]
Die Sortierung in "Unterordner" lässt sich relativ simpel bewerkstelligen, vorausgesetzt du verwendest tasmota.

Mit "zbname"<deviceID>,<folder.friendlyname> erreichst du, dass die Werte bspw. in Unterordner geschrieben werden. Ich habe es bei mir mit temp.xyz, door.yxz oder window.yxz gelöst. Du kannst auch noch weitergehen und bspw. temp.wohnzimmer.device1 machen, dann bauen sich die States entsprechend auf. ioBroker interpretiert die Punkte als Anweisung für einen Ordner.
