### ISSUE TITLE
Unterstützung des RDM6300 im Sonoff Adapter

### ISSUE THREAD

**Issue by Basti149** [ioBroker/ioBroker.sonoff#131]
Wäre es möglich den RDM6300 RFID Scanner in den Sonoff Adapter zu integrieren. Leider funktoniert dieser nur mit den "normalen" MQTT Adapter. Im Adapter Sonoff wird dagegen kein Datenpunkt erstellt. 

Wenn weitere Informationen gebraucht werden kann ich diese noch gerne schicken.

08:03:07 RSL: tele/tasmota_4A72B7/SENSOR = {"Time":"2020-08-27T08:03:07","RDM6300":{"UID":"00434343"}}
oder
08:05:16 MQT: tele/tasmota_4A72B7/SENSOR = {"Time":"2020-08-27T08:05:16","RDM6300":{"UID":"0043202D"}}

**Comment by Basti149** [comment]
Ist der RDM6300 schon in der aktuellen Version des Sonoff Adapters integriert.

Were super??
Danke

**Comment by modmax** [comment]
Hast Du schom mal  in der Sonoff-Adapter-Konfiguration die Einstellung für "Automatische Erstellung von Zuständen" für "tele/SENSOR" aktiviert?

**Comment by Basti149** [comment]
> 
> 
> Hast Du schom mal in der Sonoff-Adapter-Konfiguration die Einstellung für "Automatische Erstellung von Zuständen" für "tele/SENSOR" aktiviert?

Danke für den Tipp
Nein habe ich noch nicht probiert. Da werde ich das mal versuchen. Ich wusste gar nicht das man das so einfach machen kann :+1:

**Comment by modmax** [comment]
Wenn es klappt, dann kann dieses issue ja geschlossen werden..

**Comment by Basti149** [comment]
> 
> 
> Wenn es klappt, dann kann dieses issue ja geschlossen werden..

Ich hatte den Hacken reingemacht. Nun hat es funktioniert. danke
