### ISSUE TITLE
Kryptische Ordner nach Neuinstalltion

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.sonoff#132]
In jedem dieser kryptischen pahoxxxxxx Ordner ist nur ein "alive" Datenpunkt drin.....und alles befindet sich im Ordner der Sonoff Adapter. Legt man einen neuen Sonoff Aktor an, kommt IMMER ein pahoxxxxxxx Ordner mit dazu.

Dabei gibt es in dem eigentlichen Aktor Ordner ebenfalls einen "alive" DP.

![2020-09-08 13_15_47-objects - ioBroker](https://user-images.githubusercontent.com/44617472/92471072-9ea38280-f1d7-11ea-840b-df0b463fad06.png)

**Comment by anwa** [comment]
Hi, kannst du ein paar mehr Infos liefern?
Wie ist der Pfad dieser Ordner, was meinst du mit Aktor anlegen?
Du stellst doch nur den Server/Port  in Tasmota ein, dann wird der Automatisch im Adapter angelegt.
Falls sich das Problem schon erledigt hat, wäre eine kurze Rückmeldung nett. Bitte schließe dann auch das Issue.

**Comment by JBSullivan** [comment]
Nein der Fall ist noch nicht erledigt, sondern wird immer kryptischer.

Ich hatte in der Zwischenzeit mal alle Sonoff Datenpunkte gelöscht, weil ich alle meine mit Tasmota geflashten Geräte auf Tasmota 9.1 hochgezogen hatte.

Jeder Aktor, der sich via der Tasmota MQTT Einstellung mit dem Sonoff Adapter  gekoppelt hatte, baute seine allseits bekannte Datenpunktstruktur auf.  Der Sonoff Objekte Baum, war danach völlig clean und es waren nur die Geräte gelistet die auch tatsächlich verbunden waren.

![image](https://user-images.githubusercontent.com/44617472/107153842-eccbd600-696f-11eb-869f-cc9131d615e3.png)


Ca. 1,5 Wochen später ging  es wieder los. ZUSÄTZLICH zu der bekannten Struktur, legten sich bei der Nutzung von Tasmota geflashten Geräten, plötzlich wieder neue Objekt Ordner selbstständig an. Diese hießen dieses mal nicht "paho......." sondern hatten und haben für mein Empfinden wahrlose Nummernfolge.

Der Inhalt dieser neuen Objekt ist aber wieder, wie damals auch, lediglich ein DP mit den Namen "alive".  Welche Nummer möglicherweise zu welchem Gerät gehören könnte, erschließt sich mir nicht. Wobei ich mich sowieso frage, warum ca. 1,5 Wochen nichts passiert ist bei der Nutzung von Tasmota Geräten und plötzlich geht es wieder los.

![image](https://user-images.githubusercontent.com/44617472/107153982-a88d0580-6970-11eb-836c-62d2f76f26e9.png)

Ich lösche heute diese ganzen "Nummern Objekte" nochmal und gucke mal, ob dies sich irgendwann wieder selbstständig erzeugen.

**Comment by Apollon77** [comment]
welche adapter version?

**Comment by JBSullivan** [comment]
Sonoff ist 2.4.0 - alle anderen Adapter und Hosts stehen auf LATEST und sind auch auf dem Stand 07.02.2021

**Comment by Apollon77** [comment]
Zeigst DU mal bitte die konfiguration? Vor allem das neue setting der 2.4.0

**Comment by JBSullivan** [comment]
![image](https://user-images.githubusercontent.com/44617472/107159571-455f9b00-6991-11eb-85d9-7a72233ebd12.png)

**Comment by anwa** [comment]
Diese komischen Nummern sind UUID's.
Aber ich kann mir noch kein Bild machen wo die herkommen...

**Comment by anwa** [comment]
Diese Datenpunkte (eigentlich devices) werden von der `function createClient` angelegt.
Die Frage ist nur, warum werden plötzlich soviele Geräte angelegt...

**Comment by JBSullivan** [comment]
Ich hatte ja gestern Abend alle devices (UUID) gelöscht. Heute ist wieder eine neue dazu gekommen. Habe jetzt die Instanz auf DEBUG gestellt. Mal gucken - vielleicht bekomme ich ja etwas hin. Das Problem ist halt das viele Sachen automatisiert ablaufen und man nicht immer sieht wenn so etwas angelegt wird.

**Comment by anwa** [comment]
Richtig, aber irgendwie müssen wir dem Problem ja auf die Spur kommen.
Und da du momentan der einzige mit dem Phänomen bist, bist du auch die einzige Quelle für Infos :)
Ich  habe den Code noch nicht ganz verstanden an der Stelle, um zu sagen was dazu führen könnte.
Da ist @Apollon77 und @GermanBluefox sicher fitter als ich.
Ich werde aber versuchen das Problem soweit einzugrenzen, das die Jungs das schneller finden können :)

**Comment by JBSullivan** [comment]
Leider musste ich das debugging abrechen, da meine Sonoffs auf teleperiod10 laufen und mir das ganze LOG voll geschrieben wurde. Seit meiner letzten Lösch Aktion der "krytischen" Ordner vor 4 Tagen, wurde auch nichts neues mehr angelegt.

Heute habe ich dann den Host Controller von 3.1.3 auf 3.1.6 geupdatet und prompt wurde wieder ein "Krypto Ordner" erzeugt.

Wie gesagt, leider war das debugging zu dem Zeitpunkt abgeschaltet.

Hier das LOG direkt nach dem Update, als die Sonoff Instanz neu gestartet wurde.  Die secret Nummer passt aber zu keiner der secret Nummern der Geräte mit "echtem" Namen.
`

sonoff.0 | 2021-02-12 18:22:40.311 | info | (1132) new object created: sonoff.0.b20edcb5-e7fb-474a-a952-47cf7c6abde0.alive
-- | -- | -- | --
sonoff.0 | 2021-02-12 18:22:40.305 | info | (1132) new object created: sonoff.0.b20edcb5-e7fb-474a-a952-47cf7c6abde0
sonoff.0 | 2021-02-12 18:22:40.294 | info | (1132) Client [b20edcb5-e7fb-474a-a952-47cf7c6abde0] connected with secret 1613150560293_4645

![image](https://user-images.githubusercontent.com/44617472/107802401-92f95080-6d61-11eb-8f14-4c5bec6121d7.png)
`

**Comment by anwa** [comment]
Nach langem Studium des Codes bin ich zu dem Schluss gekommen, das ein MQTT "connect packet" kommen muss, das der Adapter nicht korrekt bearbeiten kann bzw. das korrupt ist.
Da dieses Problem scheinbar nur bei dir auftritt, vermute ich das Problem in deinem Setup. Möglicherweise spielt eines deiner Geräte verrückt und sendet durch irgendein Ereignis connect Pakete. Möglicherweise WLAN Probleme.
Das ist jetzt natürlich schwer zu greifen, aber du könntest noch versuchen in Tasmota das Logging auf einen syslog server zu aktivieren (3 debug Level) und dann nach MQT connect meldungen im betroffenen Zeitraum suchen.

09:07:59.017 MQT: Verbindungsversuch...
09:07:59.025 MQT: verbunden
09:07:59.026 MQT: tele/D1mini_45A0C0/LWT = Online (beibehalten)
09:07:59.027 MQT: cmnd/D1mini_45A0C0/POWER = 

So sollten die aussehen, ich vermute, das bei dir der Part `D1mini_45A0C0` falsch ist, dadurch wird ein neues Objekt angelegt.
Alternativ könnte man natürlich auch einen LAN/MQTT Siffer (Wireshark) drauf ansetzen...

**Comment by anwa** [comment]
Ok, ich habe noch etwas gefunden:
https://github.com/eclipse/paho.mqtt.c
Es gibt eine mqtt client lib namens paho. Du hattest ja anfangs immer pahoxxxx clients bekommen.
Dieser wurden wahrscheinlich von einem client erzeugt, der diese lib benutzt.
Hast du noch andere Tools, die auf Tasmota/ioBroker.sonoff zugreifen?

**Comment by JBSullivan** [comment]
Was konkret meinst du mit andere Tools? Ich habe in Tasmota 9.1.0 (haben alle meine Geräte) natürlich noch BELKIN WeMo Emulation aktiviert, damit ich die Geräte auch über Alexa schalten kann. Außerdem habe ich noch eine Android App Namens Tasmota Controll auf dem einen Smartphone und HTTP Shortcuts auf einem zweiten  Smarthphone laufen.

Nach deinem Hinweis habe ich mit beiden Apps ausgiebig herum gespielt, aber es sind keine neuen Einträge dazu gekommen.  Im Grunde gibt es seit 10 Tagen keine Kryptischen Einträge mehr. 

Aber der Hinweis mit den anderen Tools ist Gut, den werde ich mal weiter beobachten, da ich auch TasmoAdmin von Zeit zu Zeit zum aktualisieren der Firmware einsetze.

Was du darüber geschrieben hast, habe ich nicht so wirklich verstanden. Muss ich dazu irgend welche Konsolen Befehle eingeben?

**Comment by anwa** [comment]
Ok, TasmoAdmin habe ich getestet, verursacht auch MQTT Traffik, aber bei mit keine Fehler.
Aber dein Log verrät ja schon, das es nicht am Adapter liegt. Es kommen einfach Pakete die kaputt/leer sind.
Möglicherweise liegt es an der WemosEmu/Alexa. Ich mache das direkt über ioBroker.

**Comment by anwa** [comment]
Wäre halt hilfreich dieses Paket mal zu sehen:
2021-02-17 20:30:48.540 - info: sonoff.0 (10600) Client [Pool Basic] connection closed: Error: Cannot parse topic
Wie sieht denn deine MQTT Konfig bei Pool Basic aus? Screenshot...
Hast du irgendwelche zusätzlichen Settings vorgenommen? CustomTopics z.b.
Oder was steht in TasmoAdmin beim Pool Basic unter Settings/MQTT? Sind da andere Prefixe, Topics oder Texte eingetragen?
Der sonoff Adapter geht von den default Settings aus, da es viel zu viele Möglichkeiten gibt. Die kann man nicht alle berücksichtigen. Woher sollte der Adapter z.B. wissen was der User mit "Pumpe läuft" meint.
Wenn man sowas braucht, kann man den MQTT Adapter nehemen und alles nach seinen Wünschen einstellen.

Was die Sachen angeht, die du nicht verstanden hast. Ich weis ja nicht, wie fitt du mit Comptern/Programmierung und Netzwerktechnik bist. Aber für Leute die nicht wissen was Wireshark ist, oder wie man ihn bedient, wird es sicher schwer dem Problem auf den Grund zu gehen. Ich kann dann von der Ferne nicht wirklich helfen. Das ist nicht Böse gemeint! Nicht jeder hat Lust sich mit dem Quatsch zu beschäftigen :)

**Comment by anwa** [comment]
Also meine Vorschläge für dich:
A: Die komischen Ordner Ignorieren/löschen
B1: Prüfen ob irgendwelche Änderungen in Tasmota gemacht wurden, die sich auf die MQTT Telegramme auswirken
B2: Die Fremdtools eine Zeitlang nicht benutzen/deinstalliern/löschen um sicher zu sein
B3: BELKIN WeMo deaktivieren (siehe B2) eventuell über die ioBroker Cloud eine Alexa Verbindung schaffen. Das funktioniert bei mir prächtig, sogar mit Siri zusammen
