### ISSUE TITLE
Sonoff ZBBridge

### ISSUE THREAD

**Issue by madc882** [ioBroker/ioBroker.sonoff#133]
Hey folks,

I just read, that new states and/or devices could be added easily. I managed to flash the new sonoff ZBBridge, which is actually the official device name, with tasmota and do not receive any TELE within the sonoff Adapter in iobroker. The States are completely missing - compared to the MQTT, where they do appear, but in a very inconvenient way. Would it be possible to add the device readings?

**Comment by grdminer** [comment]
+1
more information: https://tasmota.github.io/docs/Zigbee/
Especially the SetOption89 1 might be an option for structuring. Currently the adapter seems to ignore sub devices in tele topic using this option e.g. tele/%topic%/8F20/SENSOR. With SetOption89 0 they are resolved like sonoff.0.ZigbeeBridge.ZbReceived_0xABCD_Power, so all states for all sub devices are collected directly below bridge device.

**Comment by grdminer** [comment]
Seems to be related to #130

**Comment by anwa** [comment]
See also #141

**Comment by madc882** [comment]
Sorry for not following the issue. All states are flowing in correctly now! Thanks!

**Comment by anwa** [comment]
If everything works, please cloese the issue
