### ISSUE TITLE
No response with mosquitto_sub

### ISSUE THREAD

**Issue by moelski** [ioBroker/ioBroker.sonoff#134]
Hi !
I just want to show the messages from my tasmota devices. I tried using this: 
`mosquitto_sub -p 1884 -d -v -t \#`

or at another computer using this: 
`mosquitto_sub -h 192.168.30.22 -p 1884 -d -v -t "#"`

But the only response I got is something like this: 
Client mosqsub|16088-SHome-Dis sending CONNECT
Client mosqsub|16088-SHome-Dis received CONNACK (0)
Client mosqsub|16088-SHome-Dis sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0)
Client mosqsub|16088-SHome-Dis received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|16088-SHome-Dis sending PINGREQ
Client mosqsub|16088-SHome-Dis received PINGRESP
Client mosqsub|16088-SHome-Dis sending PINGREQ
Client mosqsub|16088-SHome-Dis received PINGRESP

Is it not possible to use normal MQTT clients like mosquitto_sub with the sonoff adapter? 

Dominik

**Comment by anwa** [comment]
No, its not possible. The Sonoff Adapter is for easy handling of tasmota devices.
If you want to use pure MQTT install ioBroker.MQTT Server and connect tasmota devices to this.
There you can do everything wat you want.
If you have further questions, you can just ask me.
@Apollon77 @moelski please close the Issue
