### ISSUE TITLE
MagicHome Tasmota

### ISSUE THREAD

**Issue by LukasVFL99** [ioBroker/ioBroker.sonoff#135]
I didn´t get any datapoints in my sonoff adapter in ioBroker. Any help would be appreciate.
I´m using the MagicHome LED Controller flashed with the newest software.

**Comment by MubiTec** [comment]
Hi, which version is newest FW? I flashed it with 8.4 and everything works fine.

**Comment by LukasVFL99** [comment]
@MubiTec I flashed 8.5.1

**Comment by anwa** [comment]
Did you switched the adapter to debug output and checked the logs?
If you still have problems, send the logs.
If not, please close the issue.

**Comment by anwa** [comment]
@Apollon77 please close the Issue
