### ISSUE TITLE
Add Buttonx

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.sonoff#138]
Hi, 

It would be great if you can add following topic:

stat/Devicexxx/BUTTONx = {"ACTION":"HOLD"}

Please let me know when I can help.

**Comment by anwa** [comment]
Can you give some more information (device/version/set options)
What is your usecase? Is it not shown at all, or just wrong?
Is there something in the logfile?

**Comment by MubiTec** [comment]
I use it with a sonoff mini, but it is defined for every button.
https://tasmota.github.io/docs/Buttons-and-Switches/
Chapter: Multi-Press Functions
You can use a button for more than one action.

**Comment by anwa** [comment]
Ok, i will try to set up a hardware for testing.

**Comment by anwa** [comment]
Ok, look at #143 there i explain how you can do it until the pull request is not accepted.
