### ISSUE TITLE
external MQTT Command

### ISSUE THREAD

**Issue by Schmello** [ioBroker/ioBroker.sonoff#139]
Hello everybody..
I use the Sonoff adapter in IOBroker.
I now have to send a simple Mqtt command from a stand alone Node Red that switches on the Tasmota socket. I can do that with a normal Mosquitto server. (cmnd / Tasmota_Pool / POWER1)
But it has to run through the Sonoff adapter.
Can someone help me with the command? Or is that not even possible?

**Comment by anwa** [comment]
You could do this with the MQTT Server Adapter and a smal script, to link the two Adapter

**Comment by anwa** [comment]
@Apollon77 @Schmello pleas close this Issue, it can not be implemented in Sonoff.
