### ISSUE TITLE
Sonoff Zigbee Bridge Objektbaum

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.sonoff#141]
Ist es möglich die einzelnen Geräte ID's in Subfolder zu packen? sonst hat man bei mehreren Geräten überhaupt keinen überblick mehr

![image](https://user-images.githubusercontent.com/25475385/102521941-dacb6680-4095-11eb-819f-f1f1c6aa64ae.png)

**Comment by duczz** [comment]
Gerade gesehen wurde bereits mal besprochen, gibts da nen stand?

https://github.com/ioBroker/ioBroker.sonoff/issues/130

**Comment by morphygee** [comment]
hilft nur bedingt.
Also bei geräten mit nur einem subdevice. Sowas, wie Switches. Temperatur-Sensoren haben ja mehrere Values (Temp, Druck, Feuchtigkeit) und hier kriegt man nur den Ersten Wert aus dem Geliefertnen JSON. Am Beispiel von dem Aqara Bewegungsmelder sieht man nur die Helligkeit, sonst nichts

**Comment by DanielG80** [comment]
wie schafft ihr das, dass bei euch linkquality und battery im Biobroker angezeigt werden? bei mir werden alle Daten auf der Tasmota WebUI angezeigt und laut console auch per mqtt an Biobroker gesendet. Jedoch wird im sonoff adapter nur die Luftfeuchtigkeit und die Temp angezeigt. MQT: tele/Zigbee-Bridge/SENSOR = {"ZbReceived":{"Sensor_Wohnzimmer":{"Device":"0x16A5","Name":"Sensor_Wohnzimmer","BatteryVoltage":3.01,"BatteryPercentage":100,"Temperature":24.13,"Humidity":40.74,"Endpoint":1,"LinkQuality":97}}}

**Comment by morphygee** [comment]
mach "SetOption89 0" dann hast du alles, nur halt nicht aufgeräumt (genau das wird ja bemängelt)

**Comment by DanielG80** [comment]
09:18:55 CMD: SetOption89
09:18:55 SRC: WebConsole from 192.168.21.24
09:18:55 CMD: Group 0, Index 89, Command "SETOPTION", Data ""
09:18:55 MQT: stat/Zigbee-Bridge/RESULT = {"SetOption89":"OFF"}

Das habe ich schon. :-(

**Comment by morphygee** [comment]
das passiert wenn du die Datenpunkte im iobroker löschst. 
das geht aber hier am Thema des Threads vorbei

**Comment by anwa** [comment]
Hallo, ich hab ein bischen gespielt:
![Screenshot_20210122_081949](https://user-images.githubusercontent.com/1856906/105459690-f88a7d80-5c8a-11eb-8196-e226f1a59174.png)
Noch nicht perfekt, aber ein Start.
![Screenshot_20210122_082425](https://user-images.githubusercontent.com/1856906/105459910-4d2df880-5c8b-11eb-8cbf-41f1b651f60d.png)
Hier ist die Struktur noch fehlerhaft.
2 Möglichkeiten:
1. Nur Unterstruktur wenn Gerät ist Bridge
2. Immer mit Unterstruktur (z.B. I2C devices)

Am besten am Ende in den Einstellung wählbar...

**Comment by anwa** [comment]
Ok, ich konnte das Problem lösen...
![Screenshot_20210122_092453](https://user-images.githubusercontent.com/1856906/105466367-68e9cc80-5c94-11eb-8161-5b232623a846.png)

**Comment by anwa** [comment]
So sieht ein Shelly dann aus:
![Screenshot_20210122_092654](https://user-images.githubusercontent.com/1856906/105466422-7d2dc980-5c94-11eb-8dde-273c875019a1.png)

**Comment by morphygee** [comment]
sieht gut aus.
bleibt nur noch abzuwarten, bis wir es installieren können. Produktiver einsatz ist gerade sehr erschwert

**Comment by anwa** [comment]
Die mutigen können ja über "Adapter aus beliebiger Quelle installieren oder aktualisieren" von `https://github.com/anwa/ioBroker.tasmota.git` direkt installieren.
Gibt einen neuen Adapter tasmota, dann nur noch einen anderen Port und ihr seid dabei.
Ich habe/hatte eigentlich nicht vor das weiter zu pflegen. Wäre toll wenn das z.B. bluefox übernehmen würde.
Ich habe auch noch rausgefunden warum bei Kombisensoren C statt % für die Feuchtigkeit erstellt wird. Vielleicht finde ich am WE eine Lösung.

**Comment by morphygee** [comment]
wichtig für den fork von @anwa ist die Einstellung "SetOption89 0"

**Comment by duczz** [comment]
@anwa Erstmal Vielen Dank für den Fork, endlich mal einer der sich der Sache annimmt, könntest du evtl. einen Pull request starten, dann könnte man es mit in den Originalen Adapter mit aufnehmen

**Comment by anwa** [comment]
@duczz ich will noch ein Fehler fixen und das Problem mit den falschen units bei Luftfeuchtigkeit #111 beheben.
Danach, wenn ich Zeit habe, werde ich mal versuchen mit bluefox kontakt aufzunehemen.
Ich habe leider von Java keine Ahnung. Ich bin mir natürlich auch nicht sicher, was für Probleme meine Änderungen bei anderen Geräten verursachen, die ich selber nicht benutze.
Leider scheint auf diesem Adapter kein großer Fokus mehr zu liegen, es gibt viele Issues die offen sind, und es gibt kaum Feedback. 
Mein Fork funktioniert für mich und wahrscheinlich viele andere auch, da ich einen neuen Adapter Namen gewählt habe, kann man ihn gut parallel einsetzen.
Aber wie gesagt, es müsste jemand mit Ahnung meine Änderungen in den Adapter übernehmen...

**Comment by duczz** [comment]
@anwa Mit dem Fokus hast du leider recht, vllt wirst du der neue Coder für den Adapter :-).
Hast du mehrere Änderungen gemacht oder bisher nur die SetOption89? Diese könnte man nach einem Pull Request im latest ja testen lassen. - Apollo würde den PR dann machen, hab bereits mit im geschrieben.

**Comment by anwa** [comment]
Ok, #111 habe ich eventuell gelöst. Beschreibung was ich gemacht habe, siehe #111

**Comment by anwa** [comment]
@duczz ich habe auch #110 gefixed, die Lösung hatte ich ja schon seit 20.12.2019 beschrieben, wurde leider bis heute nicht übernommen.

**Comment by duczz** [comment]
@anwa Vllt kannst du bei Zeit die wichtigen comments in dem Pull request definieren, würd es dem der das macht vermutlich einfacher machen, dann muss es sich nicht alle comments ansehen sondern sieht gleich welche die lösungscomments sind

**Comment by anwa** [comment]
Juhu, ich habe den letzten Fehler gefunden und behoben.

Es steht jetzt die Version 2.3.5 unter meinem Fork bereit.
Zum Testen bitte "Adapter aus beliebiger Quelle installieren oder aktualisieren" und von https://github.com/anwa/ioBroker.tasmota.git direkt installieren.

Folgendes habe ich gemacht:

- Fehler behoben #141 Sonoff Zigbee Bridge Objektbaum (SetOption89 0)
- Fehler behoben #130 Unterordner bei Zigbee2Tasmota Devices
- Fehler behoben #110 Add Counter1-4
- Fehler behoben #111 Wrong unit on humidity"
- Ergänzungen an der Datenpunkt Liste

Wäre schon wen das ein paar Leute Testen könnten, bevor ich das an die Entwickler weiter gebe...
Ich glaube, ihr könnt direkt in meinem Fork Issues erstellen, dann müssen wir hier nicht alles zu müllen!

Viel Spass

**Comment by anwa** [comment]
Gut, v2.4.0 ist raus!
Objektbaum ist nun Optional.
![Screenshot_20210125_120252](https://user-images.githubusercontent.com/1856906/105697776-490d0f80-5f05-11eb-860b-90d6c053857d.png)

**Comment by Namrenner** [comment]
Hello,
get error to install:
npm
 ERR! code E404
npm 
ERR! 404 Not Found - GET https://codeload.github.com/anwa/ioBroker.tasmota/legacy.tar.gz/masternpm ERR! 404 npm ERR! 404  'https://github.com/anwa/ioBroker.tasmota/tarball/master' is not in the npm registry.npm ERR! 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR! 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git url.
npm ERR!
 A complete log of this run can be found in:npm ERR!     C:\WINDOWS\ServiceProfiles\iobroker(SmartHome)\AppData\Roaming\npm-cache\_logs\2021-02-09T09_10_23_365Z-debug.log
ERROR: host.TV Cannot install https://github.com/anwa/ioBroker.tasmota/tarball/master: 1
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
what strange url you use there to install it? just use latest repo please

**Comment by anwa** [comment]
Hello @Namrenner we merged all the changes in the latest ioBroker.sonoff release. Please install v2.4.0 of the sonoff adapter.
