### ISSUE TITLE
MQT: Verbindung fehlgeschlagen aufgrund von 192.168......:1883, rc -2. Wiederversuch in 10 s

### ISSUE THREAD

**Issue by baeriwiliwonka** [ioBroker/ioBroker.sonoff#142]
Habe immer wieder Probleme mit dem sonoff Adapter in Verbindung mit einem sonoff basic mit Tasmota.
Mal läuft alles flüssig, dann wieder Verbindungsprobleme mit der Meldung:
MQT: Verbindung fehlgeschlagen aufgrund von 192.168.20.39:1883, rc -2. Wiederversuch in 10 s

Habe mehrere sonoffs laufen, die Probleme treten immer mal wieder bei verschiedenen Devices auf, können manchmal durch Resets oder durch Ändern des MQTT Passworts auf etwas ungültiges und wieder zurück auf das korrekte PW temporär gefixt werden.
Habe die Devices nun auch alle mal auf Tasmota 9.2.0 hochgezogen, gleiches Problem...

Kennt jemand diesen Effekt?
Kann ich evtl irgendwelche Daten zur Analyse liefern?

Danke!

**Comment by thorsten2209** [comment]
Hallo,
ich habe ein ähnliches Problem und bekomme aber **permanent** den Fehler "Connect failed .... rc -2".
Ich habe schon andere MQTT Ports am sonoff-adapter und in den beiden Sonoff Geräten "Mini-Switch" und "Touch T1" ausprobiert (1883, 1884, 1885, 1890, 2000)

Der Sonoff-Adapter steht auf "gelb". Der LOG gibt mir Info, dass Dienst gestartet wurde:
"Starting MQTT authenticated server on port 1885"

Dass MQTT bei beiden Sonoff-Geräten aktiv ist, sehe ich an den zyklischen RSL Infos in der Console:
**tele/TAS_Buero_T1/STATE = {"Time":"2021-01-05T20:38:10","Uptime":"0T00:35:04","UptimeSec":2104,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0, ... **

Meine nächsten Tests werden mit einem MQTT tool sein, wo ich dann manuell Daten an den sonoff.adapter und an meinen Mini-Switch und Touch-T1 senden werde.

Mir ist noch nicht klar, ob der MQTT-User und -Passwort optional oder mandatory ist.

Infos zur Infrastruktur:
- Sonoff Mini-Switch mit Firmware Tasmota-Lite 9.2.0
- Sonoff Touch-T1 EU mit Firmware Tasmota 9.2.0
- ioBroker v4.1.11
- sonoff.adapter: v2.3.3
- Raspberry PI 3b+ mit 16GB SDCard (erste Versuche sind auf einer anderen SD-Card mit 32GB)

Ich werkel da jetzt schon seit vielen, vielen Stunden rum und verzweifle gerade. Ich bin für jeden Tipp dankbar :-)

**Comment by anwa** [comment]
Hi, ich habe mehrere Sonoff's, mehr als zehn Shellys, Steckdosen und viele Wemos D1 und auch ESP32 Wemos. Sogar zwei Sonoff ZBbridges habe ich am laufen. Aber diese Probleme kenne ich nicht.
Ich vermute bei euch Netzwerk (WLAN) Probleme:

- Wie sind die Geräte eingebaut (Abschirmung?)
- Gibt es ander Geräte die auf 2.4 GHz senden? Viele Fernbedienungen nutzen auch diese Frequenzen
- Wie ist die Auslastung eurer 2.4 GHz Kanäle (Nachbarn?) Eventuell mal Kanal wechseln

Leider gibt es viele Möglichkeiten was bei WLAN so schief laufen kann...
Auch wenn das MQTT-User und -Passwort optional ist, sollte man es nutzen!

Gruß
Andreas

**Comment by anwa** [comment]
Ist das Problem behoben/gefunden?
Bitte kurze Rückmeldung und fals erledigt, bite schließen.

**Comment by thorsten2209** [comment]
Das Problem ist nach wie vor vorhanden.
Über die Weboberfläche der Sonoffs kann ich ohne Probleme die Config ändern und die Geräte an- und ausschalten. Deshalb sehe ich keine Schwierigkeiten an meinem WLAN.

Ich habe aber dennoch verschiedene Kanäle im 2.4 GHz Bereich versucht und auch ein komplett eigenes Netzwerk aufgebaut, so dass keine Störungen von außen rein kommen sollten.

Einzig das Interface zwischen den beiden Sonoffs und dem ioBroker schlägt fehl, weil diese nicht erkannt werden (mit obigem Fehler und Code). 
Ich habe auch schon mehrfach mein System neu aufgesetzt. Mein Equipment hab ich oben aufgelistet.

**Comment by mat-sche** [comment]
> Das Problem ist nach wie vor vorhanden. Über die Weboberfläche der Sonoffs kann ich ohne Probleme die Config ändern und die Geräte an- und ausschalten. Deshalb sehe ich keine Schwierigkeiten an meinem WLAN.
> 
> Ich habe aber dennoch verschiedene Kanäle im 2.4 GHz Bereich versucht und auch ein komplett eigenes Netzwerk aufgebaut, so dass keine Störungen von außen rein kommen sollten.
> 
> Einzig das Interface zwischen den beiden Sonoffs und dem ioBroker schlägt fehl, weil diese nicht erkannt werden (mit obigem Fehler und Code). Ich habe auch schon mehrfach mein System neu aufgesetzt. Mein Equipment hab ich oben aufgelistet.
> 
> Ach ja: Die Geräte sind nicht eingebaut und in sichtbarer Reichweite ( <5m ). Ich bin für jeden weiteren Tipp dankbar :-)

Hallo Thorsten,

hast Du inzwischen eine Lösung zu dem Problem gefunden?
Ich nutze den ioBroker auf einem WIN10 Rechner und habe ebenfalls die Probleme mit dem rc-2 Meldungen in der Tasmota-Konsole. Die ioBroker Installation ist mit:
    js-controller: 4.0.23
    Node.jsv16.15.1
    NPM v8.11.0

Mit einer WIN7 Installation habe ich keine Verbindungsprobleme Tasmota <=> ioBroker.
Kannst DU etwas neues berichten?

**Comment by thorsten2209** [comment]
Hallo @mat-sche 
aktuell liegt das Projekt auf Eis und ich bastel gerade mit ESPs herum...

Das Problem habe ich nach meinem Post nicht weiter verfolgt und würde mich in wenigen Wochen wieder neu einlesen und nach anderen Lösungen suchen.
Win7 ist keine Option 😉

Grüße,
Thorsten

**Comment by mat-sche** [comment]
> Das Problem habe ich nach meinem Post nicht weiter verfolgt und würde mich in wenigen Wochen wieder neu einlesen und nach anderen Lösungen suchen.

Oki, na da bin ich mal gespannt.
Ich bin der Meinung, dass es irgend wie mit dem Sonoff Adapter und er ioBroker Installation zu tuen hat, da es ja auf einer älteren Version ja funst.
> Win7 ist keine Option 😉
Jup so ist es....

**Comment by chivas03** [comment]
Hallo,
mittlerweile habe ich auch seit ca. 2 Monaten selbiges Problem und komme auch auf keine gute Lösung. Resete ich die Tasmota-Devices, so funktioniert die Verbindung für ein paar Minuten, aber es kommt dann wieder das gleiche Problem.
Seid ihr da weiter gekommen mit dem Problem?

**Comment by thorsten2209** [comment]
Hi chivas,
ich bin zeitlich noch nicht wieder dazu gekommen. Aber es wird wieder aktueller denn je :-)
Auf jeden Fall liegen meine Tasmotas und Sonoffs schon in Reichweite und ich versuche mich gerade wieder mit der Materie (ioBroker, MQTT, ...) vertraut zu machen.

**Comment by mat-sche** [comment]
Guten Morgen,

ich hatte dann als letzten Schritt die aktuellste Version vom ioBroker für Windows 10 installiert und habe dann Zugriff auf einen Tasmota-Device gehabt. Leider habe ich jetzt noch nicht viel damit gemacht, um sagen zu können, ob die Installation stable ist...
Schau mal hier:
https://forum.iobroker.net/topic/63164/sonoff-adapter-ohne-funktion-win-10/11
 Grüße!

**Comment by TheRealCookie** [comment]
Hey Leute,
ich habe das gleiche Problem wie ihr.
Da ich auch ein tw. komisches Verhalten im WLAN generell habe (Notebook hat ein ganz schlechtes VPN zum Büro; mit Kabel gehts), vermute ich ein Problem mit der Fritzbox 7590ax. Ich dachte ja eigentlich, dass die bissel besser performt, aber irgendwie spinnt die glaube ich. 
Habt ihr noch irgendwas neues?

**Comment by ZeroQool007** [comment]
Ich hatte das gleiche Problem, aber soweit ich das beurteilen kann seit ich einige Adapter, sowie Admin aktualisiert habe.  Den MQTT Adapter habe ich aber NICHT aktualisiert. 

Das einzige was geholfen hat, dass ich im MQTT Adapter noch einmal die Passwörter eingegeben habe.
