### ISSUE TITLE
Switch1_Action

### ISSUE THREAD

**Issue by mczeus** [ioBroker/ioBroker.sonoff#143]
habe einen Shelly mit Tasmota geflashed auf die Version 9.2.0.
Es gibt ja die Option "setoption114 1" mit der man den angschlossenen Taster von dem Relay trennen kann. Funktioniert auch.
Der "Switch1_Action" DP wird erstellt, bekommt aber keine Änderungen mit.
Der DP bleibt immer leer!

**Comment by mczeus** [comment]
Man müsste in der datapoints.js
`
Action:        {type: 'number',  role: 'value',                    read: true, write: true},
In
Action:        {type: 'string',  role: 'value',                    read: true, write: true},
`
ändern!

**Comment by anwa** [comment]
Wer es sofort braucht, in /opt/iobroker/node_modules/iobroker.tasmota/lib/datapoints.js wie oben beschrieben ändern und anschließend den Adapter neu hochladen...
![Screenshot_20210128_140020](https://user-images.githubusercontent.com/1856906/106142053-49a9de00-6171-11eb-9bdf-340f354f062a.png)
Den Pfeil nach oben klicken.
