### ISSUE TITLE
Bestimmte Daten fehlen im Sonoff Adapter aber in der Tasmota WebUI sind sie vorhanden

### ISSUE THREAD

**Issue by DanielG80** [ioBroker/ioBroker.sonoff#144]
Wie oben beschrieben, wenn ich in die Tasmota WebUI gehe von meiner Sonoff Zigbee Bridge dann sehe ich alle Daten der einzelnen Geräte.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/68602252/104437734-736ade80-558f-11eb-9ebf-5618d1ffa704.png">

Im ioBroker fehlen mir allerdings einige Geräte komplett und bei einigen fehlen nur ein paar Daten wie z.B. die Linkquality.
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/68602252/104438103-e6745500-558f-11eb-9ba3-5a28d323ed2b.png">

setoption89 ist schon auf 0

In der Console von Tasmota sehe ich auch das die MQTT befehle raus gehen:
11:06:59 MQT: tele/Zigbee-Bridge/SENSOR = {"ZbReceived":{"Sensor_Schlafzimmer":{"Device":"0xB237","Name":"Sensor_Schlafzimmer","BatteryVoltage":3,"BatteryPercentage":100,"Temperature":23.73,"Humidity":39.21,"Endpoint":1,"LinkQuality":115}}}

oder sehe ich da was falsch??

Hier ein paar Einstellungen:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/68602252/104438688-91850e80-5590-11eb-80cd-402c58f8c2c5.png">
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/68602252/104438877-ca24e800-5590-11eb-8f32-7bfc01f200a5.png">

**Comment by DanielG80** [comment]
ouch. ich befürchte ich habe das Problem schon gefunden.
Automatische Erstellung von Zuständen sollte man auch aktivieren

**Comment by duczz** [comment]
@DanielG80 Bitte schließ das Issue wenn es nun passt
