### ISSUE TITLE
JS-Controller 3.2.x Error

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.sonoff#145]
Adapter Version 2.3.3
seit dem Controller Upgrade kommt folgendes bei einem Iobroker stop
`

sonoff.0 | 2021-01-16 20:36:12.942 | error | (13924) Cannot read property 'setState' of null
-- | -- | -- | --
sonoff.0 | 2021-01-16 20:36:12.942 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonoff.0 | 2021-01-16 20:36:12.942 | error | at runMicrotasks (<anonymous>)
sonoff.0 | 2021-01-16 20:36:12.942 | error | at Adapter.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6307:35)
sonoff.0 | 2021-01-16 20:36:12.942 | error | (13924) TypeError: Cannot read property 'setState' of null
sonoff.0 | 2021-01-16 20:36:12.933 | error | (13924) unhandled promise rejection: Cannot read property 'setState' of null
sonoff.0 | 2021-01-16 20:36:12.933 | error | (13924) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

**Comment by Apollon77** [comment]
This seems to be happening when the adapter ends, so is seems to be that setState calls happen after unload was called

**Comment by Apollon77** [comment]
fixed in 3.2.12 controller and with update here later
