### ISSUE TITLE
MQTT Client Mode

### ISSUE THREAD

**Issue by Befrish** [ioBroker/ioBroker.sonoff#146]
In order to use an external MQTT server I want set up as a MQTT client, which published and subscribes (like MQTT  Adapter).

How can I do this?

**Comment by anwa** [comment]
This is not possible.
The Adapter has its own MQTT Server, there is no need for an external Server.

Why would you do this? It make just no sense for me at the moment because this would be a big issue with subscribtions...

**Comment by Befrish** [comment]
I have to use an external MQTT Server in order to distribute the load (one server for each - MQTT and ioBroker) and to have a more reliable MQTT Server for the IoT devices. If ioBroker (in Raspberry Pi in my case) does not work, the MQTT devices can still connect to the MQTT Server and e.g. I can switch the light.

**Comment by anwa** [comment]
Ok, thats fine.
But than you dont need this adapter, just use the MQTT Server you want and install the MQTT Server/Client as Client in ioBroker to publisch/subscribe to your topics.
Why you want to use the Sonoff Adapter? The use ist to simplify the MQTT handling, what you want is already done by the MQTT Adapter.

**Comment by anwa** [comment]
@Befrish please close the Issue, because this can not be implemented.
If you have to use an external MQTT Server, than simply setup Tasmota to use this Server.
Than, if you need data in ioBroker, install MQTT Client and subscribe to the topics you need. Simple as that.
