### ISSUE TITLE
[Feature request] BEM280 Druck

### ISSUE THREAD

**Issue by Tingeltangelbobi** [ioBroker/ioBroker.sonoff#15]
Version: Sonoff-Tasmota 5.10.0g
Geräte Tpy: 18 WeMos D1 mini
 
Konsole(DS18B20, BME280):
`19:28:30 MQT: tele/sonoff-nodemcu/SENSOR = {"Zeit":"2018.01.03 19:28:30","DS18B20":{"Temperatur":21.4},"BME280":{"Temperatur":23.1,"Feuchtigkeit":37.0,"Druck":990.1},"TempUnit":"C"}`

Konsole(DHT22, BME280):
`19:39:40 MQT: tele/sonoff-test/SENSOR = {"Zeit":"2018.01.03 19:39:40","SI7021":{"Temperatur":7.3,"Feuchtigkeit":82.1},"BME280":{"Temperatur":8.0,"Feuchtigkeit":78.6,"Druck":991.3},"TempUnit":"C"}`

**Comment by Tingeltangelbobi** [comment]
Mit der englischen Tasmota firmware wird der Druck angezeigt.
Dann fehlt nur die Änderung für die deutsche Übersetzung.

Hier noch mal die Ausgabe der en Firmware(DHT22, BME280):
`06:55:26 MQT: tele/sonoff-test/SENSOR = {"Time":"2018-01-04T06:55:26","SI7021":{"Temperature":7.5,"Humidity":81.5},"BME280":{"Temperature":8.2,"Humidity":76.7,"Pressure":993.2},"TempUnit":"C"}`

**Comment by GermanBluefox** [comment]
Please test with 1.0.1
