### ISSUE TITLE
POWERn up to n=25

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.sonoff#152]
I have a wemos with mcp23017 portexpamder and now I have really more than 8 relais. 
It still did it locally but could you please add power up to n=25?

POWERn:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true}

Thanks a lot!

**Comment by anwa** [comment]
Hi,
how are your settings at "Auto creation of states"?
For me its not a smart solution to just add POWER states up to 25 in datapoints.js
Next week somebody needs 40 :)
So your POWERn line would be nice.
I will try to fix this, but i need time...

**Comment by MubiTec** [comment]
Hi,

The setting are true at my installation. 
OK, no problem if there is a smarter solution :-)

**Comment by anwa** [comment]
If you need a quick solution, you could do the following:

Open /opt/iobroker/node_modules/iobroker.sonoff/lib/datapoints.js in you prefered editor and copy/past all the missing POWER9-25 in. Then on admin page goto Adapter and upload the Sonoff adapter:
![Screenshot_20210128_140020](https://user-images.githubusercontent.com/1856906/106171030-65bd7780-6191-11eb-92e3-62b3a3825154.png)
Click on the arrow up icon.
Then restart the Adapter.
I will figure out a better solution, but it will take sometime. There are still 5 pull request open, i don't know how long it will take...

**Comment by anwa** [comment]
Ok, i found a smarter solution :)
Will see, how long it will take to accept this pull request :)

**Comment by MubiTec** [comment]
> Ok, i found a smarter solution :)
> Will see, how long it will take to accept this pull request :)

Thank you. If I should test it please let me know

**Comment by anwa** [comment]
Sorry, it wasn' that easy, I found a bug. Will check on the weekend...
