### ISSUE TITLE
Baumstruktur

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.sonoff#158]
@Apollon77 @anwa Bei der Baumstruktur ist ein kleiner Fehler drinnen.

Dort hat sich ein Leerzeichen eingeschlichen (Vor Wohnzimmer)
`sonoff.0.MQTT-Sonoff-ZbBridge_05DF17.SENSOR.ZbReceived. Wohnzimmer.Temperature`

**Comment by Apollon77** [comment]
Ok dann warte ich noch kurz

**Comment by anwa** [comment]
Ich habe das Problem nicht, kann es sein das du das Leerzeichen in Tasmota drin hast?
Aber eigentlich werden diese Zeichen raus gelöscht... Hmm, ich schau mir das morgen noch mal an.

Bei mir sieht das so aus:
tasmota.0.HG_EG_ZB_Bridge.SENSOR.HG_EG_Kueche.Temperature

**Comment by duczz** [comment]
Du hast Recht, das war mein Fehler in Tasmota.
Ich hab beim renamen ein Leerzeichen nach das Komma gesetzt, muss aber zusammen geschrieben werden `ZbName 0x128F, Vibration_sensor`
