### ISSUE TITLE
Relais

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.sonoff#159]
@anwa  Bei der aktiven Baumstruktur gibt es noch einen Bug.
Ich habe einen Wemos mit Tasmota und einigen Relais dran, wenn ich nun eins schalten wird der Power (gelb) oben (blau) nochmal angelegt und geschalten

![image](https://user-images.githubusercontent.com/25475385/106364950-a1dc0e00-6332-11eb-9897-b99ad56b8179.png)
![image](https://user-images.githubusercontent.com/25475385/106364953-a99bb280-6332-11eb-87a2-849310542e38.png)

**Comment by anwa** [comment]
Die Komandos werden direkt am Gerät angelegt (die blauen), normalerweise beim start des Gerätes.
Also wenn du von ioBroker schalten willst mußt du die blauen setzen. Unter STATUS bekommst du dann die Rückmeldung.
RESULT ist eigentlich nicht notwendig, da sind z.B. auch die SetOptions drin wenn du die in der Konsole eingigst.
So ist es zumindest bei meinen 1 und 2 Kanaligen Shellys.
Ich bin aber selber noch nicht so sicher ob mir das gefällt, vielleicht sollte man noch einen Ordner CMND anlegen?
Wir können aber gerne weiter diskutieren wie du das am besten findest...

**Comment by duczz** [comment]
Achso okay, dann eher ein Denkfehler meinerseits, dann wären wir aber irgendwie wieder bei dem Punkt mit dem erstellen der Automatischen zu stände.
Meines erachtens dürfte ich die states nicht sehen, da nicht angehakt

![image](https://user-images.githubusercontent.com/25475385/106378409-dc7e8e80-63a4-11eb-8ce6-d4823251dd9e.png)

**Comment by anwa** [comment]
Wie in der README.md steht, ist das Verhalten so gewünscht:

Auto-creation of objects
In the web config you can determine which MQTT telegrams create the new objects not in default datapoints

Da die 'POWER1-8' Datenpunkte in datapoints drin stehen, werden sie natürlich angelegt.
Diese Optionen sind wirklich verwirrend, da jeder meint die entsprechenden Datenpunkte z.B. unter RESULT würden dann gar nicht angelegt. Aber es handelt sich nur um neue noch unbekannte... Würde ja für TELE und SENSOR keinen Sinn machen, die alle nicht mehr zu übernehemen. Bei RESULT aber eher schon...

**Comment by anwa** [comment]
Möglicherweise könnte man da eine etwas flexiblere Lösung suchen... Eventuell eine Blacklist in der Admin Oberfläche.
Das könnte gehen, allerdings müsste er dann bei jedem Datenpunkt prüfen ob er in der Blacklist steht. Das könnte sich negativ auf die Performance auswirken.
Für Ideen und Vorschläge bin ich offen.

**Comment by duczz** [comment]
Evtl. check ich da auch nur was nicht. Aber wieso hab ich seit deinem Adapter 2mal Power drin?

Alter Adapter states:
![image](https://user-images.githubusercontent.com/25475385/106392748-97357d80-63f3-11eb-9207-25396a51a3ff.png)

Neuer Adapter States:
![image](https://user-images.githubusercontent.com/25475385/106392761-a3213f80-63f3-11eb-8070-ce0ef6ce28e5.png)

**Comment by anwa** [comment]
POWER ist ein 'state' **und** ein 'cmnd':
```
MQT: cmnd/HG_OG_Büro_Licht/POWER = 
MQT: stat/HG_OG_Büro_Licht/RESULT = {"POWER":"OFF"}
MQT: stat/HG_OG_Büro_Licht/POWER = OFF
```
Bei flacher Hirachie ist das natürlich nur einmal (R/W) vorhanden, wenn aber ein Objektbaum erstellt wird, landet ein POWER in STATE und der andere wird im Root des Gerätes angelegt. Siehe 1. Zeile oben.
Ich bin am überlegen ob man diese in einen Ordner CMND anlegen soll...

**Comment by duczz** [comment]
aahh, okay jetzt check ich's - sorry :)
Der CMND Ordner macht dann durchaus sinn. Wobei ich an dem Gedanken festhalten das die States nur da sein sollten wenn ich Sie im Adapter auch anhake, sonst kann man diese dort auch komplett entfernen oder?

**Comment by anwa** [comment]
Wie ich oben bereits geschrieben habe werden nur unbekannte Datenpunkte angelegt oder eben nicht wenn der Haken gesetzt ist.

**Comment by duczz** [comment]
Sprich wenn man die Power1-X in der datapoint.js pflegen würde dann würden diese nicht mehr mit angezeigt werden? (Wäre für Relais ja richtig)
![image](https://user-images.githubusercontent.com/25475385/106438160-664a5c80-6476-11eb-9e68-8db98cd5dea0.png)

Okay, dann sind dies also keine Fehler und @Apollon77 könnte es ins latest schieben

**Comment by anwa** [comment]
Wenn du die POWER1-x aus datapoints.js löscht und der haken bei state aus ist, dann bekommst du gar keine datenpunkte mit POWER

Ich benötige die um festzustellen ob das Licht z.B. an ist:
sonoff.0.HG_OG_Büro_Licht.STATE.POWER
