### ISSUE TITLE
MagicHome Support

### ISSUE THREAD

**Issue by ChrSch84** [ioBroker/ioBroker.sonoff#16]
Hello is it Possible to ADD the MagicHome Support with the Tasmota Firmware.

Would be nice if you could ghet the "Color" Command and the "Dimmer" Command. (all other Commands would be a BONUS)

Thank you.

**Comment by Alveran81** [comment]
Yes please. There are many people who want this.

**Comment by ihavenonick** [comment]
Ich auch
