### ISSUE TITLE
Detached Switch SO114 -> State is empty

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.sonoff#161]
**Describe the bug**  
When detaching a Switch from its Relay with SetOption114 a datapoint "Switchx_Action" (x=number of the switch) is created under the objects.
But there is no state displayed.
When using this datapoint to trigger a script the state can be read out as null. 

**To Reproduce**  
Wemos D1 mini with Tasmota 9.2.0

**Expected behavior**  
The datapoint should change to true for short period of time when Switch is pressed.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v2.3.3
 - JS-Controller version: v3.1.6
 - Node version: v10.20.1
 - Operating system: Ubuntu v19.04

![so114](https://user-images.githubusercontent.com/32200998/107882563-53aa3b80-6eea-11eb-8a48-5111651c188f.PNG)

**Comment by anwa** [comment]
Hi,
did you try:
SetOption59 1
Send tele/%topic%/STATE in addition to stat/%topic%/RESULT for commands: State, Power and any command causing a light to be turned on.
0 = disable (default)
1 = enable
otherwise the status is only send on teleperiod!

**Comment by baennjer** [comment]
Same behaviour with SO73 1 (Detach Buttons from Relay)
Datapoint Button1_Action is being created but empty. Need to asign the role button to it. 
Can be triggereg but reads Null.
Seems the sonoff adapter not yet fully compatible with detaching buttons and switches.

**Comment by anwa** [comment]
The adapter is compatible with everything coming from Tasmota via MQTT. And as long you have checkt the three boxes for SENSOR/STATE/RESULT you also see everything as datapoints.
Of course nobody can know whats coming up in tasmota so there are unknown datapoitnts, getting default settings in ioBroker.
You can add this datapoints by your own in you system: `/opt/iobroker/node_modules/iobroker.sonoff/lib/datapoints.js`
And if it works for you, create a change request here (or tell me)
I don't have this Button_Actions here, but maybe i will make a setup to test. Sounds important to work on (Switch/Button)...

**Comment by anwa** [comment]
You should also read https://tasmota.github.io/docs/Buttons-and-Switches/#buttontopic
Not all tasmota settings are sending MQTT messages on button/switch actions

**Comment by anwa** [comment]
Bei mir sieht das so aus (Button1):
![Screenshot_20210216_091250](https://user-images.githubusercontent.com/1856906/108035451-3cc52f80-7037-11eb-9e48-38689f71746f.png)
But button or switch are physical inputs at the wemos. How can you override a physical switch? You get the information switch on/off button pressed/single/double... but you can not write them of course!
You can only control relays/outputs or if you create cmd/datapoints in rules/scrips in tasmota

**Comment by baennjer** [comment]
anwa: I didnt want to overwrite their states because as u mentioned it should report the status of a physical switch/button.
I only noticed that the value of the state in sonoff.0. is empty. Both with switch and button. 
For testing I connected the Wemos with mosqitto broker and there it only publishes the switch/button action in the "stat/TOPIC/RESULT" topic. Means it doesnt have a separate topic for each button/switch nor does it have objects for each within the JSON. So I have not yet tested what happens when more than one switch is pressed....
Anyways when I trigger this sonoff.0.datapoints in javascript it works.
Btw that screen shot of your datapoints what adapter is that?

**Comment by anwa** [comment]
ioBroker.sonoff v2.4

**Comment by anwa** [comment]
I'm testing at the moment, and everything works as expected.
There is of course a big difference in tasmota behaving depending on SwitchMode's
So check just the console in tasmota to see whats get send to ioBroker

**Comment by anwa** [comment]
But yes, not everything possible in Tasmota may be handled well in the adapter.
For example custom topics (Switch/Button/Rules) are not working at the moment.
In that cases, its better to use the standard MQTT server adapter in ioBroker. That the totaly flexible solution for experts.
ioBroker.sonoff is for easy setup for tasmota devices, but less powerfull.

**Comment by baennjer** [comment]
The Sonoff Adapter works great for me.
Just wanted to get rid of the allways needed GPIO pair (Switch-Relay) by detaching switch from relay to have some extra GPIOs.
So with new set option 114 switches are detached but in MQTT the state of the switch is not published, instead only "Toggle" is published with every state change.
I see Sonoff adapter is net guilty for this behaviour in its datapoints as no valid values are transmitted from Tasmota
.

**Comment by anwa** [comment]
You may need `SwitchMode 1`
Check the doku for SwitchMode 1-15
Please let me now if this works for you, otherwise i can go deeper into the problem to solve it.

**Comment by baennjer** [comment]
I have the following settings now: SO114 on, SwitchMode 2.
In Mosqitto I get ON when input connected to GND and OFF when open:
![image](https://user-images.githubusercontent.com/32200998/108055594-7a828200-7050-11eb-892f-75ed412d59b6.png)
But in Sonoff.0. the value stayes at NULL
![image](https://user-images.githubusercontent.com/32200998/108055819-c6352b80-7050-11eb-91c2-74be51cd30e7.png)

**Comment by baennjer** [comment]
Ich hab auf meinem Test System den Sonoff Adapter V2.4 installiert und nun bekomme ich "ON" und "OFF".
Mit V2.3.3 ging das nicht.

**Comment by anwa** [comment]
Ok, seltsam. Ich kann mich nicht erinnern das ich daran was geändert habe. Möglicherweise ein Seiteneffekt da ich Status und Cmnd trenne.

**Comment by baennjer** [comment]
Ich habe auf dem ProduktivSystem V2.3.3 laufen - funktioniert nicht.
Test System V2.3.3 - funktioniert nicht.
Test System Update über Github Link auf V2.4 - FUNKTIONIERT.

**Comment by anwa** [comment]
Wie geschrieben, wenn du bei 2.4 die Baumstruktur aktivierst, musst du deine Settings und Scripte anpassen/erneuern.
Wenn alles passt für 2.4 kannst du den Issue ja schließen.
Ich werde mir das aber auf jedenfall noch genauer ansehen das alle Switch und Button Stati sauber rein kommen.

**Comment by baennjer** [comment]
Hab die Baumstruktur mal getestet auf dem Testsystem.
Ist mir aber auf dem Produktivsystem jetzt zuviel Aufwand alles weitere anzupassen.
