### ISSUE TITLE
Sonoff POW mit Tasmota 9.1.0 kein Energy Total

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.sonoff#168]
Im Sonoff Adapter (2.4.0) wird beim Sonoff POW (nicht POW R2) der Energy TOTAL Wert nicht mehr empfangen. Auf dem Webinterface wird dieser aber ausgegeben und auch in der Konsole angezeigt.

![image](https://user-images.githubusercontent.com/44617472/109492013-9c392b80-7a8a-11eb-8567-fa63d58a91d2.png)

![image](https://user-images.githubusercontent.com/44617472/109492114-c25ecb80-7a8a-11eb-88b1-d2e23630f56f.png)

![image](https://user-images.githubusercontent.com/44617472/109492185-dc98a980-7a8a-11eb-8651-3ebc873fa174.png)

**Comment by JBSullivan** [comment]
Nachtrag: Ich hab den Energy Total DP jetzt gelöscht, Sonoff Instanz gestoppt und wieder neu gestartet. Der DP wurde nun wieder angelegt und dieses Mal auch mit Werten gefüllt. Also jetzt ist alles OK.

**Comment by anwa** [comment]
Danke für das Feedback. Bitte das Issue schließen wenn fertig.
