### ISSUE TITLE
Shutter level not writable. Crashes Tasmota if written.

### ISSUE THREAD

**Issue by Kaldesh84** [ioBroker/ioBroker.sonoff#169]
**Describe the bug**  
When using a Sonoff device (in my case Sonoff T1 EU 2 channel) in Shutter mode, a state SHUTTER1 is created in ioBroker, that reads the position correctly.
The state is set to be not writeable which defeats the purpose of setting shutters to a certain level.
If the state is made writeable manually, changing the value will crash Tasmota on the device and force it to restart.
Device is running current Tasmota 9.3.1 but according to the Tasmota Devs and a certain issue on their GitHub, this already happens since at least 7.0.3 [arendst/Tasmota/issues/7808] (Link to the issue)

The problem seems to be that the data for the shutter is now JSON encoded into {"ShutterPositionX":Y} with X being the number of the shutter and Y being a value between 0 and 100.

Could you please include this change and make the related state writeable again?

**To Reproduce**  
1. Setup a Sonoff device with Tasmota in ShutterMode, connect the device with the Sonoff adapter to ioBroker
2. Locate state sonoff.0.CLIENT.SHUTTER1, verify that state is not writeabe
3. Reconfigure state to be writeable, change value and verify that device briefly crashes
4. Set the value in Tasmota's web UI manually and verify the JSON format in the console. 

**Expected behavior**  
The adapter should provide a writeable state for the shutter level that sends the correct MQTT command to Tasmota without crashing it.

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 3.1.4
 - Node version: <12.18.0
 - Operating system: Raspbian

**Comment by anwa** [comment]
What are your settings (ShutterMode) in Tasmota?
I only have a TV Lift, 2 Relais (Up/Down)
`08:01:45.757 MQT: stat/HG_OG_Schlafzimmer_TVLift/RESULT = {"Shutter1":{"Position":90,"Direction":1,"Target":100}}`
This is what i get for up...
