### ISSUE TITLE
Add possibility to send command to tasmota via MQTT 

### ISSUE THREAD

**Issue by mk176** [ioBroker/ioBroker.sonoff#171]
**Is your feature request related to a problem? Please describe.**
I would like to send command to tasmota via MQTT like "DeepSleepTimer 0". Therfore it is neccacery to use the MQTT topic /cmnd/TASMOTANAME/DeepsleepTime 0
This is currently not possible

**Describe the solution you'd like**
I would like to be able to also pubilsh cmnd

**Describe alternatives you've considered**
i could use an origanal MQTT Broker, but then the nice parsind of the topics in json has to be done manually
**Additional context**

**Comment by mk176** [comment]
I found a solution. One must just create a stat in the Device with the value. This is then send to cmnd of the Tasmota Device

**Comment by MBadberg** [comment]
Hey. i would like to pm you, but this is not possible on github :D

So, how did you manage to send mqtt commands to devices?
I can't get it to work.

cmnd/friendly_name/POWER Toggle for example is funtioning on the console on the tasmota device itself, but not from anywhere else.

The app would like to have this format:
`"name": "Back Light",
      "setTopic": "lights/hue/00:17:88:01:02:3c:49:f8-0b/set/on",
      "getTopic": "lights/hue/00:17:88:01:02:3c:49:f8-0b/get/on",
      "onValue": "true",
      "offValue": "false"`
      
But i don't get it, how this should look like with my tasmota devices?

Maybe you got an idea?
