### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.sonoff#175]
![image](https://user-images.githubusercontent.com/19333515/116661210-633b0b80-a994-11eb-9d38-e24161e0e2c3.png)
4320 warnings in 30 minutes from 4 devices!
![image](https://user-images.githubusercontent.com/19333515/116669052-663af980-a99e-11eb-98e3-e4955b0f128e.png)

**Comment by kueppert** [comment]
und von mir auch ein paar Meldungen in Textform:

sonoff.0 | 2021-04-30 10:20:14.372 | warn | (16311) State value to set for "sonoff.0.Sonoff-SP1-Küche Boiler.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:12.186 | warn | (16311) State value to set for "sonoff.0.Gosung-SP111-2.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:10.276 | warn | (16311) State value to set for "sonoff.0.Sonoff-SP1-3-Wohnwand.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:08.056 | warn | (16311) State value to set for "sonoff.0.Sonoff-S20-3-Serverschrank.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:06.198 | warn | (16311) State value to set for "sonoff.0.Sonoff-SP1-Server.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:05.579 | warn | (16311) State value to set for "sonoff.0.Sonoff-SP1-Buero.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 10:20:05.132 | warn | (16311) State value to set for "sonoff.0.Gosund-SP111-1.Wifi_Channel" has wrong type "number" but has to be "array"

**Comment by cracyfloyd** [comment]
Same here.
endless warnings.
example:

2021-04-30 10:22:13.369 - warn: sonoff.0 (9243) State value to set for "sonoff.0.Sonoff_LHC-103_Flur_oben.Wifi_Channel" has wrong type "number" but has to be "array"
2021-04-30 10:22:16.127 - warn: sonoff.0 (9243) State value to set for "sonoff.0.Rollade-Esszimmer.Wifi_Channel" has wrong type "number" but has to be "array"
2021-04-30 10:22:22.799 - warn: sonoff.0 (9243) State value to set for "sonoff.0.Gosound-Steckdose-Waschmaschine.Wifi_Channel" has wrong type "number" but has to be "array"

**Comment by MarkSau** [comment]
same at my installation


sonoff.0 | 2021-04-30 12:43:51.812 | warn | State value to set for "sonoff.0.Steckdose01.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
-- | -- | -- | --
sonoff.0 | 2021-04-30 12:43:51.763 | warn | State value to set for "sonoff.0.Steckdose01.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 12:43:51.748 | warn | State value to set for "sonoff.0.Steckdose01.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 12:43:51.702 | warn | State value to set for "sonoff.0.Steckdose01.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 12:43:51.697 | warn | State value to set for "sonoff.0.Steckdose01.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 12:43:51.604 | warn | State value to set for "sonoff.0.Steckdose01.SleepMode" has wrong type "string" but has to be "number"

**Comment by OlfrygtACAB** [comment]
bei mir läuft auch alles voll


sonoff.0 | 2021-04-30 18:40:00.535 | warn | (11112) State value to set for "sonoff.0.3D_Drucker.Command" has wrong type "string" but has to be "number"
-- | -- | -- | --
sonoff.0 | 2021-04-30 18:40:00.175 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.167 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.DS18B20-2_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.157 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.DS18B20-1_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.102 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.086 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 18:40:00.082 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.077 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:40:00.012 | warn | (11112) State value to set for "sonoff.0.HKV_OG_Temperatur.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.979 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.964 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.DS18B20_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.953 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.931 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.Wifi_Channel" has wrong type "number" but has to be "array"
sonoff.0 | 2021-04-30 18:39:59.923 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.871 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:59.794 | warn | (11112) State value to set for "sonoff.0.Teich-Technik.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:57.579 | warn | (11112) State value to set for "sonoff.0.3D_Drucker.Command" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:57.544 | warn | (11112) State value to set for "sonoff.0.3D_Drucker.Command" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:55.512 | warn | (11112) State value to set for "sonoff.0.BarschAquarium.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:55.501 | warn | (11112) State value to set for "sonoff.0.BarschAquarium.DS18B20_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:55.444 | warn | (11112) State value to set for "sonoff.0.BarschAquarium.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 18:39:55.426 | warn | (11112) State value to set for "sonoff.0.BarschAquarium.Wifi_Channel" has wrong type "number" but has to be "array"

**Comment by msiemers** [comment]
Hier auch. Warnungen ohne Ende.

**Comment by spezialtyp** [comment]
device-reminder.0 | 2021-05-01 00:02:50.173 | warn | (2048) State value to set for "device-reminder.0.Spülmaschine.live consumption" has wrong type "string" but has to be "number"
device-reminder.0 | 2021-05-01 00:02:50.172 | warn | (2048) State value to set for "device-reminder.0.Waschmaschine.live consumption" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:47.192 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:47.079 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:47.065 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:47.039 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 00:02:47.033 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.985 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.953 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_Waschmaschine.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.880 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.823 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 00:02:46.775 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.768 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.694 | warn | (1762) State value to set for "sonoff.0.Frank-Smart-Wetterstation.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 00:02:46.583 | warn | (1762) State value to set for "sonoff.0.Frank_Smart_FireTV.ENERGY_TotalStartTime" has wrong type "string" but has to be "number

**Comment by msiemers** [comment]
@Apollon77 




sonoff.0 | 2021-05-01 08:02:06.841 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:06.791 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:06.735 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:02:06.733 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:06.731 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:06.672 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Küche.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:05.224 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:05.178 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:05.174 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:02:05.171 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:05.169 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:05.115 | warn | (2378780) State value to set for "sonoff.0.Waschmaschine.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.340 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.334 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:02:04.330 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.328 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.322 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.096 | warn | (2378780) State value to set for "sonoff.0.Büro 2.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.094 | warn | (2378780) State value to set for "sonoff.0.Büro 2.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.089 | warn | (2378780) State value to set for "sonoff.0.Büro 2.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:02:04.087 | warn | (2378780) State value to set for "sonoff.0.Büro 2.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.045 | warn | (2378780) State value to set for "sonoff.0.Büro 2.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:04.038 | warn | (2378780) State value to set for "sonoff.0.Büro 2.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.419 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.411 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.365 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.361 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:02:00.359 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.358 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:02:00.351 | warn | (2378780) State value to set for "sonoff.0.Solvis Heizung.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.926 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.916 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.911 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:01:54.867 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.865 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.858 | warn | (2378780) State value to set for "sonoff.0.Kühlschrank Keller.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.426 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.420 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:01:54.419 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.357 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:54.351 | warn | (2378780) State value to set for "sonoff.0.Stromzaehler.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:53.248 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:53.246 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:53.242 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-05-01 08:01:53.240 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:53.238 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:53.232 | warn | (2378780) State value to set for "sonoff.0.Geschirrspülmaschine.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:52.878 | warn | (2378780) State value to set for "sonoff.0.Lena Kugel.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-05-01 08:01:52.873 | warn

**Comment by m0rph2k** [comment]
Selbe diverse --> has wrong type "string" but has to be "number" Fehler betrifft aber auch andere adapter wie mqtt

**Comment by FoRealx** [comment]
same here.

**Comment by nifu777** [comment]
Same here:

`(21263) State value to set for "sonoff.0.DVES_C6C767.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_301B3F.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_531521.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_B5CB99.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_348616.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_2A6877.Wifi_Channel" has to be stringified but received type "number"
(21263) State value to set for "sonoff.0.DVES_7A9F59.Wifi_Channel" has to be stringified but received type "number"`

**Comment by arteck** [comment]
![image](https://user-images.githubusercontent.com/6681528/118783515-6f2d3580-b88f-11eb-8bcb-3a3cfa4e7239.png)

**Comment by GermanBluefox** [comment]
Kann jemand die JSON Pakete besorgen für die falsch geschriebene States?
Beispiel: 
```
'{"Time":"2017-10-02T19:26:06", "Uptime":0, "Vcc":3.226, "POWER1":"OFF", "POWER2":"OFF", "POWER3":"OFF", "POWER4":"OFF", "Wifi":{"AP":1, "SSId":"AAA", "RSSI": 15}}',  expect: {Vcc: 3.226, Wifi_RSSI: 15, Time: '2017-10-02T19:26:06'}
```

**Comment by kueppert** [comment]
State value to set for "sonoff.0.Sonoff-S20-3-Serverschrank.Wifi_Channel" has to be stringified but received type "number"
ich vermute:
15:10:21 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-2005","IPAddress":"192.168.178.59","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"5C:CF:7F:7F:E7:D5","Webserver":2,"WifiConfig":5,"WifiPower":17.0}}

Ich habe nur noch bei allen Sonoff-Geräten diesen WIFI-Fehler, alle anderen Fehler sind weg...

**Comment by GermanBluefox** [comment]
Please test 2.4.1
