### ISSUE TITLE
Frage neue Datenpunkte für z.B. Version

### ISSUE THREAD

**Issue by klauswroe** [ioBroker/ioBroker.sonoff#176]
Ich habe heute auf Tasmota auf 9.4 upgedatet und es passen die Datenpunkte des sonoff - Adapters nicht mehr.
Bsp.: Bis jetzt stand im iobroker unter "sonoffgerät".INFO.Version die Version die man gerade bei den Geräten installiert hat.
Jetzt steht die Version unter "sonoffgerät".INFO. Info1_Version und der "alte" Datenpunkt "Version" wird nicht mehr upgedatet!

Dies bedeutet, dass ich in der derzeitigen Konstellation folgende Objekteinträge habe:
"sonoffgerät".INFO.Version = 9.3.1(tasmota)
"sonoffgerät".INFO. Info1_Version = 9.4.0(tasmota)

Daher meine Frage: Wird der Datenpunkt Version usw. nicht mehr upgedatet? I

Kurz zusammengefasst meine Daten:
a) kein Amazon Adapter
b) Adapter Version Nr. 2.4.0
c) iobroker über raspberry pi 4.0
d) Node Version: v12.22.1

Danke
![screen_tasmota](https://user-images.githubusercontent.com/83469381/116732136-f737c200-a9ea-11eb-9e66-f6dc34e29341.jpg)

**Comment by Apollon77** [comment]
Kann es sein das Tasmota 9.4.0 hier dinge geändert hat?
Bitte Debug Log posten

**Comment by klauswroe** [comment]
Hallo,
Anbei das Log.
Was habe ich getan - damit man es vielleicht findet:
- Adapter auf debug und gestoppt
- Ein Sonoff Gerät in iobroker gelöscht: sonoff.0.SonOffS20_2
- Sonoffgerät neustart
- Sonoff Adapter gestartet
- Ab 2021-05-01 19:22:56.678  legt er das neue Gerät an
- Wie du unter 2021-05-01 19:22:56.786 ersehen kannst, legt er ein INFO.Info1_Version an
- interessant: Er legt das "alte" Version unter INFO gar nicht mehr an!
- 
[sonofflog.txt](https://github.com/ioBroker/ioBroker.sonoff/files/6410039/sonofflog.txt)

Danke für die Hilfe

**Comment by klauswroe** [comment]
Anbei noch der Screenshot der neu angelegten Objekte in iobroker
![sonoff](https://user-images.githubusercontent.com/83469381/116790441-67f6e100-aab4-11eb-9958-6cbb614911a0.jpg)

**Comment by duczz** [comment]
Das passt schon alles. Die OIDs haben sich in unter Infos aufgeteilt

![image](https://user-images.githubusercontent.com/25475385/116804760-ba221b80-ab21-11eb-941e-d8c5cbdd80f9.png)
![image](https://user-images.githubusercontent.com/25475385/116804766-c4dcb080-ab21-11eb-986e-abde08592506.png)

**Comment by klauswroe** [comment]
Alles klar - Danke vielmals!

**Comment by Apollon77** [comment]
Also ist der einzige Effekt das die alten States da bleiben und nicht gelöscht werden ... Dann kann man die manuell löschen
