### ISSUE TITLE
H801 some Datapoints are not writable

### ISSUE THREAD

**Issue by xCruziX** [ioBroker/ioBroker.sonoff#179]
**Describe the bug**  
If a new device will be created, some datapoints for example "Scheme" and "Speed" are not writable.

**To Reproduce**  
Add a new h801 device to the adapter

**Expected behavior**  
The datapoints should be writable

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: Ubuntu 18 or 20

**Comment by Apollon77** [comment]
Plese post debug log

**Comment by xCruziX** [comment]
Sry, I forgot.
[logbroker.txt](https://github.com/ioBroker/ioBroker.sonoff/files/6409951/logbroker.txt)

**Comment by duczz** [comment]
Passiert hier noch was?
Ich glaub ich hab ein ähnliches Problem mit fehlenden stats https://github.com/ioBroker/ioBroker.sonoff/issues/187

**Comment by GermanBluefox** [comment]
Please test 2.4.1
