### ISSUE TITLE
IoBroker Fhem auf einem Docker System....

### ISSUE THREAD

**Issue by hotwebnet** [ioBroker/ioBroker.sonoff#18]
Hallo ,
ich habe heute Fhem und ioBroker auf meinem Server in Docker installiert. DIe Umgebung läuft auch bis jetzt sehr gut.....
Nun ist das Problem , das ich den Sonoff Adapter in ioBroker installiert bekomme, aber keine Verbindung habe, das Problem hatte ich auch als ich ioBroker und FHEM einfach so ohne Docker auf dem Server installiert hatte. Das Problem tritt aber nicht auf, wenn ioBroker alleine installiert ist.........

Danke, ist das ein MQTT Problem ???

**Comment by Apollon77** [comment]
Hm ... Glaskugel ist mir leider heute runtergefallen ...

Gibts irgendwelche Logs die was sagen? Fehler? Adapter mal mit Debug Output gestartet?
Bei Docker ist das Netzwerk so konfiguriert das Du "nach draussen" ins Netz kommst wo Du hin willst? ...

Ein paar mehr Infos sollten es schon sein bitte. Vor allem bei Docker-Installationen gibt es vieles was erstmal n der Docker-Konfig und damit bei Dir liegen kann. Die Adapter tun grundsätzlich bei vielen anderen Usersn ... also muss man den Unterschied finden.

In meinen Augen am besten erstmal im Forum fragen, vllt hat ein User da auch sonoff auf Docker laufen ...

**Comment by GermanBluefox** [comment]
Hochwahrscheinlich es ist wegen multicasts. Suche bitte im Inet wie man
multicast Pakete im Docker behandelt

22 янв. 2018 г. 0:11 пользователь "Ingo Fischer" <notifications@github.com>
написал:
