### ISSUE TITLE
converting String to Bool

### ISSUE THREAD

**Issue by marco1995** [ioBroker/ioBroker.sonoff#180]
If it is a boolean representing String the condition will always send a "On" signal.
Maybe it will be better to convert a boolean representing value like (1/0 "true"/"false") or set a warn message if the value isn't a boolean value.

https://github.com/ioBroker/ioBroker.sonoff/blob/a89f3be162d99668d2232e99165dc22cc0c22a68/lib/server.js#L617

**Comment by GermanBluefox** [comment]
Why are you writing 'OFF' instead of 'false'?
This is command from ioBroker side and you may not write anything except true/false

**Comment by Apollon77** [comment]
exactly
