### ISSUE TITLE
VEML6075 Datapoints

### ISSUE THREAD

**Issue by unsermanninchina** [ioBroker/ioBroker.sonoff#185]
**Describe the bug**  
As far as I understand should mqtt messages ariving at the sonoff adapter be able to make datapoints in iobroker. I have this mqtt message coming from an ESP8266 with Tasmota installed:
`
MQT: tele/Hof/Lager/Tasmota/Relais/RFresv/Beleuchtung/UV/Beleuchtungsstaerke/Außenlampe/SENSOR = {"Time":"2021-05-28T14:30:44","BH1750":{"Illuminance":27550},"VEML6075":{"UvaIntensity":1710,"UvbIntensity":890,"UvIndex":2.4}}`

I got a datapoint for UvIndex: 
sonoff.0.Hof Lager.VEML6075_UvIndex

Missing are the points for UvaIntensity and UvbIntensity.

I have data points from a formerly used VEML6050. I don't know if this might influence the creation:
sonoff.0.Hof Lager.VEML6070_UvIndex
sonoff.0.Hof Lager.VEML6070_UvIndexText
sonoff.0.Hof Lager.VEML6070_UvLevel
sonoff.0.Hof Lager.VEML6070_UvPower

The data point BH1750 is old and still there.

1. restart iobroker - no change
2. restart the RPi2 - no change

**Expected behavior**  
The data points should all be established

**Screenshots & Logfiles**  
![iobroker](https://user-images.githubusercontent.com/324880/119941407-2548fb80-bfc3-11eb-8447-96ae01a28b4b.png)

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 3.2.16
 - Node version: v12.20.0
 - Operating system: Raspian

**Comment by GermanBluefox** [comment]
Please test 2.4.1

**Comment by unsermanninchina** [comment]
I tested 2.4.1 and 2.4.3 without success. For the test with 2.4.3 I renamed the mqtt object in Tasmota and the adapter found it immedeatly - but without the UVA and UVB data, which is included in the mqtt message (08:11:43.400 MQT: tele/Hof/Lager/Tasmota/Relais/RFresv/Beleuchtung/UV/Beleuchtungsstaerke/Außenlampe/SENSOR = {"Time":"2021-07-19T08:11:43","BH1750":{"Illuminance":7006},"VEML6075":{"UvaIntensity":728,"UvbIntensity":444,"UvIndex":1.1}}). 
![Objekt_Tasmota_Hof_Lager@2 4 1](https://user-images.githubusercontent.com/324880/126086815-7c934267-8abf-4afa-ba1f-8851ed6781a4.png).
Please see attached screenshots of the admin/objects interface.

Both times after installing I restarted the Pi 2B running iobroker.
Any idea whats the problem?

Thank you!
![Objekt_Tasmota_Hof_Lager2@2 4 3](https://user-images.githubusercontent.com/324880/126086812-2358242c-d0ff-4e05-91cc-f217d52ecc75.png)

**Comment by GermanBluefox** [comment]
please try 2.4.4

**Comment by unsermanninchina** [comment]
2.4.4 work's for me. Thank you very much!

![Screenshot_2 4 4](https://user-images.githubusercontent.com/324880/126268870-d8484a36-14d6-43eb-b83b-012309b7d885.png)
