### ISSUE TITLE
ESPCAM32 mit tasmota keine mqtt verbindung

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.sonoff#194]
habe versucht mqtt für den esp32cam zu aktivieren - bekomme aber rc -4 fehler - kann das am sonoff adapter liegen ?

siehe forum: https://forum.iobroker.net/post/652924

**Comment by GermanBluefox** [comment]
>@ralla66 die mqtt settings stimmen schon - die anderen 20 geräte sind ja im adapter sichtbar


Wenn deine 20 andere Geräte verbunden sind, kann es am Adapter liegen?
Man muss wireshark starten und da den Trafik beobachten.
