### ISSUE TITLE
V 2.4.2 Einige Werte werden nicht mehr geparsed

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.sonoff#195]
Hallo,
ich habe mehrere Shelly 1PM´s auf denen Tamota V9.5.0 läuft.
Habe den Sonoff-Adapter heute auf V 2.4.2 gezogen (vorher alle alten Sonoff-Objekte gelöscht), dabei ist mir aufgefallen, das einige Werte nicht mehr angezeigt bzw. geparsed werden.
Das Objekt DeviceName hatte vorher den Namen des Shellys als Wert z.B. Waschmaschine, etc. jetzt steht da als Wert (null).
Genauso ist es mit dem Objekt TempUnit oder Command, bei beiden steht als Wert (null) drin.

Unter Objektdaten steht unter common bei allen nicht funktionierenden Objekten  als Typ --> number, müsste das nicht string sein?

Hier die Objektdaten von DeviceName:
![image](https://user-images.githubusercontent.com/35137293/126060241-ad6d6aeb-629e-42b8-afa9-253e89b6506d.png)

Und hier von Command:
![image](https://user-images.githubusercontent.com/35137293/126060264-b1f7df02-a69c-49f7-b601-f89144b348e6.png)

Gruß Steffen

**Comment by GermanBluefox** [comment]
Wenn du Historie anschaust: https://github.com/ioBroker/ioBroker.sonoff/commits/master, dann ist es klar, dass an Parsing wurde nichts getan. Nur neue Datenpunkten angelegt und einige Statetypen geändert.

D.h. dieser Fehler war immer da.

**Comment by Steff42** [comment]
@GermanBluefox ,
hmm... komisch...
Ich hatte vor der 2.4.2 die Version 2.4.0 drauf - schon längere Zeit und da wurde der Wert von DeviceName übertragen.
Bin gerade unterwegs, ich werde später einmal downgraden und schauen was dann mit den Werten passiert.
Gruß Steffen

**Comment by GermanBluefox** [comment]
Es wird heute 2.4.3 mit besser Behandlung von unbekannten States gemacht. Bitte ausprobieren. Ich denke in 5 min wird die bei npm sein und spätestens morgen in Beta-Repo

**Comment by Steff42** [comment]
@GermanBluefox ,
so ging doch schneller als gedacht.
Bin wieder zurück auf der 2.4.0, du hast Recht, die Objektdaten sehen in der 2.4.0 identisch aus:
Hier wieder das Objekt zu DeviceName - gleich wie oben.
![image](https://user-images.githubusercontent.com/35137293/126065726-ca6caeed-f0de-4231-b2da-210bb9b99992.png)

Aber - mit der 2.4.0 wird unter Wert wieder der richtige DeviceName angezeigt.
![image](https://user-images.githubusercontent.com/35137293/126065792-2179db00-1ad5-4c50-afba-a4efe3fa3e14.png)

Hier nochmal zum Vergleich die Ansicht unter 2.4.2 - der Wert unter DeviceName ist wieder (null)
![image](https://user-images.githubusercontent.com/35137293/126065935-3703c937-c5af-4227-ae99-753168ae50f8.png)

**Comment by Steff42** [comment]
> Es wird heute 2.4.3 mit besser Behandlung von unbekannten States gemacht. Bitte ausprobieren. Ich denke in 5 min wird die bei npm sein und spätestens morgen in Beta-Repo

OK, werde ich später testen - Danke

**Comment by Steff42** [comment]
Funktioniert mit der 2.4.3 nun ohne Probleme!

Danke
