### ISSUE TITLE
Regelmäßiger Fehler

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.sonoff#197]
Ich habe seit dem letzten Update auf V 2.4.4 Regelmäßig mehrmals täglich einen Fehler im Log stehen:

`
<html>
<body>

host.ioBroker | 2021-07-21 05:30:01.317 | error | instance system.adapter.sonoff.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2021-07-21 05:30:01.316 | error | Caught by controller[0]: at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.ioBroker | 2021-07-21 05:30:01.316 | error | Caught by controller[0]: at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.ioBroker | 2021-07-21 05:30:01.315 | error | Caught by controller[0]: at Connection.Duplexify._write (/opt/iobroker/node_modules/duplexify/index.js:208:22)
host.ioBroker | 2021-07-21 05:30:01.315 | error | Caught by controller[0]: at Writable.write (_stream_writable.js:318:11)
host.ioBroker | 2021-07-21 05:30:01.314 | error | Caught by controller[0]: at writeOrBuffer (_stream_writable.js:387:5)
host.ioBroker | 2021-07-21 05:30:01.313 | error | Caught by controller[0]: at doWrite (_stream_writable.js:403:12)
host.ioBroker | 2021-07-21 05:30:01.313 | error | Caught by controller[0]: at Writable.write [as _write] (/opt/iobroker/node_modules/mqtt-connection/lib/writeToStream.js:13:9)
host.ioBroker | 2021-07-21 05:30:01.312 | error | Caught by controller[0]: at generate (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:34:14)
host.ioBroker | 2021-07-21 05:30:01.312 | error | Caught by controller[0]: at publish (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:334:51)
host.ioBroker | 2021-07-21 05:30:01.311 | error | Caught by controller[0]: at Function.byteLength (buffer.js:725:11)
host.ioBroker | 2021-07-21 05:30:01.287 | error | Caught by controller[0]: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1)
sonoff.0 | 2021-07-21 05:30:00.737 | error | Exception-Code: ERR_INVALID_ARG_TYPE: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1)
sonoff.0 | 2021-07-21 05:30:00.736 | error | TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1) at Function.byteLength (buffer.js:725:11) at publish (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:334:51) at generate (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:34:14) at Writable.write [as _write] (/opt/iobroker/node_modules/mqtt-connection/lib/writeToStream.js:13:9) at doWrite (_stream_writable.js:403:12) at writeOrBuffer (_stream_writable.js:387:5) at Writable.write (_stream_writable.js:318:11) at Connection.Duplexify._write (/opt/iobroker/node_modules/duplexify/index.js:208:22) at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)

</body>
</html>`

**Comment by Apollon77** [comment]
Can yopu please enable debug logging for the instalce (Admin - instances - expert mode - loglevel) and let it run until the error happens again. Then post the log with some minutes before the error

**Comment by Chaot1** [comment]
Almost 24 hours on 2.4.5 and no more errors.
provisionally closed

**Comment by Chaot1** [comment]
Ich habe das Problem das scheinbar der Adapter auf Debug keinen Fehler macht. Sobald ich auf Info gehe kommt nach einger Zeit der Fehler:
`
<html>
<body>


sonoff.0 | 2021-07-28 14:00:33.506 | info | Client [Cam1] connected with secret 1627473633493_9557
-- | -- | -- | --
sonoff.0 | 2021-07-28 14:00:33.453 | info | Starting MQTT authenticated server on port 1500
sonoff.0 | 2021-07-28 14:00:33.389 | info | starting. Version 2.4.5 in /opt/iobroker/node_modules/iobroker.sonoff, node: v12.22.2, js-controller: 3.3.15
host.ioBroker | 2021-07-28 14:00:01.019 | error | instance system.adapter.sonoff.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2021-07-28 14:00:01.018 | error | Caught by controller[0]: at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.ioBroker | 2021-07-28 14:00:01.015 | error | Caught by controller[0]: at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.ioBroker | 2021-07-28 14:00:01.015 | error | Caught by controller[0]: at Connection.Duplexify._write (/opt/iobroker/node_modules/duplexify/index.js:208:22)
host.ioBroker | 2021-07-28 14:00:01.015 | error | Caught by controller[0]: at Writable.write (_stream_writable.js:318:11)
host.ioBroker | 2021-07-28 14:00:01.014 | error | Caught by controller[0]: at writeOrBuffer (_stream_writable.js:387:5)
host.ioBroker | 2021-07-28 14:00:01.014 | error | Caught by controller[0]: at doWrite (_stream_writable.js:403:12)
host.ioBroker | 2021-07-28 14:00:01.013 | error | Caught by controller[0]: at Writable.write [as _write] (/opt/iobroker/node_modules/mqtt-connection/lib/writeToStream.js:13:9)
host.ioBroker | 2021-07-28 14:00:01.013 | error | Caught by controller[0]: at generate (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:34:14)
host.ioBroker | 2021-07-28 14:00:01.009 | error | Caught by controller[0]: at publish (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:334:51)
host.ioBroker | 2021-07-28 14:00:01.009 | error | Caught by controller[0]: at Function.byteLength (buffer.js:725:11)
host.ioBroker | 2021-07-28 14:00:00.997 | error | Caught by controller[0]: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1)
sonoff.0 | 2021-07-28 14:00:00.233 | error | Exception-Code: ERR_INVALID_ARG_TYPE: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1)
sonoff.0 | 2021-07-28 14:00:00.227 | error | TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1) at Function.byteLength (buffer.js:725:11) at publish (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:334:51) at generate (/opt/iobroker/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:34:14) at Writable.write [as _write] (/opt/iobroker/node_modules/mqtt-connection/lib/writeToStream.js:13:9) at doWrite (_stream_writable.js:403:12) at writeOrBuffer (_stream_writable.js:387:5) at Writable.write (_stream_writable.js:318:11) at Connection.Duplexify._write (/opt/iobroker/node_modules/duplexify/index.js:208:22) at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
sonoff.0 | 2021-07-28 14:00:00.226 | error | uncaught exception: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (1)
sonoff.0 | 2021-07-28 13:26:39.195 | info | Client [RFID] connected with secret 1627471599194_2536
sonoff.0 | 2021-07-28 13:26:34.836 | info | Client [RFID] connection closed: closed
sonoff.0 | 2021-07-28 11:52:14.070 | info | Client [RFID] connected with secret 1627465934069_8372
sonoff.0 | 2021-07-28 11:52:09.734 | info | Client [RFID] connection closed: closed


</body>
</html>`

Wie gesagt läuft der Adapter auf debug tagelang durch.

**Comment by Apollon77** [comment]
Abe rohne Debug kommen wir dem Thea nicht auf die Spur und an sich geht es bei debug nur um ein paar mehr log ausgaben ... der Code ist der gleiche der ausgeführt wird. Also vllt passierts nur ein paar mal oder es ist ein ganz böses "Timing" issue was aber auch komisch wäre

**Comment by Chaot1** [comment]
Das kann ich ja verstehen. Ich habe den Adapter 4 Tage auf debug laufen gehabt. Sobald ich dann auf Info zurückgegangen bin war der Fehler wieder da. Seltsamerweise aber immer exakt zu den selben Zeiten, also 5:30 Uhr, 14:00 Uhr und 17:00 Uhr.
Ich werde den nochmals auf debug laufen lassen.
Der Fehler scheint aber auch nichts auszumachen. Es scheint alles zu funktionieren.

**Comment by Chaot1** [comment]
Fehler ist weg. Datenpunkt "Restart" auf Button und Zahl geändert

**Comment by Apollon77** [comment]
Was hast Du geändert???

**Comment by Chaot1** [comment]
Den Datenpunkt sonoff.0.RFID.Restart habe ich in den Eigenschaften auf role:Button und Type:string geändert.
`{
  "_id": "sonoff.0.RFID.Restart",
  "common": {
    "type": "string",
    "role": "button",
    "read": true,
    "write": true,
    "name": "RFID  Restart"
  },
  "native": {},
  "type": "state",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.sonoff.0",
  "user": "system.user.admin",
  "ts": 1627482386525
}`

**Comment by Apollon77** [comment]
Naja ... hacky ... ein button ist per definition ein boolean und kein String :-)

**Comment by Chaot1** [comment]
Ich denke mal das das "nur" am role:Button gelegen hat. Das war ja ursprünglich irgendwas anderes.
Da das scheinbar sowieso keiner benutzt ist das auch nicht wichtig.
Bei mir ist es so, dass der RFID Empfänger sich immer wieder mal aufhängt und ich den deshalb dreimal täglich neu starte.
