### ISSUE TITLE
Type of "Uptime" datapoint is wrong in new version 2.4.5

### ISSUE THREAD

**Issue by baennjer** [ioBroker/ioBroker.sonoff#202]
In new adapter version 2.4.5 the datapoint "Uptime" is of type number.
Thus the content can't be displayed correctly as it is of format "day hours minutes seconds" e.g. 57T20:42:02.
With this type it can only display the days but not the full string.

In previous version 2.4.0 the datapoint was of type string and it was able to display the content correctly.

When I change the type of "Uptime" in /opt/iobroker/node_modules/iobroker.sonoff/lib/datapoints.js to string and restart the instance it displayes correctly.

**Comment by Apollon77** [comment]
next verison
