### ISSUE TITLE
Suport for I2C Sensore BH1750 Beleuchtungsintensität please

### ISSUE THREAD

**Issue by Ichda** [ioBroker/ioBroker.sonoff#21]
Hello team,
please add the support for the I2C Sensor BH1750 Light sensor Illuminance.
I use the following settings on Sonof Basic:
GPIO14 = DHT11 --> Works and shows in IOBroker
GPIO01= 05 I2C SCL
GPIO03 = 06 I2C SDA
GPIO04 = 00 NONE
The Console of the Sonoff Basic sad: 
10:48:26 MQT: tele/sonoffbasic05/SENSOR = {"Time":"2018.02.10 10:48:26","DHT11":{"Temperature":14.0,"Humidity":24.0},"BH1750":{"Illuminance":777},"TempUnit":"C"}
10:53:26 MQT: tele/sonoffbasic05/SENSOR = {"Time":"2018.02.10 10:53:26","DHT11":{"Temperature":14.0,"Humidity":24.0},"BH1750":{"Illuminance":860},"TempUnit":"C"}

Many Thanks for your support!

**Comment by Apollon77** [comment]
Please try v1.0.2 from Github. Shoud be incuded there, Please verify

**Comment by Ichda** [comment]
Hello
yes it works. Many thanks
