### ISSUE TITLE
Send any command to the device.

### ISSUE THREAD

**Issue by avdlex** [ioBroker/ioBroker.sonoff#216]
For myself, I see it as follows. We add a state to the device by type:
{
  "_id": "sonoff.0.anydevice.cmd",
  "common": {
    "type": "string",
    "role": "value",
    "read": true,
    "write": true,
    "name": "anydevice command"
}
And when the value of this state is changed to the device, it is sent as a simple command.

This solves a lot of problems. The firmware is constantly evolving, the number of sensors and functions is changing. I understand that it is difficult to monitor the state of the firmware and add new options regularly.

Заранее спасибо. :-)

**Comment by Apollon77** [comment]
Can you provide a PR?
