### ISSUE TITLE
Rename Adapter to ioBroker.tasmota

### ISSUE THREAD

**Issue by jwiesel** [ioBroker/ioBroker.sonoff#228]
**Is your feature request related to a problem? Please describe.**
I didn't realize at first, that there is an ioBroker adapter for Tasmota devices. My assumption was, that the Sonoff adapter would be for sonoff devices running on the stock firmware of Sonoff.
If I understand it correctly the purpose of this adapter is to connect devices running on the "Tasmota" firmware.
Initially the Tasmota firmware was designed for devices manufatured by Sonoff. In the early days the project was still called "Sonoff-Tasmota". As the firmware is compatible to various ESP based devices, that has changed. Sonoff-Tasmota got renamed to "Tasmota" as today >90% of devices running on Tasmota are not coming from Sonoff, but from other vendors. 

*Therefore other users might face the same situation building a custom MQTT solution to integrate their non-Sonoff tasmota devices in ioBroker instead of using this adapter.*

**Describe the solution you'd like**
Rename the adapter to "ioBroker.tasmota", or to ease transition for existing users to "ioBroker.sonoffTasmota". 

**Additional context**
If we give the adapter a new name it might look more official. We could even approach the Tasmota project to integrate the adapter into the Tasmota docs as "ioBroker Integration" as well.
So far the Tasmota documentation only contains a link to an issue, but no hint, that this adapter could be used: https://tasmota.github.io/docs/Integrations/

**Comment by Apollon77** [comment]
I'm against a rename, but a rerwrite in a clean new adapter and then deprecate this one. see also my words in https://github.com/ioBroker/ioBroker.sonoff/issues/69#issuecomment-983569175

**Comment by jwiesel** [comment]
I just had a look at the iobroker.sonoff code and realized how much special handling there is for various kinds of data formats.

Tasmota offers MQTT Auto-discovery: https://tasmota.github.io/docs/Commands/#setoption19
* Either its own structure or
* the one of HomeAssistant (which produces quite some MQTT messages, but contains a lot of details.)
* Unfortunately no homie support has been implemented so far.

Maybe auto-discovery combined with and MQTT client and some logic to create & sync objects would be an approach. If we go that road (autodiscovery) it would rather be an "mqtt-discovery" adapter instead of a specific one for Tasmota - which wouldn't be a bad thing :-)
