### ISSUE TITLE
Please add topic for NSPanel

### ISSUE THREAD

**Issue by Tobi4** [ioBroker/ioBroker.sonoff#235]
Can you please add the topic /tele/DeviceNAME/RESULT for de display of the new NSPanel?

**Comment by Ichda** [comment]
Hello
I have the same part for "/tele/DeviceNAME/RESULT". But I have an other defice.
I got a SerialReceived value:

`15:21:31.419 MQT: tele/SINO_ENERGIE02/STATE = {"Time":"2022-01-04T15:21:31","Uptime":"0T01:10:09","UptimeSec":4209,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":12,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ichsmarthome","BSSId":"B2:BE:76:59:BF:92","Channel":3,"Mode":"11n","RSSI":88,"Signal":-56,"LinkCount":1,"Downtime":"0T00:00:03"}}
15:21:37.408 RUL: RULES#TIMER=1 performs "backlog SerialSend5 fe010f080000001c; RuleTimer1 10"
15:21:37.450 MQT: stat/SINO_ENERGIE02/RESULT = {"SerialSend":"Done"}
15:21:37.660 MQT: stat/SINO_ENERGIE02/RESULT = {"T1":10,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
15:21:37.677 MQT: tele/SINO_ENERGIE02/RESULT = {"SerialReceived":"FE0108020000002323000000000000005000000000000000000000000000000010000083"}
15:21:48.382 RUL: RULES#TIMER=1 performs "backlog SerialSend5 fe010f080000001c; RuleTimer1 10"
15:21:48.422 MQT: stat/SINO_ENERGIE02/RESULT = {"SerialSend":"Done"}
15:21:48.631 MQT: stat/SINO_ENERGIE02/RESULT = {"T1":10,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
15:21:48.648 MQT: **tele/SINO_ENERGIE02/RESULT** = {"SerialReceived":"FE0108020000002123000000000000005000000000000000000000000000000010000085"}
15:21:59.413 RUL: RULES#TIMER=1 performs "backlog SerialSend5 fe010f080000001c; RuleTimer1 10"
15:21:59.456 MQT: stat/SINO_ENERGIE02/RESULT = {"SerialSend":"Done"}`

Many thanks for your greate work!

Best regards
ichda

**Comment by hene42** [comment]
Hello, please add NSPanel.

THANK YOU.

**Comment by DocGame69** [comment]
Ich habe auch 2 hier liegen. Die Relais funktionieren ja wundervoll. Genial wäre natürlich wenn man an die Werte der Widgets rankommen würde, Irgendwie habe ich das mit dem Parsen der json im per Mqtt-Adapter nicht so richtig drauf,
Wäre da was machbar? dann könnte ich die Dinger endlich verbauen...

**Comment by Apollon77** [comment]
try new version
