### ISSUE TITLE
Tasmota 9.5.0 Shelly 2.5 ShutterPosition not writable

### ISSUE THREAD

**Issue by mzander** [ioBroker/ioBroker.sonoff#236]
Hi all,

I cam currently using Tasmota 9.5.0 with Shelly 2.5 to control my blinds via iobroker / mqtt.
I am wondering why SHUTTER1 is not writable.
The field represents the current position of the blind and should be set via mqtt.

Any help with this?

Thanks,
Moritz

**Comment by scripthase** [comment]
I have exactly the same problem.
And when I set the data point to writable, then Tasmota crashes on my ESP.
