### ISSUE TITLE
sonoff macht keine Objektupdates bei cmnd

### ISSUE THREAD

**Issue by joe-average-user** [ioBroker/ioBroker.sonoff#24]
Alles hier erklaert (inkl. Fix):

http://forum.iobroker.net/viewtopic.php?f=20&t=12152&p=128350#p128350

**Comment by Apollon77** [comment]
Wenn Fix schon drin: Kannst Du einen PR stellen? Oder zwischenzeitlich schon erledigt?

**Comment by Apollon77** [comment]
Laut Forum gefixt
