### ISSUE TITLE
Bitte Support für internen ADC hinzufügen

### ISSUE THREAD

**Issue by Kasperle99** [ioBroker/ioBroker.sonoff#25]
Hallo,
könnt Ihr im Adapter den Internen ADC hinzufügen. Werte werden vom Sonoff übertragen, nur es wird kein Objekt erstellt.
Output Sonoff Console:
17:36:59 MQT: tele/sonoff/SENSOR = {"Time":"2018-02-23T17:36:59","Analog0":298}

Debuglog Sonoff-Adapter:
sonoff.0 2018-02-23 17:36:59.646 debug [Basic-Analog] Received: tele/sonoff/SENSOR = {"Time":"2018-02-23T17:36:59","Analog0":298}

Danke

**Comment by Benotto** [comment]
Please :-)
tele/terassensensor/SENSOR = {"Time":"2018.03.03 15:25:41","Analog0":31,"DS18x20":{"DS1":{"Type":"DS18S20","Address":"1035D20E010800E8","Temperature":-0.1}},"TempUnit":"C"}

Ich möchte die Helligkeit draussen messen um die Beleuchtung zu steuern 
Viele Dank

**Comment by GermanBluefox** [comment]
Done in 1.0.3

**Comment by Kasperle99** [comment]
Super. Sehr gute Arbeit. Funktioniert bei mir. 

Vielen vielen Dank Bluefox.

**Comment by Benotto** [comment]
Cool! Gleich getestet und funktioniert.
Vielen Dank!!!!!
Benotto
