### ISSUE TITLE
Support für Tasmota Magichome

### ISSUE THREAD

**Issue by gemu2015** [ioBroker/ioBroker.sonoff#26]
Magichome liefert z.B. die Werte Color und Dimmer. Habe die Datenpunkte in server.js erstellt und sie werden auch erzeugt. Es gibt aber kein Update und die Werte können auch nicht gesendet werden trotz write=true
dimmer geht von 0-100
color ist ein hex wert der je nach konfiguration zB bei RGB 24 Bit und bei RGBWW 32 bit hat.
per Tasmota console kann ich beide Werte problemlosen schalten.

Mit POWER kann man die LEDS an und aus schalten das funktioniert problemlos.

**Comment by Chaot1** [comment]
Das einzubauen wäre top!
Die Chinadinger sind zwar billig und erfüllen ihren Zweck, aber deren Cloud ist leider voll für'n ******

**Comment by gemu2015** [comment]
Guck mal hier =>https://github.com/gemu2015/iobroker-sonoff-test <https://github.com/gemu2015/iobroker-sonoff-test>


https://github.com/gemu2015/iobroker-so ... gemus-test <https://github.com/gemu2015/iobroker-sonoff-test/tarball/gemus-test>

**Comment by GermanBluefox** [comment]
Gibt es die Möglichkeit Gerätetyp zu lesen? Dann könnte man automatisch
write  Sachen erzeugen.

вс, 18 мар. 2018 г., 6:47 gemu <notifications@github.com>:

**Comment by gemu2015** [comment]
Das ergibt sich automatisch aus der Länge des Color Wertes, habe ich berücksichtigt. Wird in Color role als Typ gesetzt. Es werden schon alle möglichen Write Sachen automatisch erzeugt

Von meinem iPad gesendet

**Comment by ChrSch84** [comment]
da ja mein Case geschlossen wurde muss ich hier mal einhaken. Wenn ich diese "Test" Sonoff installiere bin ich auf einem alten Stand. Wird dieser LED Strang wieder in den Hauptstrang aufgenommen? Danke. #16

**Comment by gemu2015** [comment]
Dieser LED Strang ist auf demselben Stand wie der Master wird aber ohnehin bald dort übernommen.

Von meinem iPad gesendet

**Comment by GermanBluefox** [comment]
Close?

**Comment by gemu2015** [comment]
can be closed!
