### ISSUE TITLE
SONOFF B1

### ISSUE THREAD

**Issue by nivek88** [ioBroker/ioBroker.sonoff#29]
Hallo,
wäre es möglich den Funktionsumfang derart zu erweitern, dass man die Sonoff B1 Lampe mehr als nur ein- und ausschalten kann? So das man z.B. die Helligkeit oder sogar die RGB-LEDs ansteuern kann?
Danke

**Comment by Alveran81** [comment]
Hier ist ein Clone. Wenn es gut läuft wird es hoffentlich bald in die Hauptversion integriert. 
Ich verstehe nicht warum das Thema LED Beleuchtung so Stiefmütterlich behandelt wird. Es gibt so viele LED Controller und Lampen. (Arilux, Magichome, B1 und wie sie alle heißen) aber eine vernünftige Integration gab es bisher nicht.

https://github.com/gemu2015/iobroker-sonoff-test

**Comment by GermanBluefox** [comment]
Weil 

> Es gibt so viele LED Controller und Lampen. (Arilux, Magichome, B1 und wie sie alle heißen)

Und die alle funktionieren irgendwie unterschiedlich.
