### ISSUE TITLE
no update of power_energy

### ISSUE THREAD

**Issue by wschiro** [ioBroker/ioBroker.sonoff#291]
**Describe the bug**  
no update of ENERGY_Power. Only if I restart the plug or the adapter the object will be updated.
to switch on/off the TasmotaplugI use the POWER object . This works fine und update  immediately.
Tasmota-Plug V 11.1

It is no error message, simple no update if I switch on the plug.
**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.5.1
 - iobroker 4.0.23
 - JS-Controller version: <js-controller-version> 
 - Node version: 19.1.0 
 - Operating system: rasberry

**Additional context**

**Comment by Apollon77** [comment]
Please enable debug log and provide that log of such caes where data changes but are not updated

**Comment by wschiro** [comment]
the iobroker-protokoll shows nothing, if I switch on off.  the console of the plugs has an entry of switch on off, but no ENERGY-power

**Comment by wschiro** [comment]
what is the updateintervall of the adapter?

**Comment by Apollon77** [comment]
Did you really set the log to Debug?? Instances - expert mode - expand instance - change "Loglevel" setting

**Comment by wschiro** [comment]
sorry,
here the part of the protokoll for ENERGY_Power
all the other  parameter looks similar

Am Di., 27. Dez. 2022 um 15:31 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
> der ganze log ist zu gross zum senden

File attachements als .log oder gepackt sollte gehen

**Comment by wschiro** [comment]
Ich hab die Ursache gefunden. In der plug-konfiguration war das updateintervall auf 3000 gestellt, Standardeinstellung.
Jetzt habe ich es auf 30sec. Und alles ist gut.
Danke für die Hinweise, ohne die wäre ich noch blind
