### ISSUE TITLE
Sonoff TH10/16 DS18X20

### ISSUE THREAD

**Issue by fragman89** [ioBroker/ioBroker.sonoff#30]
Hallo, 

besteht die möglichkeit beim Adapter den Sensor DS18X20 einzupflegen.
In der Tasmota Weboberfläche werden die Werte für Temperatur angezeigt nur nicht im Adapter.

LG Pierre

**Comment by Apollon77** [comment]
Bitte mehr details zu den gesendeten Daten hier angeben. Wie heissen die Messages/Daten exakt?

**Comment by fragman89** [comment]
Hier der Log aus der Weboberfläche 
9:15:06 MQT: sonoff_0494/tele/SENSOR = {"Time":"2018-03-13T19:15:06","DS18B20":{"Temperature":18.3},"TempUnit":"C"}

**Comment by GermanBluefox** [comment]
Muss schon drin sein.

13 мар. 2018 г. 19:17 пользователь "fragman89" <notifications@github.com>
написал:

**Comment by fragman89** [comment]
Alles klar aber an was kann es liegen die Sonor POW werden alle richtig eingelesen nur halt der TH16 mit Sensor dran nicht

**Comment by Apollon77** [comment]
Elche Version des Adapters nutzt du?

**Comment by fragman89** [comment]
Hallo,
also ich konnte es endlich an einem anderem Sonoff TH16 testen da hat der Adapter reibungslos funktioniert. Ich habe meinen jetzt auch noch mal mit ner älteren Firmware von Tasmota geflasht und hab es per Weboberfläche zurückgesetzt und dann ging es auch endlich.

Ich habe aber noch ne fragen zu einem Sonoff SC soll ich da einen Issues starten?

LG Pierre
