### ISSUE TITLE
Sonoff SC

### ISSUE THREAD

**Issue by GrumpyNyanCat** [ioBroker/ioBroker.sonoff#31]
Ist es Möglich noch die Sensorwerte "Light", "Noise" und "Air Quality" des Sonoff SC miteinzupflegen? Bis jetzt werden im Broker nur "Temperature" und "Humidity" angezeigt.

`MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-03-16T01:56:06","Temperature":24.0,"Humidity":43.0,"Light":10,"Noise":20,"AirQuality":80,"TempUnit":"C"}}`

Grüße

**Comment by GermanBluefox** [comment]
Ich brauche die debug Ausgaben dafür

16 мар. 2018 г. 0:51 пользователь "GrumpyNyanCat" <notifications@github.com>
написал:

**Comment by GrumpyNyanCat** [comment]
Hi :-) 

was muss ich machen?

**Comment by GermanBluefox** [comment]
Kennst du die Units für Light, Noise, AirQuality?
lux, dB, %

**Comment by GermanBluefox** [comment]
Please test 2.0.0 from github

**Comment by GrumpyNyanCat** [comment]
Funktioniert :-) fehlenden Werte sind jetzt unter den Objekten zu finden.

Vielen Dank. Sollte ich noch auf etwas spezielles testen?
