### ISSUE TITLE
User Password Warning

### ISSUE THREAD

**Issue by Bettman66** [ioBroker/ioBroker.sonoff#311]
Admin v6.6.5
js-controller v5.0.11
sonoff v2.5.7

I created a second instance with a different port and the same user/password.
The device registers errors at the second instance and can be registered again at the first instance without errors.

[Forum](https://forum.iobroker.net/topic/67321/adapter-sonoff-nach-%C3%A4nderung-des-password-keine-verbindung/9?_=1690988534483)

```
Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
sonoff.0 | 2023-08-02 16:47:31.764 | info | Client [Wohnen.Fliegenfalle] connected with secret 1690987651764_6692
sonoff.1 | 2023-08-02 16:47:19.421 | warn | Client [Wohnen.Fliegenfalle] has invalid password or username
sonoff.1 | 2023-08-02 16:46:54.543 | warn | Client [Wohnen.Fliegenfalle] has invalid password or username
sonoff.1 | 2023-08-02 16:46:39.689 | warn | Client [Wohnen.Fliegenfalle] has invalid password or username
sonoff.0 | 2023-08-02 16:46:33.836 | info | Client [Wohnen.Fliegenfalle] connection closed: closed
sonoff.1 | 2023-08-02 16:46:13.630 | info | Starting MQTT authenticated server on port 1155
sonoff.1 | 2023-08-02 16:46:13.602 | info | starting. Version 2.5.7 (non-npm: ioBroker/ioBroker.sonoff) in /opt/iobroker/node_modules/iobroker.sonoff, node: v18.17.0, js-controller: 5.0.11
host.iobroker | 2023-08-02 16:46:12.981 | info | instance system.adapter.sonoff.1 started with pid 68931
host.iobroker | 2023-08-02 16:46:12.910 | info | "system.adapter.sonoff.1" enabled
```

**Comment by Apollon77** [comment]
So problem is that connecting a second instance to the same device do not work? or what exactly is the issue? Are you sure the devcie supports multiple parallel connections?

**Comment by 0x1234567890** [comment]
why nobody fix this?

**Comment by Apollon77** [comment]
because nobody knows the reason and nobody had time till now ?!

Fact is that all potentially relevant changes regarding username/passwort were last changes ages ago and the isue started popping up a week ago. Is that correctly summarized?

Which sonoff versions are in use here? Maybe it is a change there or such?

In fact someone with such devices at hand  need to find out the reason.

**Comment by Bettman66** [comment]
So ich habe auf meinem Proxmoxserver eine neue ioBroker Installation mit dem Repo stable durchgeführt.
Danach den Sonoff 2.5.3 installiert und Passwortänderungen ohne Probleme getestet.
Das Repo auf latest umgestellt und nur den Sonoff auf 2.5.7 gezogen.
Der Adapter startet normal und das Tasmotagerät verbindet sich ohne Probleme mit dem Adapter.
Nach einer Passwortänderung im Sonoffadapter 2.5.7 und im Tasmotagerät kommt keine Verbindung mehr zustande.
Laut Changelog wurde am Passwort Management was geschraubt.
_(mcm1957) Disabled the logging of username and password during connection errors_

**Comment by GTV1** [comment]
> So ich habe auf meinem Proxmoxserver eine neue ioBroker Installation mit dem Repo stable durchgeführt. Danach den Sonoff 2.5.3 installiert und Passwortänderungen ohne Probleme getestet. Das Repo auf latest umgestellt und nur den Sonoff auf 2.5.7 gezogen. Der Adapter startet normal und das Tasmotagerät verbindet sich ohne Probleme mit dem Adapter. Nach einer Passwortänderung im Sonoffadapter 2.5.7 und im Tasmotagerät kommt keine Verbindung mehr zustande. Laut Changelog wurde am Passwort Management was geschraubt. _(mcm1957) Disabled the logging of username and password during connection errors_

Sehe ich auch so. Irgendwo zwischen 2.5.3 und 2.5.7 muss das Problem liegen. Ich habe auch wieder 2.5.3 installieren müssen damit alles wie gewohnt läuft.

**Comment by Apollon77** [comment]
Ok, das ist schonmal eine wichtige Info. Danke!

https://github.com/ioBroker/ioBroker.sonoff/compare/865c4a8e46...master

**Comment by Apollon77** [comment]
Frage: Wenn Passwort und username per Admin gesetzt werden in der 2.5.7 -> was steht dann in der Adapter konfig im JSON unter system.adapter.sonoff.0 im Objekt? stehen da die richtigen werte?

**Comment by Bettman66** [comment]
Ich kann leider keinen Daumen nach oben geben wie @GTV1 , es hat sich sogar bei mir verschlimmert.
Nach Upgrade von 2.5.3 nach 3.0.1 kommt sofort die Passwortwarnung, nicht erst wie bei der 2.5.7 nach Passwortwechsel.
Ein Downgrade funktioniert auch nicht mehr es muss die 2.5.3 neu installiert werden. Eine Neuinstallation der 3.0.1 funktioniert
auch nicht es lassen sich bei mir keine Geräte anmelden.

**Comment by Apollon77** [comment]
WIe @GermanBluefox gesagt hjat muss in der 3.0.1 das passwort einmalig NEU gesetzt werden!! Sollte aber danach gehen

Geht das?

**Comment by Bettman66** [comment]
Wie ich oben geschrieben habe bei mir nicht.

**Comment by Bettman66** [comment]
`} else if (!adapter.config.password && adapter.config.pass) {`
Das ! ist falsch
`} else if (adapter.config.password && !adapter.config.pass) {`

**Comment by Bettman66** [comment]
Habe mir den Code mal genauer angeschaut und er hätte stimmen müssen.
Warum es bei mir nicht funktioniert sehe ich mir mal an, melde mich.

**Comment by Bettman66** [comment]
Hab ein Pull request erstellt
