### ISSUE TITLE
 sonoff.0 2023-08-07 21:32:55.260	warn	Client [xxx] has invalid password or username

### ISSUE THREAD

**Issue by 0x1234567890** [ioBroker/ioBroker.sonoff#312]
my MQTT Clients cant conntect to the server v2.5.7  .In iobroker is only this error :

sonoff.0 | 2023-08-07 21:32:55.260 | warn | Client [xxx] has invalid password or username

but the passwords are 100% correct. Whatever I do it does not work

![image](https://github.com/ioBroker/ioBroker.sonoff/assets/1353407/27232779-d47f-44a5-99f4-e54c7915bfe0)
![image](https://github.com/ioBroker/ioBroker.sonoff/assets/1353407/67fd1555-bc45-49fa-aa5e-eedd54b1305b)
![image](https://github.com/ioBroker/ioBroker.sonoff/assets/1353407/0c1c7543-775a-4a9e-bfde-1ae3f891813e)
![image](https://github.com/ioBroker/ioBroker.sonoff/assets/1353407/cff4276c-18b1-44bd-b560-25729866fc95)
i had reset the password because i no longer had it and now i can't connect any device at all

**Comment by Bettman66** [comment]
look here #311
