### ISSUE TITLE
BPM180 SeaLevel Pressure

### ISSUE THREAD

**Issue by downset** [ioBroker/ioBroker.sonoff#32]
Hi,
would it be possible to add the Altimate corrected Pressure value called SeaPressure

here is the RAW log Data:

`

stateChange sonoff.0.TH16_Wohnzimmer.BMP180_Pressure: {"val":963.4,"ack":true,"ts":1521291321999,"q":0,"from":"system.adapter.sonoff.0","lc":1521291321999}
sonoff.0 | 2018-03-17 13:55:22.007 | debug | stateChange sonoff.0.TH16_Wohnzimmer.BMP180_Temperature: {"val":32.3,"ack":true,"ts":1521291321998,"q":0,"from":"system.adapter.sonoff.0","lc":1521291321998}
sonoff.0 | 2018-03-17 13:55:21.999 | debug | stateChange sonoff.0.TH16_Wohnzimmer.AM2301_Humidity: {"val":37.6,"ack":true,"ts":1521291321996,"q":0,"from":"system.adapter.sonoff.0","lc":1521291200850}
sonoff.0 | 2018-03-17 13:55:21.998 | debug | stateChange sonoff.0.TH16_Wohnzimmer.AM2301_Temperature: {"val":23.1,"ack":true,"ts":1521291321993,"q":0,"from":"system.adapter.sonoff.0","lc":1521291321993}
sonoff.0 | 2018-03-17 13:55:21.993 | debug | [TH16_Wohnzimmer] Received: tele/sonoff/SENSOR = {"Time":"2018.03.17 13:55:17","AM2301":{"Temperature":23.1,"Humidity":37.6},"**BMP180":{"Temperature":32.3,"Pressure":963.4,"SeaPressure":1004.4}**,"TempUn
sonoff.0 | 2018-03-17 13:55:21.934 | debug | stateChange sonoff.0.TH16_Wohnzimmer.Wifi_RSSI: {"val":54,"ack":true,"ts":1521291321927,"q":0,"from":"system.adapter.sonoff.0","lc":1521291200779}
sonoff.0 | 2018-03-17 13:55:21.934 | debug | stateChange sonoff.0.TH16_Wohnzimmer.POWER: {"val":true,"ack":true,"ts":1521291321927,"q":0,"from":"system.adapter.sonoff.0","lc":1521290594538}
sonoff.0 | 2018-03-17 13:55:21.928 | debug | stateChange sonoff.0.TH16_Wohnzimmer.Vcc: {"val":3.418,"ack":true,"ts":1521291321925,"q":0,"from":"system.adapter.sonoff.0","lc":1521291200776}
sonoff.0 | 2018-03-17 13:55:21.924 | debug | [TH16_Wohnzimmer] Received: tele/sonoff/STATE = {"Time":"2018.03.17 13:55:17","Uptime":"0 00:20:15","Vcc":3.418,"POWER":"ON","Wifi":{"AP":1,"SSId":"CM","RSSI":54,"APMac":"60:45:CB:68:E8:00"}}

`
greets
downset

**Comment by GermanBluefox** [comment]
Please test https://github.com/ioBroker/ioBroker.sonoff/commit/f0b6cdc674f1f1449ed9d5486813422086bb64f4
2.0.2

**Comment by downset** [comment]
It`s working,

Thank you very much.

feel free to contact me if you need any Log data or something else.

Greets 
downset
