### ISSUE TITLE
TypeError: window.CryptoJS is undefined

### ISSUE THREAD

**Issue by stephanritscher** [ioBroker/ioBroker.sonoff#321]
**Describe the bug**  
After upgrading to v3.0.3, I tried to update MQTT user/password as I read [here](https://forum.iobroker.net/topic/68651/sonoff-invalid-password-or-username/14) that config changes require this. This failed with an error popup.

**To Reproduce**  
1. Go to instances and press settings icon of sonoff.0
2. Enter a new MQTT password (and possibly change other settings)
3. Press save & close (same behaviour with "save", but more steps to verify)
4. A popup with the error `[JsonConfig] Cannot set object: TypeError: window.CryptoJS is undefined` appears.
5. Re-open adapter settings and see that the changed settings have not been stored.

**Expected behavior**  
The entered settings should have been stored. Especially, MQTT user/password should have been stored such that devices should be able to connect again which failed after sonoff adapter upgrade (supposedly) due to config changes.

**Versions:**  
 - Adapter version: v3.0.3
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Fedora Linux 38

**Additional context**  
I use redis for objects and states:
```
$ iob status
iobroker is running on this host.

At least one iobroker host is running.

Objects type: redis
States  type: redis
```

**Comment by Apollon77** [comment]
Which browser do you use?

**Comment by stephanritscher** [comment]
Firefox on Linux Fedora

**Comment by Apollon77** [comment]
irgendwelche Fehlw rin der Browser Konsole wie geblockte skripte oder sowas?

**Comment by stephanritscher** [comment]
Ich habe gerade festgestellt, dass das Problem von meinem Reverse-Proxy-Setup verursacht wird. Bei direkter Verbindung hat alles geklappt. Vielen Dank für den Tipp
