### ISSUE TITLE
Sonoff Pow übergibt keine Energy werte

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.sonoff#34]
Guten Tag,
Heute sind meine Sonoff´s aus china angekommen.
Ich habe mich mal ran gesetzt und einen Pow geflasht und jetzt zu meinem Problem.
der State zum Power triggern ist in iobroker angekommen aber der rest nicht mit fehlt die komplette Sparte Energy.
die Tasmota Firmware ist auf Sonoff Pow umgestellt wurden und gibt in der console auch folgenden wert aus:
`17:08:46 RSL: tele/sonoff/SENSOR = {"Time":"2018-03-19T17:08:46","ENERGY":{"Total":0.000,"Yesterday":0.000,"Today":0.000,"Period":0,"Power":2,"Factor":0.09,"Voltage":215,"Current":0.115}}`

**Comment by GermanBluefox** [comment]
Wie ist die Version von iobroker.sonoff?

eXplOiD1 <notifications@github.com> schrieb am Mo., 19. März 2018, 17:10:

**Comment by eXplOiD1** [comment]
2.0.1 die aktuellste mit der älteren ging es aber auch nicht

**Comment by GermanBluefox** [comment]
Dein Debug ist komisch. Was ist das ich erwarte so was:

`sonoff.0 | 2018-03-17 13:55:21.993 | debug | [TH16_Wohnzimmer] Received: tele/sonoff/SENSOR = {"Time":"2018.03.17 13:55:17","AM2301":{"Temperature":23.1,"Humidity":37.6},"BMP180":{"Temperature":32.3,"Pressure":963.4,"SeaPressure":1004.4},"TempUn`

Wo kommt deine Zeile her?

**Comment by eXplOiD1** [comment]
Die kommen aus der console des webinterfaces vpn meinem sonoff pow

**Comment by eXplOiD1** [comment]
ein debug log vom adapter sehe ich nicht wie kann ich diesen aktivieren

**Comment by eXplOiD1** [comment]
was ich Persönlich komisch daran finde, gehe ich hin und stelle den sonoff auf Basic und sage dem gpio14 das er ein switch ist wird das objekt an iobroker übergeben nur energy wird eben nicht erstellt

**Comment by GermanBluefox** [comment]
Mit dem gleichen Effekt kannst du hier die Logs von deinem Wasserkocher die
Logs posten, da ich nicht mal weiss ob dein wasserkocher angeschlossen ist.

Bitte stelle den debug Level (Experten modus auf Instanzen) ein und Posten
die Ausgabe von iobroker.

eXplOiD1 <notifications@github.com> schrieb am Mo., 19. März 2018, 22:32:

**Comment by eXplOiD1** [comment]
sonoff.0 | 2018-03-20 08:33:22.650 | info | Client [Sonoff-pow-wohnzimmer] connected
-- | -- | -- | --
sonoff.0 | 2018-03-20 08:33:13.582 | info | Starting MQTT authenticated server on port 1884
sonoff.0 | 2018-03-20 08:33:13.579 | info | starting. Version 2.0.1 in /mnt/iobroker/node_modules/iobroker.sonoff, node: v8.8.0
sonoff.0 | 2018-03-20 08:33:11.147 | info | terminating
sonoff.0 | 2018-03-20 08:33:10.649 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":false,"ack":true,"ts":1521531190648,"q":0,"from":"system.adapter.sonoff.0","lc":1521531190648}
sonoff.0 | 2018-03-20 08:33:09.024 | debug | system.adapter.admin.0: logging false
sonoff.0 | 2018-03-20 08:33:01.343 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:32:46.337 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:32:31.341 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:32:20.412 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/RESULT = {"Command":"Unknown"}
sonoff.0 | 2018-03-20 08:32:16.333 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:32:01.333 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:31:46.330 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:31:31.329 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:31:16.327 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:31:01.331 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:30:46.325 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:30:31.333 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":true,"ack":true,"ts":1521531031329,"q":0,"from":"system.adapter.sonoff.0","lc":1521531031329}
sonoff.0 | 2018-03-20 08:30:31.330 | debug | [Sonoff-pow-wohnzimmer] Received: cmnd/sonoff/POWER =
sonoff.0 | 2018-03-20 08:30:31.314 | debug | stateChange sonoff.0.info.connection: {"val":"Sonoff-pow-wohnzimmer","ack":true,"ts":1521531031311,"q":0,"from":"system.adapter.sonoff.0","lc":1521531031311}
sonoff.0 | 2018-03-20 08:30:31.267 | info | Client [Sonoff-pow-wohnzimmer] connected
sonoff.0 | 2018-03-20 08:30:21.582 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":false,"ack":true,"ts":1521531021581,"q":0,"from":"system.adapter.sonoff.0","lc":1521531018570}
sonoff.0 | 2018-03-20 08:30:21.580 | debug | stateChange sonoff.0.schlafzimmer-licht.alive: {"val":false,"ack":true,"ts":1521531021578,"q":0,"from":"system.adapter.sonoff.0","lc":1521465666998}
sonoff.0 | 2018-03-20 08:30:21.576 | debug | stateChange sonoff.0.info.connection: {"val":"","ack":true,"ts":1521531021559,"q":0,"from":"system.adapter.sonoff.0","lc":1521531021559}
sonoff.0 | 2018-03-20 08:30:21.556 | info | Starting MQTT authenticated server on port 1884
sonoff.0 | 2018-03-20 08:30:21.534 | info | starting. Version 2.0.1 in /mnt/iobroker/node_modules/iobroker.sonoff, node: v8.8.0
sonoff.0 | 2018-03-20 08:30:21.441 | debug | statesDB connected
sonoff.0 | 2018-03-20 08:30:21.422 | debug | objectDB connected
sonoff.0 | 2018-03-20 08:30:19.068 | info | terminating
sonoff.0 | 2018-03-20 08:30:18.571 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":false,"ack":true,"ts":1521531018570,"q":0,"from":"system.adapter.sonoff.0","lc":1521531018570}
sonoff.0 | 2018-03-20 08:30:14.137 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:29:59.122 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:29:44.122 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:29:29.119 | debug | Client [Sonoff-pow-wohnzimmer] pingreq
sonoff.0 | 2018-03-20 08:29:18.208 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.POWER: {"val":true,"ack":true,"ts":1521530958207,"q":0,"from":"system.adapter.sonoff.0","lc":1521530958207}
sonoff.0 | 2018-03-20 08:29:18.206 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/POWER = ON
sonoff.0 | 2018-03-20 08:29:18.163 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/RESULT = {"POWER":"ON"}
sonoff.0 | 2018-03-20 08:29:14.113 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":true,"ack":true,"ts":1521530954112,"q":0,"from":"system.adapter.sonoff.0","lc":1521530954112}
sonoff.0 | 2018-03-20 08:29:14.108 | debug | [Sonoff-pow-wohnzimmer] Received: cmnd/sonoff/POWER =
sonoff.0 | 2018-03-20 08:29:14.096 | debug | stateChange sonoff.0.info.connection: {"val":"Sonoff-pow-wohnzimmer","ack":true,"ts":1521530954092,"q":0,"from":"system.adapter.sonoff.0","lc":1521530954092}
sonoff.0 | 2018-03-20 08:29:14.042 | info | Client [Sonoff-pow-wohnzimmer] connected
sonoff.0 | 2018-03-20 08:29:05.095 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":false,"ack":true,"ts":1521530945093,"q":0,"from":"system.adapter.sonoff.0","lc":1521530942141}
sonoff.0 | 2018-03-20 08:29:05.092 | debug | stateChange sonoff.0.schlafzimmer-licht.alive: {"val":false,"ack":true,"ts":1521530945091,"q":0,"from":"system.adapter.sonoff.0","lc":1521465666998}
sonoff.0 | 2018-03-20 08:29:05.084 | debug | stateChange sonoff.0.info.connection: {"val":"","ack":true,"ts":1521530945082,"q":0,"from":"system.adapter.sonoff.0","lc":1521530945082}
sonoff.0 | 2018-03-20 08:29:05.076 | info | Starting MQTT authenticated server on port 1884
sonoff.0 | 2018-03-20 08:29:05.056 | info | starting. Version 2.0.1 in /mnt/iobroker/node_modules/iobroker.sonoff, node: v8.8.0
sonoff.0 | 2018-03-20 08:29:05.031 | debug | statesDB connected
sonoff.0 | 2018-03-20 08:29:05.016 | debug | objectDB connected
sonoff.0 | 2018-03-20 08:29:02.643 | info | terminating

**Comment by eXplOiD1** [comment]
es geht jetzt.
nach einmaligem Triggern von "status 8" in der sonoff console sind die werte erschienen.

**Comment by eXplOiD1** [comment]
ok jetzt habe ich ein anderes Problem die Objekte werden 2 mal erstellt einmal beim triggern des on/off Buttons und das 2te mal bei jeder Überprüfung alle 5 minuten .


host.homeserver | 2018-03-20 10:36:30.783 | error | Caught by controller[0]: TypeError: Cannot read property 'readyState' of undefined
-- | -- | -- | --
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Current: {"val":0,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521538566365}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Voltage: {"val":216,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589073}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Factor: {"val":0,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521538566365}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Power: {"val":29,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589073}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Today: {"val":0.006,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521538533353}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Yesterday: {"val":0,"ack":true,"ts":1521538589073,"q":0,"from":"system.adapter.sonoff.0","lc":1521536923461}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY.ENERGY_Total: {"val":0.006,"ack":true,"ts":1521538589072,"q":0,"from":"system.adapter.sonoff.0","lc":1521538533349}
sonoff.0 | 2018-03-20 10:36:29.085 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Current: {"val":0,"ack":true,"ts":1521538589072,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589072}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Voltage: {"val":216,"ack":true,"ts":1521538589071,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589071}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Factor: {"val":0,"ack":true,"ts":1521538589066,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589066}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Power: {"val":29,"ack":true,"ts":1521538589066,"q":0,"from":"system.adapter.sonoff.0","lc":1521538520354}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Today: {"val":0.006,"ack":true,"ts":1521538589066,"q":0,"from":"system.adapter.sonoff.0","lc":1521538520354}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Yesterday: {"val":0,"ack":true,"ts":1521538589066,"q":0,"from":"system.adapter.sonoff.0","lc":1521536922492}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.ENERGY_Total: {"val":0.006,"ack":true,"ts":1521538589065,"q":0,"from":"system.adapter.sonoff.0","lc":1521538520352}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.Wifi_RSSI: {"val":68,"ack":true,"ts":1521538589062,"q":0,"from":"system.adapter.sonoff.0","lc":1521538520351}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.POWER: {"val":true,"ack":true,"ts":1521538589061,"q":0,"from":"system.adapter.sonoff.0","lc":1521538586883}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/ENERGY = {"Time":"2018-03-20T10:36:28","ENERGY":{"Total":0.006,"Yesterday":0.000,"Today":0.006,"Period":0,"Power":29,"Factor":0.00,"Voltage":216,"Current"
sonoff.0 | 2018-03-20 10:36:29.076 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.Vcc: {"val":3.512,"ack":true,"ts":1521538589059,"q":0,"from":"system.adapter.sonoff.0","lc":1521538589059}
sonoff.0 | 2018-03-20 10:36:29.076 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/SENSOR = {"Time":"2018-03-20T10:36:28","ENERGY":{"Total":0.006,"Yesterday":0.000,"Today":0.006,"Period":0,"Power":29,"Factor":0.00,"Voltage":216,"Current"
sonoff.0 | 2018-03-20 10:36:29.060 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/STATE = {"Time":"2018-03-20T10:36:28","Uptime":"0T00:00:13","Vcc":3.512,"POWER":"ON","Wifi":{"AP":1,"SSId":"eXplOiD-Access-2.4ghz","RSSI":68,"APMac":"50:C
sonoff.0 | 2018-03-20 10:36:26.885 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.POWER: {"val":true,"ack":true,"ts":1521538586883,"q":0,"from":"system.adapter.sonoff.0","lc":1521538586883}
sonoff.0 | 2018-03-20 10:36:26.883 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/POWER = ON
sonoff.0 | 2018-03-20 10:36:26.878 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/RESULT = {"POWER":"ON"}
sonoff.0 | 2018-03-20 10:36:22.041 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.POWER: {"val":false,"ack":true,"ts":1521538582039,"q":0,"from":"system.adapter.sonoff.0","lc":1521538564101}
sonoff.0 | 2018-03-20 10:36:22.039 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/POWER = OFF
sonoff.0 | 2018-03-20 10:36:22.028 | debug | [Sonoff-pow-wohnzimmer] Received: stat/sonoff/RESULT = {"POWER":"OFF"}
sonoff.0 | 2018-03-20 10:36:21.067 | debug | [Sonoff-pow-wohnzimmer] Received: homeassistant/switch/sonoff_1/config = {"name":"Sonoff","command_topic":"cmnd/sonoff/POWER","state_topic":"stat/sonoff/RESULT","value_template":"{{value_json.POWER}}"
sonoff.0 | 2018-03-20 10:36:21.060 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.INFO.RestartReason: {"val":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x4010011d epc2:0x00000000 epc3:0x00000000 excvaddr:0x40036c58 depc:0x00000000","ack":t
sonoff.0 | 2018-03-20 10:36:21.060 | debug | [Sonoff-pow-wohnzimmer] Received: homeassistant/light/sonoff_1/config =
sonoff.0 | 2018-03-20 10:36:21.057 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/INFO3 = {"RestartReason":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x4010011d epc2:0x00000000 epc3:0x00000000 excvaddr:0x40036c58 depc:0x00000000"}
sonoff.0 | 2018-03-20 10:36:21.026 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.INFO.IPAddress: {"val":"192.168.3.105","ack":true,"ts":1521538581023,"q":0,"from":"system.adapter.sonoff.0","lc":1521465384151}
sonoff.0 | 2018-03-20 10:36:21.026 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.INFO.Hostname: {"val":"sonoff-5831","ack":true,"ts":1521538581018,"q":0,"from":"system.adapter.sonoff.0","lc":1521465384150}
sonoff.0 | 2018-03-20 10:36:21.020 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.INFO.Version: {"val":"5.12.0g","ack":true,"ts":1521538581014,"q":0,"from":"system.adapter.sonoff.0","lc":1521536186824}
sonoff.0 | 2018-03-20 10:36:21.020 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.INFO.Module: {"val":"Sonoff Pow","ack":true,"ts":1521538581013,"q":0,"from":"system.adapter.sonoff.0","lc":1521536186817}
sonoff.0 | 2018-03-20 10:36:21.018 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-5831","IPAddress":"192.168.3.105"}
sonoff.0 | 2018-03-20 10:36:21.013 | debug | [Sonoff-pow-wohnzimmer] Received: tele/sonoff/INFO1 = {"Module":"Sonoff Pow","Version":"5.12.0g","FallbackTopic":"Sonoff-pow-wohnzimmer","GroupTopic":"sonoffs"}
sonoff.0 | 2018-03-20 10:36:20.960 | debug | stateChange sonoff.0.Sonoff-pow-wohnzimmer.alive: {"val":true,"ack":true,"ts":1521538580956,"q":0,"from":"system.adapter.sonoff.0","lc":1521538580956}
sonoff.0 | 2018-03-20 10:36:20.960 | debug | [Sonoff-pow-wohnzimmer] Received: cmnd/sonoff/POWER =
sonoff.0 | 2018-03-20 10:36:20.879 | debug | stateChange sonoff.0.info.connection: {"val":"Sonoff-pow-wohnzimmer","ack":true,"ts":1521538580874,"q":0,"from":"system.adapter.sonoff.0","lc":1521538580874}

[screenshot](https://www2.pic-upload.de/img/35030751/Unbenannt-2.png)

**Comment by GermanBluefox** [comment]
Bitte neuen Issue aufmachen.
Was heißt 2 mal erstellt?

**Comment by wowik2018** [comment]
undefined2018-11-26 20:48:13.541 - debug: sonoff.0 Client [DVES_A3174F] pingreq
--
2018-11-26 20:48:17.166 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:48:23.513 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:48:27.172 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:48:33.523 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:48:37.176 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:48:43.522 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:48:47.183 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:48:53.540 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:48:57.184 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:03.530 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:07.188 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:13.569 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:17.227 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:23.537 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:27.197 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:33.536 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:37.199 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:43.539 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:47.200 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:49:53.541 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:49:57.201 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:03.546 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:07.202 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:13.545 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:17.206 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:23.553 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:27.206 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:33.548 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:37.210 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:43.549 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:47.212 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:50:53.551 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:50:57.212 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:51:03.551 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:51:06.238 - debug: sonoff.0 [DVES_9EAD94] Received: tele/sonoff/STATE = {"Time":"2018-11-26T20:51:05","Uptime":"0T23:10:53","Vcc":3.208,"POWER":"OFF","Wifi":{"AP":1,"SSId":"UPC9AB63FF","BSSId":"54:67:51:56:7C:F7","Channel":1,"RSSI":68}}
2018-11-26 20:51:06.245 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.Time: {"val":"2018-11-26T20:51:05","ack":true,"ts":1543261866241,"q":0,"from":"system.adapter.sonoff.0","lc":1543261866241}
2018-11-26 20:51:06.253 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.Uptime: {"val":"0T23:10:53","ack":true,"ts":1543261866250,"q":0,"from":"system.adapter.sonoff.0","lc":1543261866250}
2018-11-26 20:51:06.257 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.Vcc: {"val":3.208,"ack":true,"ts":1543261866255,"q":0,"from":"system.adapter.sonoff.0","lc":1543251585419}
2018-11-26 20:51:06.268 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.POWER: {"val":false,"ack":true,"ts":1543261866266,"q":0,"from":"system.adapter.sonoff.0","lc":1543209435812}
2018-11-26 20:51:06.275 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.Wifi_Channel: {"val":1,"ack":true,"ts":1543261866273,"q":0,"from":"system.adapter.sonoff.0","lc":1543173816329}
2018-11-26 20:51:06.282 - debug: sonoff.0 stateChange sonoff.0.DVES_9EAD94.Wifi_RSSI: {"val":68,"ack":true,"ts":1543261866280,"q":0,"from":"system.adapter.sonoff.0","lc":1543261866280}
2018-11-26 20:51:07.231 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:51:13.552 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:51:17.211 - debug: sonoff.0 Client [DVES_9EAD94] pingreq
2018-11-26 20:51:23.557 - debug: sonoff.0 Client [DVES_A3174F] pingreq
2018-11-26 20:51:27.213 - debug: sonoff.0 Client [DVES_9EAD94] pingreq

**Comment by GermanBluefox** [comment]
I cant see in
```
{"Time":"2018-11-26T20:51:05","Uptime":"0T23:10:53","Vcc":3.
208,"POWER":"OFF","Wifi":{"AP":1,"SSId":"UPC9AB63FF","BSSId"
:"54:67:51:56:7C:F7","Channel":1,"RSSI":68}}
```
Any energy. Because of that the value is not in iob

Am Mo., 26. Nov. 2018, 21:04 hat wowik2018 <notifications@github.com>
geschrieben:
