### ISSUE TITLE
Unterstützung der

### ISSUE THREAD

**Issue by Basti149** [ioBroker/ioBroker.sonoff#344]
Hallo wäre es möglich den PCA9685 in den Sonoff Adapter zu unterstützen?
Es werden die Datenpunkte PCA9685_PWM0- PCA9685_PWM15 als Datenpunkte generiert aber leider kann man sie nicht Dimmen da sie schreibgeschützt sind. Auch wenn ich ein Slider in der visu mit den DB verbinde kommt Kommando Error.
Es wäre auch schön wenn man 0-15 nochmal als On/ Off Button hat.

https://tasmota.github.io/docs/PCA9685/

Gerne stelle ich alle Relevanten Daten zur Verfügung vielleicht helfen die Bilder. 
Ist nicht super dringend aber schön wenn es irgendwann funktioniert.

![Unbenannt3](https://github.com/ioBroker/ioBroker.sonoff/assets/58861066/706797b6-559b-4b7b-8c7b-9fb85b04a2f6)
![Unbenannt454](https://github.com/ioBroker/ioBroker.sonoff/assets/58861066/6f93b2cc-7d07-465a-9ce1-a8c733c9c10d)
![Unbenanntfdf](https://github.com/ioBroker/ioBroker.sonoff/assets/58861066/040f3f0b-4606-40b9-9740-fcb922dcafb5)

**Comment by Apollon77** [comment]
PWM added by @mattreim  in next version
