### ISSUE TITLE
Please add ESP32 PWM Mode with SetOption15 off

### ISSUE THREAD

**Issue by eddymc3** [ioBroker/ioBroker.sonoff#361]
Hi, 
can you please add the feature for the ESP32 DevKit PWM Channels, that the normal PWM Mode (SetOption15 off) with read and write is recognized by the Adapter. I'd like to set 8 diffrent Channels with numbers from 0-1023 from IoBroker.
Thanks a lot!

**Comment by eddymc3** [comment]
forget to say, that I want to use it with MQTT.
To specify my problem, I get the data in IoBroker if I activate the automatic for stat/Results, but I can't write it. The Tasmota Console gets the error 14:39:56.484 MQT: stat/tasmota_80CB7C/RESULT = {"Command":"Unknown"}

**Comment by Apollon77** [comment]
in next version
