### ISSUE TITLE
Add ClientId to Warning "Cannot parse ..."

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/ioBroker.sonoff#362]
**Consider the Reality**  
The adapter is using the same API as the Alexa mobile App. This means:

If you can not do this what you want with the App then the Adapter also can not do it! Also a feature rewuest most likely will not be possible.

**Is your feature request related to a problem? Please describe.**
If I get warning in log, like Cannot parse data "RESULT": _{"�#@1"_ - SyntaxError: Unexpected token  in JSON at position 2

**Describe the solution you'd like**
It will be nice, if we can get also the clientID, which send this wrong data. 

**Describe alternatives you've considered**
I can also set the adapter to debug or info, but normally the log should be clean. I can't reproduce it on demand, so I've have to wait.

Perhaps it is simple to change 
adapter.log.warn(`Cannot parse data "${stateId}": _${val}_ - ${e}`);
to
adapter.log.warn(`[${client.id}] Cannot parse data "${stateId}": _${val}_ - ${e}`);

**Comment by Apollon77** [comment]
in next version
