### ISSUE TITLE
Relaisausgang lässt sich per iobroker sonoff adapter nicht schalten

### ISSUE THREAD

**Issue by Vetinari1977** [ioBroker/ioBroker.sonoff#371]
Adapter: iobroker sonoff adapter V 3.03
 Tasmota 14.0.0 
Anbindung über mqtt

Die Mqtt Verbindung funktioniert (daten von Tasmota werden empfangen). Wenn ich den Datenpunkt von z.B. Power 1 auf true änder, dann schaltet nichts und nachdem der  esp82 seine daten per mqtt gesendet hat ist der Datenpunkt wieder auf false. Bei älteren Versionen und gleichen Einstellungen (Tasmota 13.2.0) funktioniert alles. Per web ui kann man die Ausgänge problemlos schalten. Auch per http kommando. Was kann ich noch prüfen?

**Comment by Apollon77** [comment]
Kannst Du bitte ggf mal ältere versionen des Adapters versuchen und dann melden von welcher zu welcher es kaputt gegangen ist? und dann am besten debug log von beiden posten das man ggf nach unterschieden schauen kann. Danke

**Comment by mattreim** [comment]
Mit der [Template](https://templates.blakadder.com/search.html)-Funktion können die Geräte richtig konfiguriert werden und es kann auch einige Probleme beheben.

![Tasmota_Template](https://github.com/ioBroker/ioBroker.sonoff/assets/80219712/740ec2c1-1d12-4f3b-906f-6c745baa723f)

**Comment by mcm1957** [comment]
DANKE für die Info.
