### ISSUE TITLE
Add support for VEML6070 UV Light Intensity Sensor

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.sonoff#39]
Hello,

it will be great when you can add the  VEML6070 UV (ultraviolet radiation) Sensor .

![wemos_veml6070](https://user-images.githubusercontent.com/26110738/38668805-01e9bd4e-3e45-11e8-8aa2-307ba12e23d3.jpg)

Here is some additional Info:
https://learn.adafruit.com/adafruit-veml6070-uv-light-sensor-breakout/overview

I am still waiting for the Product, so that I can provide the MQTT String in the next days.

Please tell me if you need more Information about the sensor.
Thank you.

Greetings
Fabian

**Comment by GermanBluefox** [comment]
Please provide debug output. When the device will arrive.

чт, 12 апр. 2018 г., 11:33 FabianHM <notifications@github.com>:

**Comment by FabianHM** [comment]
Das Gerät ist heute angekommen und direkt ausprobiert:
Hier der Output:
MQT: tele/sonoff/SENSOR = {"Time":"2018-04-13T17:31:52","VEML6070":{"UvLevel":0}}

**Comment by FabianHM** [comment]
Werden noch weitere Informationen als der Output benötigt?

**Comment by FabianHM** [comment]
@GermanBluefox It works fine, Thanks :-)
Greetings Fabian
