### ISSUE TITLE
Sonoff basic with Tasmota unresponsive

### ISSUE THREAD

**Issue by DrBoom45** [ioBroker/ioBroker.sonoff#41]

**Comment by DrBoom45** [comment]
Hi everyone,

I'm currently trying to setup my Sonoff basic, flashed with Tasmota, with my iobroker running on a raspberry pi 3.

I have entered the MQTT details into the Sonoff to connect to my iobroker, and the connection can be established.

If I try to change the value of my Sonoff with iobroker and Alexa (power trigger added to the cloud adapter), it does not work.

Also, when the Sonoff is connected via MQTT, the web interface of the Tasmota firmware cannot be reached.

I don't understand where it's going wrong.

Hopefully, you guys can help me integrate this.

Thanks a lot in advance!

**Comment by Apollon77** [comment]
Please turn Adapter into Debug loglevel (Instances -> Export mode ->Column Loglevel) and check the debug. Additionaally check what the device says.

**Comment by DrBoom45** [comment]
`

sonoff.0 | 2018-04-22 15:06:34.097 | info | terminating
-- | -- | -- | --
sonoff.0 | 2018-04-22 15:06:33.307 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 15:06:27.742 | info | Starting MQTT authenticated server on port 1337
sonoff.0 | 2018-04-22 15:06:27.600 | info | starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.sonoff, node: v6.14.1
sonoff.0 | 2018-04-22 15:05:54.403 | info | terminating
sonoff.0 | 2018-04-22 15:05:53.885 | error | at processImmediate [as _immediateCallback] (timers.js:617:5)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at tryOnImmediate (timers.js:645:5)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at runCallback (timers.js:672:20)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3194:38)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at Adapter.emit (events.js:191:7)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at emitTwo (events.js:106:13)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.sonoff/main.js:58:16)
sonoff.0 | 2018-04-22 15:05:53.885 | error | at MQTTServer.onStateChange (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:190:48)
sonoff.0 | 2018-04-22 15:05:53.885 | error | TypeError: Cannot read property 'POWER' of undefined
sonoff.0 | 2018-04-22 15:05:53.883 | error | uncaught exception: Cannot read property 'POWER' of undefined
sonoff.0 | 2018-04-22 15:05:29.218 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:04:58.223 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:04:27.228 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:03:56.224 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:03:25.223 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:02:54.242 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 15:02:54.234 | info | Client [WoZiVorne1] closed
sonoff.0 | 2018-04-22 15:02:23.181 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:01:52.183 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:01:19.191 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 15:00:48.178 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 15:00:47.217 | info | Client [WoZiVorne1] closed
sonoff.0 | 2018-04-22 15:00:17.197 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 15:00:13.335 | info | Client [WoZiVorne1] closed
sonoff.0 | 2018-04-22 14:59:43.200 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:59:12.150 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:58:41.147 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:58:10.149 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:57:39.149 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:57:08.144 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:56:37.134 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:56:06.134 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:55:35.139 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:55:04.134 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:54:32.778 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 14:54:26.907 | info | Starting MQTT authenticated server on port 1337
sonoff.0 | 2018-04-22 14:54:26.776 | info | starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.sonoff, node: v6.14.1
sonoff.0 | 2018-04-22 14:53:53.363 | info | terminating
sonoff.0 | 2018-04-22 14:53:52.843 | error | at processImmediate [as _immediateCallback] (timers.js:617:5)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at tryOnImmediate (timers.js:645:5)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at runCallback (timers.js:672:20)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3194:38)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at Adapter.emit (events.js:191:7)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at emitTwo (events.js:106:13)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.sonoff/main.js:58:16)
sonoff.0 | 2018-04-22 14:53:52.843 | error | at MQTTServer.onStateChange (/opt/iobroker/node_modules/iobroker.sonoff/lib/server.js:190:48)
sonoff.0 | 2018-04-22 14:53:52.843 | error | TypeError: Cannot read property 'POWER' of undefined
sonoff.0 | 2018-04-22 14:53:52.841 | error | uncaught exception: Cannot read property 'POWER' of undefined
sonoff.0 | 2018-04-22 14:53:50.692 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:53:19.690 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:52:48.701 | info | Client [WoZiVorne1] reconnected
sonoff.0 | 2018-04-22 14:52:17.240 | info | Client [WoZiVorne1] connected
sonoff.0 | 2018-04-22 14:52:10.036 | info | Starting MQTT authenticated server on port 1337
sonoff.0 | 2018-04-22 14:52:09.945 | info | starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.sonoff, node: v6.14.1

`

**Comment by volkmydj** [comment]
Hello. I have a similar problem


sonoff.0 | 2018-04-24 16:48:31.663 | info | Client [Kitchen] reconnected
-- | -- | -- | --
sonoff.0 | 2018-04-24 16:48:30.489 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:48:19.675 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:48:19.669 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:48:18.488 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:48:07.689 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:48:07.675 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:48:06.489 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:47:55.634 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:47:55.632 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:47:54.494 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:47:43.802 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:47:43.802 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:47:43.801 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:47:31.566 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:47:31.558 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:47:30.490 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:47:19.663 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:47:19.555 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:47:18.488 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:47:07.564 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:47:07.554 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:47:06.488 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:46:55.566 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:46:55.553 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:46:54.485 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:46:43.564 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:46:43.552 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:46:42.481 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:46:31.559 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:46:31.551 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:46:30.479 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:46:19.558 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:46:19.549 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:46:18.478 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:46:07.504 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:46:07.497 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:46:06.481 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:55.469 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:45:55.460 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:45:54.478 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:43.384 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:45:43.364 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:45:42.481 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:31.356 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:45:31.350 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:45:30.476 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:19.296 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:45:19.291 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:45:18.477 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:07.296 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:45:07.283 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:45:06.476 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:45:00.184 | warn | Unknown mapping for "POWER"
sonoff.0 | 2018-04-24 16:44:55.273 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:44:55.268 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:44:54.476 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:44:43.284 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:44:43.277 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:44:42.483 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:44:31.251 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:44:31.231 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:44:30.478 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:44:19.247 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:44:19.233 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:44:18.476 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:44:07.254 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:44:07.236 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:44:06.473 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:43:55.270 | info | Client [Bedroom] reconnected
sonoff.0 | 2018-04-24 16:43:55.169 | info | Client [Kitchen] reconnected
sonoff.0 | 2018-04-24 16:43:54.481 | info | Client [Living room] reconnected
sonoff.0 | 2018-04-24 16:43:43.183 | info | Client [Bedroom] reconnected
