### ISSUE TITLE
[Add Support] Analog Input A0

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.sonoff#43]
Hello,
es gibt bei Tasmota die Möglichkeit den Analog Input A0 auszugeben.
Der Output (z.B. eines Regensensors) würde mein ioBroker sehr gerne verarbeiten.
Folgender Output ist relevant:
MQT: tele/sonoff/SENSOR = {"Time":"2018-05-08T11:06:33","ANALOG":{"A0":485}}
![analog](https://user-images.githubusercontent.com/26110738/39751790-98df5730-52b9-11e8-920e-343c49b4ca01.JPG)

Ich hoffe auch für diese Implementierung besteht bei Gelegenheit die Zeit :-)
Grüße Fabian

**Comment by gemu2015** [comment]
geht in meiner Version => https://github.com/gemu2015/ioBroker.sonoff

wurde in 5.13 geändert
Habe fast alle Neuerungen von 5.13 eingebaut

(z.B timer1-16, HSBColor,Channels etc)

**Comment by gemu2015** [comment]
um in Zukunft nicht wegen jedem Sensor ein Update zu machen, habe ich ein "auto generate" für tele Sensor Objekte eingebaut. Damit sollten alle von Tasmota erzeugten Sensoren angezeigt werden.

Bitte mal testen damit ich nach Verifizieren einen PR machen kann

https://github.com/gemu2015/ioBroker.sonoff

**Comment by FabianHM** [comment]
Hallo gemu2015,
freut mich sehr, dass der anlaoge Input nun auch berücksichtigt wird und besonders die langfristige, automatiserte Aufnahme neuer Objekte klingt spannend!
Habe leider die nächsten Tage keine Gelegenheit auf meine Umgebung zuzugreifen, gebe feedback wenn ich zurück bin...
Gruß
Fabian

**Comment by gemu2015** [comment]
Hier noch ein paar Infos zum Testen der neuesten Version:
Es wird ein Objekt setup/flags erzeugt:

Mit Flags kann man die automatische Erzeugung von Tasmota Objekten steuern:

flags=1 => tele/sonoff/SENSOR Objekte werden automatisch erzeugt (nur lesen)
flags=2 => tele/sonoff/STATE Objekte werden automatisch erzeugt (nur lesen)
flags=4 => stat/sonoff/RESULT Objekte werde automatisch erzeugt (lesen und schreiben)

natürlich auch Kombinationen z.B. 7 für alle erzeugen

Die Objekte werden erzeugt wenn das entsprechende Tasmota MQTT Telegramm das erste Mal empfangen wurde. Die tele und stat MQTT Meldungen erfolgen meist automatisch, die RESULT MQTTs kann man durch Eingabe des Befehls  in der Tasmota Konsole erzeugen 

Gruß Gerhard

**Comment by gemu2015** [comment]
Hallo Fabian,

Nur lesen heisst dass du die Objekte nur auslesen nicht setzen bzw. schreiben kannst.

Sensoren werden z.B nur gelesen.  POWER oder DIMMER  sind Beispiele für lesen und schreiben, dort wird etwas in Tasmota verstellt, geschrieben.

Ich habe die 3 telegramme getrennt weil die meisten nur Objekte für Sensoren brauchen, also 1

da die Anzahl der verwalteten Objekte den Speicherbedarf beeinflusst sollte man nicht mehr Objekt als nötig erzeugen.   


Mit dem WemosD1 habe ich keinerlei Probleme auch nicht mit den ganz neuen Tasmota releases.

Wie hast du denn das Modul in Tasmota Platformio.ini konfiguriert ?

dort wurde ja einiges verändert mit der release 5.14.

du musst z.B. das board auf => board = d1_mini stellen

auch würde ich die konfig komplett löschen in dem du die  cfg_holder id veränderst (dort einfach den hex wert ändern)

#define CFG_HOLDER             0x29161210

allerdings hatte ich gelegentlich das Problem das erst nach einem Power on reset MQTT richtig funktioniert hat.

VG Gerhard

**Comment by Kasperle99** [comment]
Hallo Gerhard,
auch ich habe nochmal testet.
Wemos D1 mini mit Tasmota 6.0.0a. 
Analog ok.
Sensor AM2301 auf GPIO14 angeshlossen.
Tasmota GUI zeigt Werte für Analog0, Temperatur und Feuchtigkeit an, In der Console vom Wemos werden die Werte auch angezeigt.
------
15:58:10 MQT: tele/sonoff/SENSOR = {"Time":"2018-06-03T15:58:10","ANALOG":{"A0":327},"AM2301":{"Temperature":23.4,"Humidity":69.9},"TempUnit":"C"}
-------

Einstellung Flags am Sonoff-Adapter Standart 0
Es wurde nur das Analog Objekt erstellt. Opjekte für den Sensor an GPIO14 nicht.

Fags auf 7 gesetzt:
Objekt Temperatur wurde erstellt, aber keine Werte, nur die Einheit.

Wemos mehtfach neu gestartet, keine Änderung.

Analog geht, Temperature und Humidity nicht.

Gruß
Udo

**Comment by gemu2015** [comment]
Hallo Udo,

die Werte Temperature und Humidity sind schon lange in der Liste (kein auto generate) und sollten eigentlich erzeugt werden.  An dem Standard Mechanismus habe ich nichts geändert.

TempUnit dagegen ist ein "auto generate"

was zeigt das iobroker.sonoff log ? habe eine Meldung eingebaut die das Erzeugen neuer Objekte loggt.

Adapter neu starten ? 

Gruß Gerhard

**Comment by Kasperle99** [comment]
Hallo Gerhard,
ok. Möchtest Du normales Log, oder Debug-Log

Normales Log nach restart Sonoff-Adapter.

sonoff.0	2018-06-03 17:01:09.807	info	Client [Touch-T2-Ku] connected
sonoff.0	2018-06-03 17:01:09.584	info	Client [POW-GS] connected
sonoff.0	2018-06-03 17:01:09.584	info	Client [POW-TR] connected
sonoff.0	2018-06-03 17:01:09.584	info	Client [Touch-T2-Wo] connected
sonoff.0	2018-06-03 17:01:09.584	info	Client [S20-Ku] connected
sonoff.0	2018-06-03 17:01:09.583	info	Client [D1-mini-Test-1] connected
sonoff.0	2018-06-03 17:01:09.582	info	Client [4chpro-Solar] connected
sonoff.0	2018-06-03 17:01:09.582	info	Client [POW-WA] connected
sonoff.0	2018-06-03 17:01:09.501	info	Client [Touch-T2-SZ] connected
sonoff.0	2018-06-03 17:01:02.272	info	Starting MQTT authenticated server on port 1883
sonoff.0	2018-06-03 17:01:02.214	info	starting. Version 2.1.3 in /opt/iobroker/node_modules/iobroker.sonoff, node: v6.14.2

Leider nicht viel zu sehen. Nach restart Wemos D1 Mini kommt nur Reconnect.

Wemos D1Mini Objekte nochmal gelöscht, und siehe da, jetzt sind die Objekte erstellt wurden.
Keine Ahnung warum jetzt auf einmal, hatte vorher auch schon ein paar mal die Objekte gelöscht.

hier das log

sonoff.0 | 2018-06-03 17:16:41.129 | info | new object created: sonoff.0.D1-mini-Test-1.AM2301_Humidity
-- | -- | -- | --
sonoff.0 | 2018-06-03 17:16:41.125 | info | new object created: sonoff.0.D1-mini-Test-1.AM2301_Temperature
sonoff.0 | 2018-06-03 17:16:41.125 | info | new object created: sonoff.0.D1-mini-Test-1.ANALOG_A0
sonoff.0 | 2018-06-03 17:16:41.066 | info | new object created: sonoff.0.D1-mini-Test-1.Wifi_RSSI
sonoff.0 | 2018-06-03 17:16:41.065 | info | new object created: sonoff.0.D1-mini-Test-1.Uptime
sonoff.0 | 2018-06-03 17:16:41.056 | info | new object created: sonoff.0.D1-mini-Test-1.Time

Ist sehr Merkwürdig, ich werde es  noch mal weiter beobachten, aber sonst Danke für die schnelle Hilfe.

Gruß
Udo

**Comment by Chaot1** [comment]
Ich habe das jetzt mit einem Sonoff DEV und einem BME680 am laufen.
Werte werden erst nach dem zweiten Empfang des MQTT Telegramms korrekt angezeigt.
Ist nicht schlimm, aber man sollte das wissen sonst such man eventuell Fehler die gar nicht existieren.

Nach dem Erkennen habe ich im RAW die Zeile 
` "unit": "kOhm",` 

einfegügt. 
Ich denke das sollte so funktionieren.

**Comment by FabianHM** [comment]
@gemu2015: 
Hallo Gerhard,
nimmst Du die Änderungen nun in der offiziellen Version 2.1.4 auf?

Grüße
Fabian

**Comment by FabianHM** [comment]
Dankeschön 👍

**Comment by FabianHM** [comment]
@gemu2015 
Hallo Gerhard,

nachdem ich heute endlich einen neuen Sensor erhalten habe ist mir aufgefallen, dass ein Wert nicht übertragen wird. Es handelt sich um den **"UvIndex":0.15**
Tasmota sendet den Wert:
MQT: tele/sonoff/SENSOR = {"Time":"2018-06-12T19:26:13","AM2301":{"Temperature":22.0,"Humidity":56.8},"BH1750":{"Illuminance":935},"VEML6070":{"UvLevel":40},"SI1145":{"Illuminance":285,"Infrared":544,"UvIndex":0.15},"TempUnit":"C"}

Der UvIndex erscheint trotz mehrfachen Neustarts nicht im ioBroker:
![screen](https://user-images.githubusercontent.com/26110738/41309418-0ade7894-6e7f-11e8-8697-2cc79d661e0f.JPG)
Woran kann es liegen?
Viele Grüße
Fabian

**Comment by gemu2015** [comment]
Hallo Fabian

Fehler behoben!

VG Gerhard

**Comment by FabianHM** [comment]
Hallo Gerhard,

prima, jetzt werden alle Attribute des Sensors übertragen.
Danke für die Korrektur,
VG Fabian
