### ISSUE TITLE
4CH pro MQTT permanatly reconection 

### ISSUE THREAD

**Issue by 123dabei** [ioBroker/ioBroker.sonoff#44]
Hi, 
I flashed me CH4 pro with 5.12 and 5.14, but on bouth firmware ich have an issue (see screenshot) 
![fehlermeldung](https://user-images.githubusercontent.com/39468840/40283781-35ac9e28-5c84-11e8-94ea-138ebbfa4a63.JPG)

The Information like PW an User and IP of the Pi ar definetly correct
![iobroker](https://user-images.githubusercontent.com/39468840/40283826-f63ed7e6-5c84-11e8-810c-1d44b59d7552.JPG)
![sonoff 4ch pro](https://user-images.githubusercontent.com/39468840/40283827-f671e604-5c84-11e8-957b-6506464ab043.JPG)

Can someone help me

**Comment by GermanBluefox** [comment]
Very old topic, so close.
