### ISSUE TITLE
Sonoff-Tasmota  ADC input in mqtt topic

### ISSUE THREAD

**Issue by Sergio-tix** [ioBroker/ioBroker.sonoff#46]
Hello!
I'm using ESP-12S with firmware Sonoff-Tasmota. I'm faced with a problem, is not displayed in MQTT ADC input. Not yet displayed digital input.
![tasmota01](https://user-images.githubusercontent.com/18720428/41254977-ca9a6c72-6dcd-11e8-9639-378514fde4c3.PNG)
![tasmota02](https://user-images.githubusercontent.com/18720428/41254985-cdc29172-6dcd-11e8-9347-cd8b54085ffd.PNG)
![tasmota03](https://user-images.githubusercontent.com/18720428/41254988-cfff1e4c-6dcd-11e8-80fc-59774f840169.PNG)
P.S. Excuse me for my google translate.
P.S.S. You need some kind of data from my device? How can I get them for you?

**Comment by gemu2015** [comment]
Buttons are NOT transmitted via MQTT, only switches and POWER (relays) operated by Buttons
ANALOG should work in newest adapter version.

**Comment by Sergio-tix** [comment]
I learned that now in Sonoff-Tasmota, there are RULES.
Rules allow you to use a switch or button to transmitted message via MQTT. 
Each switch(button) can send an individual message.
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#2-execute-any-mqtt-message-when-a-button-is-pressed
I made this configuration:
×××××
rule on Switch1#state do publish cmnd/Switch1/power %value% endon on Switch2#state do publish cmnd/Switch2/power %value% endon on Switch3#state do publish cmnd/Switch3/power %value% endon on Switch4#state do publish cmnd/Switch4/power %value% endon
×××××
But I do not see messages in the driver.
I do not know yet what's wrong. I'm trying to change the firmware and rules.
Your driver is able to receive such messages?

**Comment by gemu2015** [comment]
you should enable auto detection in setup for unknown keywords

and send e.g. => publish tele/sonoff/STATE {"Switch1": %value%}

**Comment by Sergio-tix** [comment]
in Russian:
Если использовать обычный чип ESP8266, как делаю я, с прошивкой Sonoff-Tasmota, то настройки правила должны выглядеть так:
`rule on Switch1#State do publish tele/sonoff/STATE {"Input1":%value%} endon on Switch2#State do publish tele/sonoff/STATE {"Input2":%value%} endon on Switch3#State do publish tele/sonoff/STATE {"Input3":%value%} endon on Switch4#State do publish tele/sonoff/STATE {"Input4":%value%} endon`
В консоли прошивки Sonoff-Tasmota нужно ввести выше указанное правило, после чего включить правило командой `rule1 1` и выключить стандартный топик командой `SwitchTopic 0`
Задать настройку свитчу(входу) командой `SwitchMode1 2` для первого входа, `SwitchMode2 2` для второго, и т.д.
Конфигурация в настройках такая:
![st](https://user-images.githubusercontent.com/18720428/43414830-9dbd8096-943c-11e8-89ee-90a95a1775c6.PNG)
P.S. Перед прошивкой скетча в Arduino IDE, в файле `user_config.h` раскоментировать строку `#define USE_CONFIG_OVERRIDE`. Файл `user_config_override_sample.h` переименовать в `user_config_override.h`.
Теперь в драйвере ioBroker.sonoff установить Auto creation of states для tele/STATE, и получим 4 входа и 4 выхода совершенно независимых друг от друга.
![0002](https://user-images.githubusercontent.com/18720428/43415675-e4abff26-943e-11e8-8e25-2124782a19d4.PNG)
Всё работает, всем спасибо!

**Comment by katodo** [comment]
Can you tell me something about the GUI in this post? Where can I find some information?

**Comment by Sergio-tix** [comment]
What exactly are you interested in?

**Comment by katodo** [comment]
The GUI visible in this post is a tool of ioBroker ? Or... better... where can I find it?

**Comment by Sergio-tix** [comment]
Here GUI Sonoff-Tasmota(vertical screen) and GUI iobroker (horizontal screen).
