### ISSUE TITLE
DS18B20 Temperature will not be shown

### ISSUE THREAD

**Issue by SEWADE** [ioBroker/ioBroker.sonoff#47]
Hi, 

I've a connect DS18B20 to a Sonoff Basic.
Under the object the temperature will not be shown. I have restarted the adapter several time, but it doesn't help.

The sonoff is sending:

`10:03:24 MQT: tele/sonoff/STATE = {"Time":"2018-06-15T10:03:24","Uptime":"0T00:10:14","Vcc":3.208,"POWER1":"OFF","Wifi":{"AP":1,"SSId":"S04_mesh","RSSI":84,"APMac":"EC:08:6B:F9:07:94"}}
10:03:24 MQT: tele/sonoff/SENSOR = {"Time":"2018-06-15T10:03:24","DS18B20":{"Temperature":0.0},"TempUnit":"C"}`

The iobroker is is receiving the temperature:

sonoff.0 | 2018-06-15 11:03:24.811 | debug | stateChange sonoff.0.Sonoff_Basic_1.DS18B20_Temperature:  {"val":0,"ack":true,"ts":1529053404803,"q":0,"from":"system.adapter.sonoff.0","lc":1529052803660}
-- | -- | -- | --
sonoff.0 | 2018-06-15 11:03:24.792 | debug | [Sonoff_Basic_1] Received: tele/sonoff/SENSOR = {"Time":"2018-06-15T10:03:24","DS18B20":{"Temperature":0.0},"TempUnit":"C"}
sonoff.0 | 2018-06-15 11:03:24.772 | debug | stateChange sonoff.0.Sonoff_Basic_1.Wifi_RSSI:  {"val":84,"ack":true,"ts":1529053404757,"q":0,"from":"system.adapter.sonoff.0","lc":1529053404757}
sonoff.0 | 2018-06-15 11:03:24.771 | debug | stateChange sonoff.0.Sonoff_Basic_1.POWER1:  {"val":false,"ack":true,"ts":1529053404755,"q":0,"from":"system.adapter.sonoff.0","lc":1529052446688}
sonoff.0 | 2018-06-15 11:03:24.758 | debug | stateChange sonoff.0.Sonoff_Basic_1.Vcc:  {"val":3.208,"ack":true,"ts":1529053404748,"q":0,"from":"system.adapter.sonoff.0","lc":1529052453690}
sonoff.0 | 2018-06-15 11:03:24.737 | debug | [Sonoff_Basic_1] Received: tele/sonoff/STATE =  {"Time":"2018-06-15T10:03:24","Uptime":"0T00:10:14","Vcc":3.208,"POWER1":"OFF","Wifi":{"AP":1,"SSId":"S04_mesh","RSSI":84,"APMac":"EC:08:6B:F9:07:94"}}

![deepinbildschirmfoto_bereich auswahlen_20180615111158](https://user-images.githubusercontent.com/31615609/41460431-01af35b4-708d-11e8-88e0-5288651f6e2d.png)

`

Regards
Sebastian

**Comment by GermanBluefox** [comment]
Sorry I cannot reproduce you error. I even built your log into tests and everything is OK.
Sure that you updated the browser? F5?
