### ISSUE TITLE
autocreate options not showing up in adapter config

### ISSUE THREAD

**Issue by gemu2015** [ioBroker/ioBroker.sonoff#48]
adapter config not showing autocreate options

**Comment by GermanBluefox** [comment]
Can you please paste here the values of mqtt topics for colours. With hue,
saturation, ww, cw... so I can create the tests.

Btw I fixed it yesterday. Have you tested the the newest version?

вт, 19 июн. 2018 г., 7:15 gemu <notifications@github.com>:

**Comment by gemu2015** [comment]
06:39:33 MQT: tele/sonoff/STATE = {"Time":"2018-06-19T06:39:33","Uptime":"0T23:47:32","Vcc":3.482,"POWER":"OFF","Dimmer":100,"Color":"000000FF","HSBColor":"0,0,0","Channel":[0,0,0,100],"Scheme":0,"Fade":"OFF","Speed":4,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"WLAN-7490","RSSI":50,"APMac":"34:31:C4:C6:EB:0F"}}


yes, i use the newest version. i installed via github and to be sure i uploaded again with iobroker upload sonoff

**Comment by gemu2015** [comment]
tasmota sends and receives color per default  in 3 formats 

3 hex bytes => RGB only
4 hex bytes => RGBWW
5 hex bytes => RGBCWWW

so rgb, cw and ww are coded into color and from 5.12 into channels

hue and saturation are not sent by tasmota but in hsb composite (from tasmota 5.12 up)

hue and saturation write only states are converted to color and transmitted as color via MQTT

**Comment by gemu2015** [comment]
exception =>
xObj = addObject('WW.level', client, prefix, path);

changing ww to ww.level inconsistent 
if changing, should change all instances also in datapoints and also should change cw to cw.level

i would prefer not to change the name because level is indicated in role already

still no adapter autocrate config!
i am sticking to admin 2.09. may this be a reason ?

**Comment by GermanBluefox** [comment]
Yes. 2.0.9 has no new settings.

**Comment by gemu2015** [comment]
OK, updated to admin 3  (sadly does not work with safari, only with chrome)

but config  settings not updated in server.js  => eg. adapter.config.TELE_SENSOR always false

**Comment by gemu2015** [comment]
sorry, still not fixed => adapter.config.TELE_SENSOR always false

**Comment by gemu2015** [comment]
sorry accidentally closed

index_m.html

"user">For tele/SENSOR
to
"TELE_SENSOR">For tele/SENSOR

**Comment by gemu2015** [comment]
after correcting index_m.html everything works as expected

i would change the readme like this =>

##Autocreation of objects
In the web config you can determine which MQTT telegrams create new objects not in default datapoints

TELE_SENSOR creates objects from tele/xxx/SENSOR telegrams
TELE_STATE creates objects from tele/xxx/STATE telegrams
STAT_RESULT creates objects from stat/xxx/RESULT telegrams

usually TELE_SENSOR should be sufficiant for most users_
   

## Flags for ledcontrollers
The mode states will be created only if device has one of the states:
- 'Red', 'Green', 'Blue', 'WW', 'CW', 'Color', 'RGB_POWER', 'WW_POWER', 'CW_POWER', 'Hue', 'Saturation'

States:
- modeLedExor - exor for white LEDs and color leds => if the white LEDs are switched on, color LEDs are switched off and vice versa (default true)
- modeReadColors - allow for color read from MQTT (default false)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/41812337-67b12b20-7721-11e8-8d5a-89df589ab9f8.png)

![image](https://user-images.githubusercontent.com/4582016/41812324-42841862-7721-11e8-925d-adc99b326fb4.png)

**Comment by GermanBluefox** [comment]
Ich habe aber nichts im index_m geändert? Funktioniert jetzt?

**Comment by gemu2015** [comment]
Alles OK mit aktueller Version!!!
