### ISSUE TITLE
No Update on sonoff.0.Highboard-Long.alive

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.sonoff#50]
I updated the adapter to 2.2.2 - since than i don´t have any "alive" updates. 
Tested on devices with Tasmota 5.11.1 (Basic) and 5.14.0 (Dual)

**Comment by GermanBluefox** [comment]
Please test 2.3.0

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.sonoff/issues/81
