### ISSUE TITLE
Counter transmission format has changed since tasmota v5.14.0

### ISSUE THREAD

**Issue by Tingeltangelbobi** [ioBroker/ioBroker.sonoff#51]
Counters are not displayed.
Since version 5.14.0 the transmission format has changed: "COUNTER":{"C1":251,"C2":0,"C3":0,"C4":0}
In version 5.11.0: "Counter1":0,"Counter2":0,"Counter3":0,"Counter4":0

Can you please update the code

**Comment by gemu2015** [comment]
did you enable auto detection of unknown keywords in adapter setup ?

this should solve it

**Comment by Tingeltangelbobi** [comment]
no. where can I find this option?
under "Instances -> sonoff -> Settings" I could not find this option.

**Comment by gemu2015** [comment]
you must use the latest version of the adapter => 2.2.2 for auto creation of unknown objects

**Comment by Tingeltangelbobi** [comment]
2.2.2 is already installed
admin adapter v 2.4.9
js-controller v 1.4.2

but I can't find the option

**Comment by gemu2015** [comment]
ok, the new auto create option is only supported with admin 3!

**Comment by Tingeltangelbobi** [comment]
sorry, I mistyped, I mean ioBroker.admin 3.4.9

**Comment by gemu2015** [comment]
ok, then you should see in adapter instance => sonoff settings

"automatische Erstellung von Zuständen"

**Comment by Tingeltangelbobi** [comment]
the option is not displayed

![sonoff](https://user-images.githubusercontent.com/35076365/43306904-ff268084-917c-11e8-9aef-f2c5cbc74349.PNG)

**Comment by gemu2015** [comment]
ok, reupload the adapter, if still not working delete and reinstall

**Comment by Tingeltangelbobi** [comment]
ok now the option is there.
but all objects and their history have been deleted.
The records of one year have been deleted.

**Comment by Apollon77** [comment]
I think the records are still there. When you still know the old ID names then update your history/sql/influxdb adapter to latest version and use alias feature to store new alues at the old ids. works also for selections

**Comment by gemu2015** [comment]
all objects will be created again, BUT some as the ip are only created on a new start of the tasmota devices.

history will reappear if the objects a recreated and you set the history flag again.

All history files remain there and are NOT deleted

**Comment by Tingeltangelbobi** [comment]
thank you very much. It's working.
the history data has been transferred.
