### ISSUE TITLE
send cmnd to Sonoff via iobroker sonoff

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.sonoff#55]
hey,

im using IOBroker sonoff addon and want to send a cmnd to my RFBridge.

when i try to send it via mqtt client with "cmnd/Bridge_433MHZ/rfcode 5526835"
it doesen't work.
only when i connect the RFBridge to mqtt Server and send command "cmnd/Bridge_433MHZ/rfcode 5526835"

what can i do by using sonoff addon?

thanks for help

**Comment by LaLinea** [comment]
maybe the same as this: https://github.com/ioBroker/ioBroker.sonoff/issues/69
