### ISSUE TITLE
Reduce log level from WARN to DEBUG for invalid ping request

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.sonoff#56]
After reconnects of sonoff with ioBroker there occurs following line in log file:
Old client Stehlampe with secret 1534742437089_8715 sends pingreq. Ignore! Actual secret is 1534747629125_6065

Actually the log level ist set to WARN; but DEBUG level is enough, cause this has no impact on the sonoff handling.

**Comment by GermanBluefox** [comment]
Please test 2.3.0
