### ISSUE TITLE
Alive State is not updated, if sonoff no longer available 

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/ioBroker.sonoff#58]
I have a SOnOff, which are not always reachable. 
I want to react on sonoff.0.XXXX.alive in my Script, but if the SOnOff disconnected, the state will not be updated.

I fixed it, by add "updateAlive(client, false);"
in the function clientClose before updateClients(); in Line 1250

Could you please add this general to your code?

Thank you, also for your great Adapter
Dirk

**Comment by Marty56** [comment]
@dirkhe: I have tested your fix and it is working nicely.
The alive object is updated with the polling interval.

It would be great if it is also updated when a command is sent to the sonoff device and this command is not acknowledged in a reasonable short amount of time by the sonoff device. This would improve the real time capability and would resemble a kind of  Homematic "unreach" data point which I find very useful for error handling.

**Comment by FabianHM** [comment]
@dirkhe Hallo Dirk,
um das Problem mit dem nicht aktualisierten Status zu beheben habe ich versucht die von Dir beschriebene Funktion aufzunehmen. Stimmt Zeile 1250 wirklich, ich hätte eher Zeile 1259 vermutet?
Anbei die von umgesetzte Änderung, ist die Position korrekt?

![Function clientClose](https://user-images.githubusercontent.com/26110738/57981801-ecbdd100-7a3c-11e9-8dfc-6e05caa17cb2.JPG)
Muss ich nun noch die Besitzer Rechte anpassen?
![server js Berechtigungen](https://user-images.githubusercontent.com/26110738/57981838-48885a00-7a3d-11e9-9f07-c9f9c460eaef.JPG)


Vielen Dank vorab,
Grüße
Fabian

**Comment by dirkhe** [comment]
Die neue Zeile ist schon richtig, ich habe extra versucht, die Stelle zu beschreiben, weil die Zeilennummer sich ja immer ändern kann.
Ob das "Client Zeitüberschreitung" so direkt als intervall genomen wird, kann ich dir gerade gar nicht sagen, aber das könnte schon sein. Das Problem war ja, dass der Adapter zwar gemerkt hatte, dass der client weg war, er hatte nur den entsprechenden Datenpunkt nicht angepasst, mehr macht meine Zeile da nicht.
Wenn du nicht schreiben kannst, musst du die rechte ggf. anpassen oder per sudo ändern

**Comment by FabianHM** [comment]
Hat funktioniert, Danke für den tollen Tipp!

**Comment by GermanBluefox** [comment]
Please test 2.3.0

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.sonoff/issues/81

**Comment by Marty56** [comment]
Funktioniert. Super, danke für den Fix.
