### ISSUE TITLE
Auto generate Objects - Problem with SDS0x Sensor

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.sonoff#59]
Hallo @gemu2015 
ich habe nun die neue Version von Tasmota verwendet.
Es gab u.a. eine Änderung zur Unterstützung der SDS011 Partikelsensoren.
Der MQTT String von Tasmota lautet:
MQT: tele/sonoff/SENSOR = {"Time":"2018-09-23T18:55:04","SDS0X1":{"PM2.5":1.1,"PM10":3.4}}
Im ioBroker kommen die Werte leider nicht wie erwartet an:
![wemos3](https://user-images.githubusercontent.com/26110738/45930591-67902400-bf62-11e8-90e3-24b213c61c3d.JPG)
Für die Partikelgröße 2.5qm wird leider ein Ordner angelegt, der Nachkommanteil "5" wird als Ordnername verwendet. Mir ist es nicht gelungen, durch Änderungen der drei Optionen zum "auto generate" das Problem zu lösen.

Danke für Deine Hilfe vorab.
Grüße
Fabian

**Comment by gemu2015** [comment]
Hallo Fabian,

Da diese Bezeichnungen (PM2.5 und PM10) bereits in der vordefinierten Liste sind, hat das Problem nichts mit auto generate zu tun.

Habe das kurz mal ausprobiert und es scheint dass der Fehler in "setForeignObject" steckt.  Dort wird offensichtlich der Punkt im Namen falsch interpretiert und ein "Ordner" erzeugt.

Hier kann aber sicher bluefox weiterhelfen. Ich habe gerade keine Zeit da ich für 3 Wochen in Urlaub fahre.

Nur zur Info => man kann jede MQTT Message in einer Tasmota Konsole mit publish absetzen :

publish tele/sonoff/SENSOR {"Time":"2018-09-23T18:55:04","SDS0X1":{"PM2.5":1.1,"PM10":3.4}}

Achtung das "=" Zeichen nach SENSOR weglassen ! 

Falls du Tasmota selbst kompilierst könntest du dort natürlich vorerst auch den Namen PM2.5 patchen z.B als PM2_5

Grüße

Gerhard




> Am 23.09.2018 um 18:59 schrieb FabianHM <notifications@github.com <mailto:notifications@github.com>>:
> 
>  tele/sonoff/SENSOR = {"Time":"2018-09-23T18:55:04","SDS0X1":{"PM2.5":1.1,"PM10":3.4}}

**Comment by FabianHM** [comment]
Danke Gerhard für die Analyse des Themas :+1: 

Hallo @GermanBluefox ,
kannst Du die von gemu2015 angesprochene ggf. erforderliche Anpassung vielleicht durchführen?

> Da diese Bezeichnungen (PM2.5 und PM10) bereits in der vordefinierten Liste sind, hat das Problem nichts mit auto generate zu tun. Habe das kurz mal ausprobiert und es scheint dass der Fehler in "setForeignObject" steckt.  Dort wird offensichtlich der Punkt im Namen falsch interpretiert und ein "Ordner" erzeugt.

Danke und Grüße
Fabian

**Comment by GermanBluefox** [comment]
Ich verspreche nicht, dass es bald passiert :(

**Comment by gemu2015** [comment]
Hallo Fabian,

Das Problem liegt nicht an setForeignObject sondern nur an der Anzeige der Objekte. Das Object wird richtig angelegt und du kannst es mit der Angabe des richtigen Objektbezeichners in VIS anzeigen, also z.B. sonoff.0.DVES_008ADB.SDS0X1_PM2.5
 
Gruß Gerhard

**Comment by FabianHM** [comment]
Workaround ist okay

**Comment by AndreasB71** [comment]
Gibt's da mitlerweile schon ne Lösung? Hab das gleiche Problem nun beim einlesen der Daten von einem PMS5003.

Gruß
Andreas

**Comment by xxcite** [comment]
Hallo,

ich habe dieselben Probleme mit einem PMS5003 Sensor und bisher keine Lösung gefunden. Auch für das von @gemu2015 vorgeschlagene Kompilieren von Tasmota und der Umbenennung habe ich leider keinen Anhaltspunkt gefunden, wie und wo genau da was geändert werden muss.

Danke
