### ISSUE TITLE
ioBroker.sonoff

### ISSUE THREAD

**Issue by 3wisky** [ioBroker/ioBroker.sonoff#6]
Adapter does not read the Tasmota/ sonoff T1, T2, T3 properly. It don,t see all the switches, just one and does not react on state changes. IOBroker.MQTT is working oke with T1,T2, T3.

Grtz.

**Comment by GermanBluefox** [comment]
What is T1, T2, T3?
As you can see from https://github.com/ioBroker/ioBroker.sonoff#usage only specific topics are supported.

If you want that Tx will be supported, you should provide debug information for me. And Tx must be a standard, so it will be valid not only for you.

**Comment by 3wisky** [comment]
I mean T1 1ch, T1 2ch, T3 3ch. But after a few times toggle the switches they show up. thus it's working.
