### ISSUE TITLE
Sonoff Touch / Tasmota Button Hold

### ISSUE THREAD

**Issue by WahlFisch91** [ioBroker/ioBroker.sonoff#60]
Hi,
I'd would be nice to have support for the Button Hold feature of Tasmota.
If i hold the button on my touch for about 2 seconds, i get an mqtt message "cmnd/hold_TEST-SONOFF/POWER1 = HOLD"
Sadly the sonoff adapter does not recognize this message.

greetings,

**Comment by MubiTec** [comment]
That would be great for me, too!

**Comment by pandel** [comment]
+1

See for details, if that helps: https://github.com/arendst/Sonoff-Tasmota/wiki/Control-other-devices

**Comment by WahlFisch91** [comment]
I know that.
But this solution is for the MQTT Adapter and not for the SONOFF Adapter.

**Comment by pandel** [comment]
It wasn't meant for you, more for the dev ;-)

**Comment by mczeus** [comment]
das wäre richtig hilfreich wenn es den Datenpunkten geben würde!

**Comment by GermanBluefox** [comment]
How this HOLD should work? 
Will it be sent after the button is released some another value?

**Comment by GermanBluefox** [comment]
That means, we need additional state POWER1_HOLD that could be true and false.
What will come when you release the button?
`"cmnd/hold_TEST-SONOFF/POWER1 = UNHOLD"` ?

**Comment by MubiTec** [comment]
@GermanBluefox I think this issue can be closed. The hold function works with "button_action" as part of multipress function, at one press it displays "single", at 2 presses "double" and on hold "hold". So everything should be fine
