### ISSUE TITLE
Objects under sonoff.0 are not created anymore after manual deleting

### ISSUE THREAD

**Issue by braintr84** [ioBroker/ioBroker.sonoff#61]
Hi, i currently use a sonoff classic module and an arilux-lc01 rgb wifi adapter. 

I tryed both, tasmota and espurna firmwares. Everytime i used a different firmware, i also deleted the objects that were created in previouse versions. 

Now if i add one of these two controlers, there will only be "alive" states created, but no further datapoints like rgb_red, rgb_blue for example.

i also tried to use different credentials, reinstallt the sonoff mqtt adapter, reconfigure/reset/reflash mqtt configuration of my modules, but nothing works. 

why is the adapter not recreating the objects? is it possible to edit the subscriber list? 

Here is a screenshot of how both modules look now under objects
![unbenannt](https://user-images.githubusercontent.com/44327780/47260560-33a31280-d4be-11e8-8884-b5808f5741cc.JPG)

**Comment by GermanBluefox** [comment]
Activate autocreation in cofnig
