### ISSUE TITLE
MagicHome with ESP8285 LED Controller

### ISSUE THREAD

**Issue by resper** [ioBroker/ioBroker.sonoff#62]
Hello,
I use a MagicHome with ESP8285 LED Controller. I flashed it with Sonoff-Tasmota 

https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-with-ESP8285

In ioBroker it shows me only the possibility to turn it on/off. No color changing or dimming.

**Comment by resper** [comment]
Der Controller sendet in Regelmäßigen Abständen folgenden Status:

12:50:18 MQT: home/ikea/small/sonoff/STATE = {"Time":"2018-10-23T12:50:18","Uptime":"1T14:45:26","Vcc":3.237,"POWER":"OFF","Dimmer":100,"Color":"00FF0000","HSBColor":"120,100,100","Channel":[0,100,0,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"BodmannHome","RSSI":90,"APMac":"08:96:D7:81:B8:17"}}

**Comment by B0bb3rl3** [comment]
Du kannst z.B. in der Console mit dem Befehl Color xxxxxxxx (RGBW) bestimmte Farben einstellen. Solltest vorher noch SetOption15 1 in der Konsole eintippen, um vom PWM zum Color Mode zu wechseln.

**Comment by jenshartmann** [comment]
Ich habe genau dasselbe Problem, die Datenpunkte werden nicht automatisch angelegt!

Von Hand kann ich den aber nicht richtig anlegen, so das es mit dem Cloud-Adapter funktioniert.

14:43:37 MQT: wohnzimmer/tele/led/STATE = {"Time":"2018-11-24T14:43:37","Uptime":"0T00:33:26","Vcc":3.221,"POWER":"OFF","Dimmer":50,"Color":"7F7F7F","HSBColor":"0,0,50","Channel":[50,50,50],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"XXXXXXXXX","BSSId":"E0:28:6D:C5:6F:B0","Channel":1,"RSSI":76}}

**Comment by GermanBluefox** [comment]
sonoff adapter expects `tele/SonoffPOW/STATE` also `tele` or `cmnd` at the first place
