### ISSUE TITLE
MagicHome with ESP8285 LED Controller

### ISSUE THREAD

**Issue by resper** [ioBroker/ioBroker.sonoff#63]
Hello,
I use a MagicHome with ESP8285 LED Controller. I flashed it with Sonoff-Tasmota.

https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-with-ESP8285

In ioBroker it shows me only the possibility to turn it on/off. No color changing or dimming.

The other MagicHome controllers working with an other ESP Chip, this Controller seems to work with the adapter.

**Comment by GermanBluefox** [comment]
Duplicate
