### ISSUE TITLE
Broken sensor, tasmota sends "nan" (not a number) and sonoff stops working

### ISSUE THREAD

**Issue by christianh17** [ioBroker/ioBroker.sonoff#65]
Hi!

I just had a broken DHT22 sensor and the tasmota software sent "nan" as value for temperature and humidity. Unfortunately all the message is discarded, in the logfile I see:
`sonoff.0 Cannot parse data "SENSOR": _{"Time":"2018-10-31T11:57:31","SI7021-00":{"Temperature":17.1,"Humidity":70.0},"SI7021-02":{"Temperature":nan,"Humidity":nan},"SI7021-04":{"Temperature":10.0,"Humidity":59.7},"SI7021-05":{"Temperature":8.8,"Humidity":79.3},"TempUnit":"C"}_ - SyntaxError: Unexpected token a in JSON at position 107`
I am not sure where to look for the problem. In my opinion on tasmota side it is better to send an error than sending "0" e.g. so I think it should be fixed on the iobroker-side.

Does anybody have an idea how to fix it? I think the function checkData in server.js should be the right point but I have no experience with js and json, so I did not find the right place to start.

Kind regards
Christian

**Comment by GermanBluefox** [comment]
Please test 2.3.0
