### ISSUE TITLE
Temperatur auslesen

### ISSUE THREAD

**Issue by abuzzeberlin** [ioBroker/ioBroker.sonoff#7]
Hallo
Ich habe ein Sonoff TH mit Temperaturfühler und habe den Sonoff Adapter installiert.Werte werden angezeigt wie z.B Typ IP Adresse usw. Was aber nicht angezeigt wird ist der Temperaturfühler.
Im Forum wurde mir empfohlen diese Info hier zu hinterlassen. 
Folgendes habe Ich aus dem log ausgelesen.

[DVES_9ED4F7] Received: tele/sonoff/SENSOR = {"Zeit":"2017-11-05T14:17:26", "DS18B20":{"Temperatur":53.3}, "TempUnit":"C"}
--

Danke

**Comment by GermanBluefox** [comment]
Bitte die Version 0.3.3 ausprobieren.
Im Forum kann man finden, wie man aus git eine Version installieren kann.
