### ISSUE TITLE
tele/DeviceNAME/STATE wrong

### ISSUE THREAD

**Issue by rocklobster42195** [ioBroker/ioBroker.sonoff#70]
Hi,
I'm using a "SONOFF 4ch" with TASMOTA 6.3.0.15. I can switch all channels from IOBROKER and when I externaly switch a channel, the correct state is shown in OBJECTS. But when IOBROKER receives TELE data the values are all "false"

The SONOFF is sending:
`tele/terrasse/STATE = {"Time":"2018-12-02T13:13:53","Uptime":"0T01:01:07","Vcc":3.423,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"false","POWER2":"false","POWER3":"false","POWER4":"true", ...`

IOBROKER's LOG shows in debug mode:
`redis pmessage io.sonoff.0.* io.sonoff.0.Terrasse.POWER4 {"val":false,"ac ....`
and
`stateChange sonoff.0.Terrasse.POWER4: {"val":false," ...`

What is going wrong here? Thanks for your help.
Boris

**Comment by GermanBluefox** [comment]
Please test 2.3.0
