### ISSUE TITLE
No user friendly "unreachable" state

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.sonoff#72]
Although the sonoff actor provide feedback to iobroker whether the command has been executed it is difficult to hard for the user to react.
I would be worthwhile to have an "unreach" state indicating the loss or error in communication.

see https://forum.iobroker.net/viewtopic.php?f=20&t=19635&p=205487#p205487

this issue to related to https://github.com/ioBroker/ioBroker.sonoff/issues/58

**Comment by GermanBluefox** [comment]
Please use "alive" state for that

**Comment by GermanBluefox** [comment]
Please test 2.3.0
