### ISSUE TITLE
[BUG] Connection wird nicht erneut aufgenommen

### ISSUE THREAD

**Issue by scheilch** [ioBroker/ioBroker.sonoff#75]
[sonoff.log](https://github.com/ioBroker/ioBroker.sonoff/files/2719601/sonoff.log)
[tasmota.log](https://github.com/ioBroker/ioBroker.sonoff/files/2719602/tasmota.log)

Scheinbar sorgt der dynamic Sleep dafür, dass die Connection zum Mqtt Broker abbricht, was eigentlich nicht weiter schlimm ist, denn es wird ja nach der voreingestellt Zeit (50ms - bei mir nur 30ms) wieder versucht die Connection aufzubauen. Dann allerdings kommt es vor, dass der Broker die Connection nicht annimmt. Ich habe mal die Logs aus beiden Modulen (Tasmota/Sonoff) beigelegt. Weiterhin ist der POWER Status nach erfolgreichem Reconnect immer false und bleibt es auch eine Zeit lang, bis mal wieder ein Status Update kommt - oder auch nicht. Es ist ein sehr merkwürdiges Verhalten.

Ich habe mir den Source Code schon mal angeschaut - allerdings ist der (sorry wenn ich das so sagen darf) sehr unübersichtlich. Hilfreich wären sprechende Methodennamen und vor allem keine 100e Zeilen langen  Methoden voller if/then/else - Es wird mich wohl einige Zeit kosten zu durchblicken was da genau passiert.

Weiterhin würde ich das ganze gern mal debuggen - um die Pfade nachverfolgen zu können. Wie kann ich das anstellen? Gibt es die Möglichkeit des Remote Debuggings mit ioBroker? oder muss ich mir debug Ausgaben rein packen - das ist sehr sehr mühselig.

**Comment by DanielWeeber** [comment]
> Weiterhin ist der POWER Status nach erfolgreichem Reconnect immer false und bleibt es auch eine Zeit lang, bis mal wieder ein Status Update kommt - oder auch nicht.

Kann ich nur bestätigen.

**Comment by BigWumpus** [comment]
Ja, habe auch ein issue dazu geöffnet.

**Comment by GermanBluefox** [comment]
If still actual, please reopen
