### ISSUE TITLE
cmnd/xxx/POWER = causes trouble

### ISSUE THREAD

**Issue by BigWumpus** [ioBroker/ioBroker.sonoff#77]
After a connect, TASMOTA send a cmnd with "POWER ="
This is interpretet as "POWER like OFF" as you understand. The POWER-field is empty, so it is not "ON" and  can be read as "OFF" (= not "ON").

So, I switch back to mqtt-adapter.

`17:47:56 MQT: Attempting connection...
17:47:56 MQT: Connected
17:47:56 MQT: tele/Home-Heizung/LWT = Online (retained)
17:47:56 MQT: cmnd/Home-Heizung/POWER = 
17:47:56 MQT: stat/Home-Heizung/RESULT = {"POWER":"ON"}
17:47:56 MQT: stat/Home-Heizung/POWER = ON`

**Comment by GermanBluefox** [comment]
Is fixed
