### ISSUE TITLE
kein Issue.... eher frage

### ISSUE THREAD

**Issue by simpixo** [ioBroker/ioBroker.sonoff#78]
ich erhalte immer wieder die folgende Meldung im Log

old client SONOFF_xxx_xxx with secret 1547485778407_5606 sends pingreq. Ignore! Actual secret is 1547485949421_3119

Was bedeutet diese, oder was kann ich machen das diese nicht erscheint?

**Comment by GermanBluefox** [comment]
That you have two clients with the same client id
