### ISSUE TITLE
iobroker.sonoff.0 - alive (connection) wird nicht aktuallisiert. 

### ISSUE THREAD

**Issue by R-Guhr** [ioBroker/ioBroker.sonoff#81]
Hallo,
bei meinen Sonoff Geräten wird im ioBroker der "alive" State nicht aktualisiert. (Nur bei durchgeführten Adapter-Neustart). Somit kann ich nicht prüfen ob das jeweilige Gerät sich noch im Netzwerk befindet. 

(Was auch im Adapter schön wäre ist, wenn der gesetzte "Friendly Name" mit in den Objekten angezeigt werden würde)

**Comment by FabianHM** [comment]
Habe gerade einen weiteren Issuse zum Thema eröffnet, da ich diesen übersehen hab.
Schade, das Projekt scheint wohl nicht mehr gepflegt zu werden :-(

**Comment by LJSven** [comment]
Ich habe ebenfalls das gleiche Problem.

**Comment by GermanBluefox** [comment]
Please test 2.3.0

**Comment by smartboart** [comment]
looks good....thanks a lot....installed from github, but it is already available in latest...Latest repo shows 2.3.1.Correct?

**Comment by Ahrenfelde** [comment]
Hi,

i seems that the alive state is not working for me. How long does it takes to update the state? I wait for around 5 mins, and iobroker shows alive = true.

Installed is V2.3.2
Tested with Maxio PowerPlug

All other states works like a charm.
