### ISSUE TITLE
Anyone of the project responsibles still alive?

### ISSUE THREAD

**Issue by Pewibe** [ioBroker/ioBroker.sonoff#83]
I like to only know if this project ioBroker.sonoff is being cancelled. Otherwise any estimation for sleeping phase off? This should not be understood as kind of pressure. I only want to know if ioBroker is still a home for Sonoff owners. Thanks!

**Comment by Apollon77** [comment]
Yes it is

**Comment by Apollon77** [comment]
Das Projekt an dem wir alle Arbeiten heisst "ioBroker". In Summe gibt es 267 Adapter und die Core-Entwickler zeichnen sich neben dem Core-System für über 100 dieser Adapter verantwortlich. Leider sind wir immer noch viel zu wenige Entwickler, die auch noch ein Privatleben haben und eigene Projekte. Da kann es durchaus dazu kommen das einzelne Adapter mal etwas aus dem Fokus geraten.
Oft finden sich auch Entwickler die Dinge übernehmen, im Falle von Sonoff bisher noch nicht und ja die Challenge hier ist, dass man die ganze Hardware gar nicht haben kann und damit wird es zu blinder Entwicklung. Das geht generell, aber.
Je mehr Infos in den Tickets ist und umso einfacher es der Entwickler hat es anzupassen desdo schneller kann es auch mal passieren wenn Zeit ist

**Comment by Tobi4** [comment]
Ich hoffe mein Kommentar ist nicht falsch rüber gekommen! Ich bin mehr als zufrieden mit iobroker und seinen Adaptern!!!

Ich hoffe die Infos für die serielle Schnittstelle reichen aus! Falls nicht einfach bescheid geben! 

Würde ganz gerne an meine sonoff t1 ein nextion Display hängen und wollte dafür die serielle Schnittstelle nutzen.

**Comment by Apollon77** [comment]
Alles gut, Ich habe mit dem Adapter noch nichts gemacht, von daher kann ich gerade wenig dazu sagen, sorry

**Comment by PapaSpik3** [comment]
Hallo Apollon77,

vielleicht kannst Du ja erstmal Kleinigkeiten beheben?
Z.B. muss man bei jeder Änderung das Kennwort neu eingeben (habe von JS leider keine Ahnung), bei anderen Adaptern muss man das nicht oder die Warnung für den Schlüssel (gibt es einige Einträge #78 #71 ...) auf Info reduzieren:

lib/server.js Zeile 1601
return adapter.log.**info**(`Old client ${client.id} with secret ${client.__secret} sends pingreq. Ignore! Actual secret is ${clients[client.id].__secret}`);

**Comment by GermanBluefox** [comment]
The iobroker Project has now over 1.5 Millions lines of code. And we are only 4 Core developers and about 20 community adapter developers.
Project is alive, it is just no time for that :)
