### ISSUE TITLE
Sonoff Adapter startet nicht mehr

### ISSUE THREAD

**Issue by Toki99** [ioBroker/ioBroker.sonoff#87]
Der Adapter lässt sich starten beendet sich dann aber wieder. Status rot.

onoff.0 | 2019-04-17 06:30:11.215 | info | terminating
-- | -- | -- | --
sonoff.0 | 2019-04-17 06:30:11.170 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
sonoff.0 | 2019-04-17 06:30:11.170 | error | at _combinedTickCallback (internal/process/next_tick.js:142:11)
sonoff.0 | 2019-04-17 06:30:11.170 | error | at doListen (net.js:1510:7)
sonoff.0 | 2019-04-17 06:30:11.170 | error | at listenInCluster (net.js:1401:12)
sonoff.0 | 2019-04-17 06:30:11.170 | error | at Server.setupListenHandle [as _listen2] (net.js:1360:14)
sonoff.0 | 2019-04-17 06:30:11.170 | error | Error: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2019-04-17 06:30:11.169 | error | uncaught exception: listen EADDRINUSE 0.0.0.0:1883

Danke!

**Comment by skar-cgn** [comment]
I have the same issue, could not find any solution. 
Deleted, reinstalled the adapter several times. Does work with version 2.2.2 oder 2.2.3
I already use the js.controller in version 2.0.29

Any help would be appreciated. 

Thanks
Regards
Skar

**Comment by Apollon77** [comment]
Please use netstat to check which other service uses port 1883. something is blocking the port.

**Comment by skar-cgn** [comment]
For sure mosquitto is already running on this port. I thought this adapter only connects to an existing mqtt instance. 
And it worked before but I must admit, that I did not recognised this behaviour on time, so not sure which changes happened before. But definitively mosquitto was already running before. 
Regards
Skar

**Comment by Apollon77** [comment]
From my knowledge sonoff is opening an own server ... so it should never have worked

**Comment by skar-cgn** [comment]
You are right, no clue why it worked before. Stopping my local mqtt server, now it is working. 
I have some other issues like I do not get message from this instance in an external mqtt client, but I need to figure out what is reason for that. 
Thanks for your help.

From my point of view this is issue can be closed, but perhaps add this information to the description of the adapter.

**Comment by ozboss** [comment]
I have the same problem. Can you please tell me how to solve this? I didn't start any servers by myselfe other then iobroker.

**Comment by skar-cgn** [comment]
As mentioned above please check what else is running on the same port.
