### ISSUE TITLE
Serielle Schnittstelle einfügen

### ISSUE THREAD

**Issue by Tobi4** [ioBroker/ioBroker.sonoff#88]
Wäre es möglich folgende Topics mit rein zu nehmen?

cmnd/DEVICENAME/SerialSend
stat/DEVICENAME/RESULT
tele/DEVICENAME/RESULT

![Topics](https://user-images.githubusercontent.com/50216483/57100347-0530aa80-6d1f-11e9-82e7-33a260a9c0f4.png)

**Comment by Pewibe** [comment]
Hallo Tobi
Woher nimmst du hier die Begeisterung, die Projektverantwortlichen nach Hilfe bzw. Erweiterungen zu fragen? Ich habe am 4.02.2019 mit der #83 gefragt, ob noch einer lebt. Das wurde bis heute nicht beantwortet. Weißt du da mehr bzw. hast berechtigte Hoffnung, dass du erhört wirst?

**Comment by Apollon77** [comment]
@Pewibe Sehr negative Einstellung hier ... und dein Issue 83 könnte man direkt schliesen weil es kein Issue ist. Natürlich ist dieser wie jeder andere Adapter der nicht abgekündigt ist noch dabei ... 
Wir nehmen PRs sehr gern an

**Comment by Bettman66** [comment]
Du kannst das Objekt SerialSend5 selber als String hinzufügen und Daten senden. SerialReceived kannst sdu auch mit einer Regel oder Script von Tasmota an den Adapter senden.
