### ISSUE TITLE
Retained Messages

### ISSUE THREAD

**Issue by Jetiman** [ioBroker/ioBroker.sonoff#89]
Hi,

ich vermisse eine Option womit ich den Broker immer Vorrang gebe.

Wenn z.b in der Zeit wo ein Sonoff grade neustartet oder das Wlan abbricht ein Status im Broker gesetzt wird, schreibt der Sonoff einfach **sein** Status in den Broker.

Ich möchte es aber das der Sonoff den Status aus dem Broker übernimmt wenn dieser sich in seiner Abwesenheit geändert hat.

Gibt es da eine Lösung für?

**Comment by Xyolyp** [comment]
Ich möchte mich hier einklinken und anmerken, dass ich es auch begrüßen würde, wenn Steuerbefehle, die im Objekt in der Zwischenzeit gesetzt wurden, bei einer erfolgreichen Verbindung mit dem Gerät gesendet werden würden. Wenn dann nach einem Neustart die Skripte schneller starten als sich die Tasmota Geräte wieder verbinden gehen aktuell Steuerbefehle verloren.
