### ISSUE TITLE
 Alive State wir nicht nach false aktualisiert

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.sonoff#91]
Hallo zusammen,

mir ist aufgefallen, dass sich nach dem Ausfall eines Devices der State.alive im Adapter nicht verändert. Nur nach einem manuellen Neustart des Adapters, was ja keine Lösung darstellt.
Bisher hatte ich es so verstanden, dass durch die Einstellung "Client Zeitüberschreitung" im Adapter diese Zeit definiert wird, so dass der State danach auf "false" wechselt!?
Ich habe zusätzlich die damals von @gemu2015 implementierte Funktion zur Erstellung von States tele/SENSOR/ tele/STATE / stat/RESULT alle aktiviert.
Hat hat jemand eine Lösungsidee?
Grüße
Fabian

**Comment by dirkhe** [comment]
Ist doppelt und Quickfix ist hier beschrieben
https://github.com/ioBroker/ioBroker.sonoff/issues/58
