### ISSUE TITLE
sonoff.0 startet nicht (wechselt nicht auf grün)

### ISSUE THREAD

**Issue by Philipp92** [ioBroker/ioBroker.sonoff#92]
Hallo, ich habe den sonoff Adapter in meinem iobroker installiert und dort Benutzername und Passwort hinterlegt. In meinem geflashten Sonoff Basic habe ich MQTT aktiviert und den gleichen Benutzer hinterlegt.
Die Adresse vom Raspberry bzw. iobroker ist natürlich auch hinterlegt.
Aber der Adapter läuft einfach nicht.

Kann mir da jemand helfen?

Viele Grüße, Philipp

**Hier der Log dazu:**
host.raspberrypi | 2019-06-05 10:25:59.041 | info | Restart adapter system.adapter.sonoff.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-06-05 10:25:59.041 | error | instance system.adapter.sonoff.0 terminated with code 0 (OK)
Caught | 2019-06-05 10:25:59.041 | error | by controller[0]:   port: 1883 }
Caught | 2019-06-05 10:25:59.041 | error | by controller[0]:   address: '0.0.0.0',
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:   syscall: 'listen',
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:   code: 'EADDRINUSE',
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:   errno: 'EADDRINUSE',
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:142:11)
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:     at doListen (net.js:1510:7)
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:     at listenInCluster (net.js:1401:12)
Caught | 2019-06-05 10:25:59.040 | error | by controller[0]:     at Server.setupListenHandle [as _listen2] (net.js:1360:14)
Caught | 2019-06-05 10:25:59.039 | error | by controller[0]: { Error: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2019-06-05 10:25:58.993 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
sonoff.0 | 2019-06-05 10:25:58.993 | error | at _combinedTickCallback (internal/process/next_tick.js:142:11)
sonoff.0 | 2019-06-05 10:25:58.993 | error | at doListen (net.js:1510:7)
sonoff.0 | 2019-06-05 10:25:58.993 | error | at listenInCluster (net.js:1401:12)
sonoff.0 | 2019-06-05 10:25:58.993 | error | at Server.setupListenHandle [as _listen2] (net.js:1360:14)
sonoff.0 | 2019-06-05 10:25:58.993 | error | Error: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2019-06-05 10:25:58.992 | error | uncaught exception: listen EADDRINUSE 0.0.0.0:1883
sonoff.0 | 2019-06-05 10:25:58.910 | info | starting. Version 2.2.2 in /opt/iobroker/node_modules/iobroker.sonoff, node: v8.16.0
host.raspberrypi | 2019-06-05 10:25:57.728 | info | instance system.adapter.sonoff.0 started with pid 3349

**Comment by Apollon77** [comment]
Ja, finde raus welcher andere Prozess den Port 1883 belegt, weil ioBroker kann nicht weil da schon was läuft. Support dazu am besten im Forum
