### ISSUE TITLE
Shutter Support (MQTT Shutter Value)

### ISSUE THREAD

**Issue by onkeldittmayer** [ioBroker/ioBroker.sonoff#95]
Hi,

Theo just implement the Shutter Code from StefanBode's fork in the develop Branch.
However: when you SetOption80 to 1 (at least you should have two relays) you activate Shutter support. Here you got special MQTT Data what the Sonoff Adapter don't expect (or accept).
stat/RolloEZ/SHUTTER1 = "value" is set on every Shutter hold and very needfull for smothless Shutter support. The code Support up to 4 Shutter. So a implementation in the Sonof ioBroker-Adapter would be great.

Here full Tasmota Log:

22:13:12 MQT: stat/RolloEZ/RESULT = {"POWER1":"ON"}
22:13:12 MQT: stat/RolloEZ/POWER1 = ON
22:13:12 SHT: Shutter 0: Real Pos: 1900, Target 46000, source: Shutter, start-pos: 4 %, direction: 1, rtcshutter: 0.0 [s]
22:13:13 SHT: Shutter 0: Real Pos: 3600, Target 46000, source: Shutter, start-pos: 4 %, direction: 1, rtcshutter: 0.9 [s]
22:13:14 MQT: stat/RolloEZ/RESULT = {"POWER1":"OFF"}
22:13:14 MQT: stat/RolloEZ/POWER1 = OFF
22:13:14 MQT: stat/RolloEZ/SHUTTER1 = 90
22:13:14 MQT: tele/RolloEZ/RESULT = {"Shutter1":{"Position":90,"direction":0}}

and by the way:
Thanks for your great work!

**Comment by onkeldittmayer** [comment]
OK just solved it by myself.
Just add in /lib/datapoints.js

SHUTTER1:       {type: 'number', role: 'state',                   read: true, write: false},

restart the adapter
have fun

**Comment by modmax** [comment]
Ticket kann geschlossen werden.
Aktuell in der 2.3.3 vorhanden.
