### ISSUE TITLE
Sonoff driver not correct parse JSON?

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.sonoff#96]
Hello, friends! When i send JSON from 15 esp8266 with lastest Tasmota, JSON, which send on sonoff is well..But when it's pasing, the time, for example is not correct..
![Скриншот 20-10-2019 164724](https://user-images.githubusercontent.com/6728198/67160467-b1ac2a80-f359-11e9-838f-f41cb3ffbb2e.jpg)
JS-controller is 2.0.34..

![Скриншот 20-10-2019 205731](https://user-images.githubusercontent.com/6728198/67163872-fdbc9680-f37c-11e9-9ecd-c49e1decba34.jpg)
Maybe in my case with thins thing: "npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3"  ??

**Comment by GermanBluefox** [comment]
Can you please provide the JSON string from sonoff?
This one with `tele/AC1/STATE={"Time": ,...`

**Comment by GermanBluefox** [comment]
Are you sure, that your ALL clients have all different names (clientIds)

**Comment by itProfi** [comment]
22:52:31 MQT: tele/pump/SENSOR = {"Time":"2019-10-21T22:52:31","ENERGY":{"TotalStartTime":"2019-09-29T21:07:46","Total":[36.130,3.869,27.505],"Yesterday":1.643,"Today":2.468,"Period":0,"Power":3,"ApparentPower":12,"ReactivePower":11,"Factor":0.26,"Voltage":222,"Current":0.05}}
Yes, of course all different names -
![Скриншот 21-10-2019 225228](https://user-images.githubusercontent.com/6728198/67238282-94f51d00-f455-11e9-8d02-d6fa682e6aa3.jpg)

**Comment by itProfi** [comment]
I install lastest JS-controller, sonoff 2.2.3- the same things

**Comment by itProfi** [comment]
I see, that sonoff driver maybe skips each second? teleperiod (in picture teleperiod=5)
![Скриншот 21-10-2019 230759](https://user-images.githubusercontent.com/6728198/67239410-d38bd700-f457-11e9-9b38-941237d65f9d.jpg)
![Скриншот 21-10-2019 230750](https://user-images.githubusercontent.com/6728198/67239413-d71f5e00-f457-11e9-9bef-20273b894874.jpg)

**Comment by itProfi** [comment]
Yes, driver not parce any teleperiod..just randomise..maybe mqtt part guilty?

**Comment by itProfi** [comment]
After update to version 2.3.0 (lastest, bump) -time - same errors:
![Скриншот 22-10-2019 195257](https://user-images.githubusercontent.com/6728198/67310057-bb729100-f505-11e9-91dd-eb54ebef3cf4.jpg)
And new erros:
````
sonoff.0 | 2019-10-22 19:50:01.810 | error | (17548) After: {"Time":"2019-10-22T19:50:01","DS18B20":{"Temperature":24.4},"BME280":{"Temperature":24.3,"Humidity":55.7,"Pressure":766},"BH1750":{"Illuminance":0},"PressureUnit":"mmHg","TempUnit":"C
-- | -- | -- | --
sonoff.0 | 2019-10-22 19:50:01.810 | error | (17548) Before: {"Time":"2019-10-22T19:50:01","DS18B20":{"Temperature":24.4},"BME280":{"Temperature":24.3,"Humidity":55.7,"Pressure":766},"BH1750":{"Illuminance":0},"PressureUnit":"mmHg","TempUnit":"
````

**Comment by itProfi** [comment]
Any chances?

**Comment by itProfi** [comment]
Any chances?

**Comment by Apollon77** [comment]
So in fact the device is generating an invalid JSON by using "NaN" as a value or how I should understand the topic now ... with your code fix ...
The official fix would be to have the device send valid JSON ;-)
Yes we could check the incoming text to **hopefully** detect a NaN value (and hope that it not part of any string which would lead to a wrong replace) ...

**Comment by algar42** [comment]
Look here - https://github.com/arendst/Tasmota/issues/4147
It seems that it was updated to have correct JSON already a year ago... Or I'm wrong?

**Comment by itProfi** [comment]
Dear friends. Sonoff driver not work fine with js-controller 2.x! Dont waste you time.

**Comment by Apollon77** [comment]
Sorry but this is not helpful. If there are problems with js-controller 2.0 please provide more details in an own issue or forum. 

Controller 2 is the Future base and so the adapter or controller needs to be fixed!

**Comment by itProfi** [comment]
Thanks for all! I upgrade js-controller-2.21 and redis databse and all fine!
