### ISSUE TITLE
Probleme nach Update auf 2.3.0

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.sonoff#99]
Ich habe nach dem Update mit einem Gerät Probleme.
Es kommt im Log immer die Fehlermeldung:
```
sonoff.0	2019-10-22 22:27:00.009	error	(24241) After: {"Time":"2019-10-22T21:26:59","Switch1":"OFF","BME280":{"Temperature":22.3,"Humidity":59.8,"Pressure":992.7},"BH1750":{"Illuminance":0},"PressureUnit":"hPa","TempUnit":"C"}
sonoff.0	2019-10-22 22:27:00.008	error	(24241) Before: {"Time":"2019-10-22T21:26:59","Switch1":"OFF","BME280":{"Temperature":22.3,"Humidity":59.8,"Pressure":992.7},"BH1750":{"Illuminance":0},"PressureUnit":"hPa","TempUnit":"C"}
```

Zurück auf 2.2.3 ist der Fehler weg.
Taucht aber seltsamerweise nur bei einem Gerät auf. Die Fehlermeldung kommt im Normalfall alle 5 Minuten und lässt sich durch einen Neustart des Sonoff auslösen.
Betroffener Sonoff: Sonoff SV mit Tasmota 6.6.0

**Comment by FabianHM** [comment]
Hallo @GermanBluefox,

bei mir das gleiche Problem.
 Abhängig vom der Logtime des sonoff erscheint die Meldung.
![SonoffError2 3](https://user-images.githubusercontent.com/26110738/67368062-eea13880-f576-11e9-8e54-b0e80aefeedb.JPG)

Die Bezeichnung des state hat sich übrigens auch nicht geändert nach ""indicator.connected".
Fehlende states, wie z.b. der fehlenden "WifiConfig" wir auch nicht übertragen, bzw. fehlt nach dem manuellen löschen nun weiterhin in den Objekten.

**Comment by Chaot1** [comment]
Oh! Auch mit dem BH1750. 
Ob das zusammenhängt?

**Comment by Chaot1** [comment]
Eben Version 2.3.1 aktiviert. Fehler scheint behoben zu sein.
